// AP German Language & Culture — Practice Set 1
// Theme: Familien und Gemeinschaften / Persönliche und öffentliche Identitäten

const GERMAN_SET1_MC = [

  // ── Questions 1–6 ── Anzeige / Plakat ──────────────────────────────────────
  {q:"<div class=\"stimulus\"><pre>MEHRGENERATIONENHAUS SONNENHOF\nIhre Anlaufstelle für Jung und Alt\n\nWir suchen ab sofort:\n• Ehrenamtliche Helfer/innen für die Hausaufgabenbetreuung (Di & Do, 14–17 Uhr)\n• Seniorenbegleiter/innen für Ausflüge und Freizeitaktivitäten\n• Kursleiter/innen für Handarbeit, Kochen und digitale Medien\n\nWas wir bieten:\n– Kostenlose Schulungen und Zertifikate\n– Aufwandsentschädigung: 50 € pro Monat\n– Ein herzliches, multikulturelles Team\n\nInteressiert? Melden Sie sich bis zum 30. April bei:\nFrau Dagmar Hofmann, Tel. 0511-887 6234\noder per E-Mail: d.hofmann@sonnenhof-hannover.de\n\nGemeinsam stark – für alle Generationen!</pre></div><b>1.</b> Welche Art von Hilfe sucht das Mehrgenerationenhaus Sonnenhof?", choices:["Bezahlte Vollzeitangestellte für die Verwaltung","Freiwillige für verschiedene Betreuungsaufgaben","Auszubildende für Pflege- und Sozialberufe","Praktikanten für ein Schulprojekt"], answer:1},

  {q:"<div class=\"stimulus\"><pre>MEHRGENERATIONENHAUS SONNENHOF\nIhre Anlaufstelle für Jung und Alt\n\nWir suchen ab sofort:\n• Ehrenamtliche Helfer/innen für die Hausaufgabenbetreuung (Di & Do, 14–17 Uhr)\n• Seniorenbegleiter/innen für Ausflüge und Freizeitaktivitäten\n• Kursleiter/innen für Handarbeit, Kochen und digitale Medien\n\nWas wir bieten:\n– Kostenlose Schulungen und Zertifikate\n– Aufwandsentschädigung: 50 € pro Monat\n– Ein herzliches, multikulturelles Team\n\nInteressiert? Melden Sie sich bis zum 30. April bei:\nFrau Dagmar Hofmann, Tel. 0511-887 6234\noder per E-Mail: d.hofmann@sonnenhof-hannover.de\n\nGemeinsam stark – für alle Generationen!</pre></div><b>2.</b> Wann findet die Hausaufgabenbetreuung statt?", choices:["Montags und mittwochs am Nachmittag","Dienstags und donnerstags von 14 bis 17 Uhr","Täglich von 9 bis 12 Uhr","An den Wochenenden nach Absprache"], answer:1},

  {q:"<div class=\"stimulus\"><pre>MEHRGENERATIONENHAUS SONNENHOF\nIhre Anlaufstelle für Jung und Alt\n\nWir suchen ab sofort:\n• Ehrenamtliche Helfer/innen für die Hausaufgabenbetreuung (Di & Do, 14–17 Uhr)\n• Seniorenbegleiter/innen für Ausflüge und Freizeitaktivitäten\n• Kursleiter/innen für Handarbeit, Kochen und digitale Medien\n\nWas wir bieten:\n– Kostenlose Schulungen und Zertifikate\n– Aufwandsentschädigung: 50 € pro Monat\n– Ein herzliches, multikulturelles Team\n\nInteressiert? Melden Sie sich bis zum 30. April bei:\nFrau Dagmar Hofmann, Tel. 0511-887 6234\noder per E-Mail: d.hofmann@sonnenhof-hannover.de\n\nGemeinsam stark – für alle Generationen!</pre></div><b>3.</b> Was erhalten die ehrenamtlichen Helfer laut der Anzeige?", choices:["Ein monatliches Gehalt von 500 Euro","Kostenlose Schulungen und eine kleine Aufwandsentschädigung","Freie Unterkunft im Sonnenhof","Rabatte auf städtische Freizeitangebote"], answer:1},

  {q:"<div class=\"stimulus\"><pre>MEHRGENERATIONENHAUS SONNENHOF\nIhre Anlaufstelle für Jung und Alt\n\nWir suchen ab sofort:\n• Ehrenamtliche Helfer/innen für die Hausaufgabenbetreuung (Di & Do, 14–17 Uhr)\n• Seniorenbegleiter/innen für Ausflüge und Freizeitaktivitäten\n• Kursleiter/innen für Handarbeit, Kochen und digitale Medien\n\nWas wir bieten:\n– Kostenlose Schulungen und Zertifikate\n– Aufwandsentschädigung: 50 € pro Monat\n– Ein herzliches, multikulturelles Team\n\nInteressiert? Melden Sie sich bis zum 30. April bei:\nFrau Dagmar Hofmann, Tel. 0511-887 6234\noder per E-Mail: d.hofmann@sonnenhof-hannover.de\n\nGemeinsam stark – für alle Generationen!</pre></div><b>4.</b> Wofür werden Kursleiter gesucht?", choices:["Für Fremdsprachenkurse und Nachhilfe","Für Handarbeit, Kochen und digitale Medien","Für Sport, Musik und Theaterspiel","Für Erste-Hilfe-Kurse und Gesundheitsvorsorge"], answer:1},

  {q:"<div class=\"stimulus\"><pre>MEHRGENERATIONENHAUS SONNENHOF\nIhre Anlaufstelle für Jung und Alt\n\nWir suchen ab sofort:\n• Ehrenamtliche Helfer/innen für die Hausaufgabenbetreuung (Di & Do, 14–17 Uhr)\n• Seniorenbegleiter/innen für Ausflüge und Freizeitaktivitäten\n• Kursleiter/innen für Handarbeit, Kochen und digitale Medien\n\nWas wir bieten:\n– Kostenlose Schulungen und Zertifikate\n– Aufwandsentschädigung: 50 € pro Monat\n– Ein herzliches, multikulturelles Team\n\nInteressiert? Melden Sie sich bis zum 30. April bei:\nFrau Dagmar Hofmann, Tel. 0511-887 6234\noder per E-Mail: d.hofmann@sonnenhof-hannover.de\n\nGemeinsam stark – für alle Generationen!</pre></div><b>5.</b> Wie soll man sich bewerben?", choices:["Durch persönliche Vorstellung in der Geschäftsstelle","Telefonisch oder per E-Mail bei Frau Hofmann","Mit schriftlicher Bewerbungsmappe per Post","Über ein Online-Formular auf der Webseite"], answer:1},

  {q:"<div class=\"stimulus\"><pre>MEHRGENERATIONENHAUS SONNENHOF\nIhre Anlaufstelle für Jung und Alt\n\nWir suchen ab sofort:\n• Ehrenamtliche Helfer/innen für die Hausaufgabenbetreuung (Di & Do, 14–17 Uhr)\n• Seniorenbegleiter/innen für Ausflüge und Freizeitaktivitäten\n• Kursleiter/innen für Handarbeit, Kochen und digitale Medien\n\nWas wir bieten:\n– Kostenlose Schulungen und Zertifikate\n– Aufwandsentschädigung: 50 € pro Monat\n– Ein herzliches, multikulturelles Team\n\nInteressiert? Melden Sie sich bis zum 30. April bei:\nFrau Dagmar Hofmann, Tel. 0511-887 6234\noder per E-Mail: d.hofmann@sonnenhof-hannover.de\n\nGemeinsam stark – für alle Generationen!</pre></div><b>6.</b> Was ist der Hauptzweck des Mehrgenerationenhauses Sonnenhof?", choices:["Günstige Wohnungen für Senioren anzubieten","Verschiedene Generationen zu verbinden und zu unterstützen","Kinderbetreuung für berufstätige Eltern anzubieten","Ein professionelles Pflegeheim zu betreiben"], answer:1},

  // ── Questions 7–12 ── Brief der Gastfamilie ────────────────────────────────
  {q:"<div class=\"stimulus\"><pre>Freiburg, den 3. März\n\nLiebe Emma,\n\nwir freuen uns sehr, dass du im Juli für drei Wochen zu uns kommen wirst! Ich möchte dir schon mal ein bisschen über unsere Familie erzählen, damit du weißt, was dich erwartet.\n\nWir sind die Familie Brinkmann: mein Mann Thomas (47), ich, Sabine (44), unsere Tochter Lena (16) und unser Sohn Felix (13). Wir wohnen in einem Reihenhaus am Stadtrand von Freiburg, nicht weit vom Schwarzwald. Lena freut sich schon sehr auf dich – sie lernt selbst Englisch und möchte sich gern mit dir unterhalten. Felix ist eher schüchtern, aber sobald er dich kennt, redet er ununterbrochen über Fußball!\n\nZu deiner Frage über Haustiere: Wir haben einen Hund namens Bello und zwei Katzen. Wenn du allergisch bist, sag uns bitte sofort Bescheid, dann finden wir eine Lösung.\n\nWas das Essen angeht: Wir kochen meist frisch und essen abends zusammen. Wir haben auch türkische Nachbarn, mit denen wir oft grillen – du wirst also echte deutsche und internationale Küche kennenlernen!\n\nWir sind gespannt auf dich und auf den Sommer!\n\nHerzliche Grüße,\nSabine Brinkmann</pre></div><b>7.</b> Wer schreibt diesen Brief?", choices:["Emma, die Austauschschülerin","Thomas Brinkmann, der Vater","Sabine Brinkmann, die Mutter der Gastfamilie","Lena, die Tochter der Gastfamilie"], answer:2},

  {q:"<div class=\"stimulus\"><pre>Freiburg, den 3. März\n\nLiebe Emma,\n\nwir freuen uns sehr, dass du im Juli für drei Wochen zu uns kommen wirst! Ich möchte dir schon mal ein bisschen über unsere Familie erzählen, damit du weißt, was dich erwartet.\n\nWir sind die Familie Brinkmann: mein Mann Thomas (47), ich, Sabine (44), unsere Tochter Lena (16) und unser Sohn Felix (13). Wir wohnen in einem Reihenhaus am Stadtrand von Freiburg, nicht weit vom Schwarzwald. Lena freut sich schon sehr auf dich – sie lernt selbst Englisch und möchte sich gern mit dir unterhalten. Felix ist eher schüchtern, aber sobald er dich kennt, redet er ununterbrochen über Fußball!\n\nZu deiner Frage über Haustiere: Wir haben einen Hund namens Bello und zwei Katzen. Wenn du allergisch bist, sag uns bitte sofort Bescheid, dann finden wir eine Lösung.\n\nWas das Essen angeht: Wir kochen meist frisch und essen abends zusammen. Wir haben auch türkische Nachbarn, mit denen wir oft grillen – du wirst also echte deutsche und internationale Küche kennenlernen!\n\nWir sind gespannt auf dich und auf den Sommer!\n\nHerzliche Grüße,\nSabine Brinkmann</pre></div><b>8.</b> Wie wird Felix im Brief beschrieben?", choices:["Sehr gesprächig und offen gegenüber Fremden","Schüchtern, aber redet viel über Fußball, sobald er jemanden kennt","Sportlich und sehr an Musik interessiert","Hilfsbereit und immer gut gelaunt"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Freiburg, den 3. März\n\nLiebe Emma,\n\nwir freuen uns sehr, dass du im Juli für drei Wochen zu uns kommen wirst! Ich möchte dir schon mal ein bisschen über unsere Familie erzählen, damit du weißt, was dich erwartet.\n\nWir sind die Familie Brinkmann: mein Mann Thomas (47), ich, Sabine (44), unsere Tochter Lena (16) und unser Sohn Felix (13). Wir wohnen in einem Reihenhaus am Stadtrand von Freiburg, nicht weit vom Schwarzwald. Lena freut sich schon sehr auf dich – sie lernt selbst Englisch und möchte sich gern mit dir unterhalten. Felix ist eher schüchtern, aber sobald er dich kennt, redet er ununterbrochen über Fußball!\n\nZu deiner Frage über Haustiere: Wir haben einen Hund namens Bello und zwei Katzen. Wenn du allergisch bist, sag uns bitte sofort Bescheid, dann finden wir eine Lösung.\n\nWas das Essen angeht: Wir kochen meist frisch und essen abends zusammen. Wir haben auch türkische Nachbarn, mit denen wir oft grillen – du wirst also echte deutsche und internationale Küche kennenlernen!\n\nWir sind gespannt auf dich und auf den Sommer!\n\nHerzliche Grüße,\nSabine Brinkmann</pre></div><b>9.</b> Warum erwähnt Sabine die Haustiere?", choices:["Um Emma zu zeigen, dass sie Tiere liebt","Weil Emma in ihrem Brief danach gefragt hat","Damit Emma Geschenke für die Tiere mitbringt","Weil Haustiere in Deutschland besonders wichtig sind"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Freiburg, den 3. März\n\nLiebe Emma,\n\nwir freuen uns sehr, dass du im Juli für drei Wochen zu uns kommen wirst! Ich möchte dir schon mal ein bisschen über unsere Familie erzählen, damit du weißt, was dich erwartet.\n\nWir sind die Familie Brinkmann: mein Mann Thomas (47), ich, Sabine (44), unsere Tochter Lena (16) und unser Sohn Felix (13). Wir wohnen in einem Reihenhaus am Stadtrand von Freiburg, nicht weit vom Schwarzwald. Lena freut sich schon sehr auf dich – sie lernt selbst Englisch und möchte sich gern mit dir unterhalten. Felix ist eher schüchtern, aber sobald er dich kennt, redet er ununterbrochen über Fußball!\n\nZu deiner Frage über Haustiere: Wir haben einen Hund namens Bello und zwei Katzen. Wenn du allergisch bist, sag uns bitte sofort Bescheid, dann finden wir eine Lösung.\n\nWas das Essen angeht: Wir kochen meist frisch und essen abends zusammen. Wir haben auch türkische Nachbarn, mit denen wir oft grillen – du wirst also echte deutsche und internationale Küche kennenlernen!\n\nWir sind gespannt auf dich und auf den Sommer!\n\nHerzliche Grüße,\nSabine Brinkmann</pre></div><b>10.</b> Was erfährt Emma über das Essen bei den Brinkmanns?", choices:["Die Familie isst hauptsächlich in Restaurants","Sie kochen frisch und essen gemeinsam, oft auch mit Nachbarn","Frühstück ist die wichtigste Mahlzeit im Haushalt","Emma soll ihr eigenes Essen selbst zubereiten"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Freiburg, den 3. März\n\nLiebe Emma,\n\nwir freuen uns sehr, dass du im Juli für drei Wochen zu uns kommen wirst! Ich möchte dir schon mal ein bisschen über unsere Familie erzählen, damit du weißt, was dich erwartet.\n\nWir sind die Familie Brinkmann: mein Mann Thomas (47), ich, Sabine (44), unsere Tochter Lena (16) und unser Sohn Felix (13). Wir wohnen in einem Reihenhaus am Stadtrand von Freiburg, nicht weit vom Schwarzwald. Lena freut sich schon sehr auf dich – sie lernt selbst Englisch und möchte sich gern mit dir unterhalten. Felix ist eher schüchtern, aber sobald er dich kennt, redet er ununterbrochen über Fußball!\n\nZu deiner Frage über Haustiere: Wir haben einen Hund namens Bello und zwei Katzen. Wenn du allergisch bist, sag uns bitte sofort Bescheid, dann finden wir eine Lösung.\n\nWas das Essen angeht: Wir kochen meist frisch und essen abends zusammen. Wir haben auch türkische Nachbarn, mit denen wir oft grillen – du wirst also echte deutsche und internationale Küche kennenlernen!\n\nWir sind gespannt auf dich und auf den Sommer!\n\nHerzliche Grüße,\nSabine Brinkmann</pre></div><b>11.</b> Wo wohnt die Familie Brinkmann?", choices:["Im Stadtzentrum von Freiburg, nahe dem Münster","In einem Reihenhaus am Stadtrand, nicht weit vom Schwarzwald","Auf einem Bauernhof außerhalb der Stadt","In einer großen Mietwohnung in Freiburg-Nord"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Freiburg, den 3. März\n\nLiebe Emma,\n\nwir freuen uns sehr, dass du im Juli für drei Wochen zu uns kommen wirst! Ich möchte dir schon mal ein bisschen über unsere Familie erzählen, damit du weißt, was dich erwartet.\n\nWir sind die Familie Brinkmann: mein Mann Thomas (47), ich, Sabine (44), unsere Tochter Lena (16) und unser Sohn Felix (13). Wir wohnen in einem Reihenhaus am Stadtrand von Freiburg, nicht weit vom Schwarzwald. Lena freut sich schon sehr auf dich – sie lernt selbst Englisch und möchte sich gern mit dir unterhalten. Felix ist eher schüchtern, aber sobald er dich kennt, redet er ununterbrochen über Fußball!\n\nZu deiner Frage über Haustiere: Wir haben einen Hund namens Bello und zwei Katzen. Wenn du allergisch bist, sag uns bitte sofort Bescheid, dann finden wir eine Lösung.\n\nWas das Essen angeht: Wir kochen meist frisch und essen abends zusammen. Wir haben auch türkische Nachbarn, mit denen wir oft grillen – du wirst also echte deutsche und internationale Küche kennenlernen!\n\nWir sind gespannt auf dich und auf den Sommer!\n\nHerzliche Grüße,\nSabine Brinkmann</pre></div><b>12.</b> Welches Ziel hat Lena in Bezug auf Emma?", choices:["Sie will Emma das Kochen beibringen","Sie möchte mit Emma Englisch üben und sich unterhalten","Sie plant, Emma den Schwarzwald zu zeigen","Sie will, dass Emma ihr bei den Hausaufgaben hilft"], answer:1},

  // ── Questions 13–18 ── Zeitungsartikel ────────────────────────────────────
  {q:"<div class=\"stimulus\"><pre>DAS WANDEL DER DEUTSCHEN FAMILIE\n\nFrankfurter Allgemeine Zeitung, 12. Februar\n\nDie traditionelle Kleinfamilie – Vater, Mutter, zwei Kinder – ist in Deutschland längst nicht mehr die einzige Lebensform. Laut dem Statistischen Bundesamt lebten 2023 rund 41 Prozent aller Haushalte als Einpersonenhaushalte, während Patchwork-Familien, gleichgeschlechtliche Partnerschaften und Alleinerziehende eine immer größere Rolle spielen.\n\nBesonders auffällig ist der Anstieg der Mehrgenerationenhaushalte: Immer mehr junge Erwachsene ziehen nach dem Studium wieder zu ihren Eltern, nicht zuletzt wegen der steigenden Mietpreise in Großstädten wie München, Hamburg und Berlin. Gleichzeitig kehren ältere Menschen, die früher in Seniorenheimen lebten, zunehmend in den Familienkreis zurück.\n\n„Die Familie bleibt der wichtigste soziale Anker für die meisten Menschen\", sagt Prof. Dr. Heike Maaß, Soziologin an der Universität Frankfurt. „Doch ihre Formen werden vielfältiger, und das ist kein Zeichen des Niedergangs, sondern des Wandels.\"\n\nKritiker hingegen warnen vor dem Verlust gemeinsamer Familienmahlzeiten und des Zusammenhalts über Generationen. Studien zeigen, dass Kinder aus Familien, in denen regelmäßig zusammen gegessen wird, im Schnitt bessere schulische Leistungen und ein stärkeres Gemeinschaftsgefühl entwickeln.</pre></div><b>13.</b> Was ist laut dem Artikel ein wichtiger Trend in der deutschen Gesellschaft?", choices:["Die Rückkehr zur traditionellen Großfamilie auf dem Land","Die zunehmende Vielfalt der Familienformen","Der Rückgang der Geburtenrate auf unter 1,0","Die wachsende Bedeutung von Altersheimen"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DAS WANDEL DER DEUTSCHEN FAMILIE\n\nFrankfurter Allgemeine Zeitung, 12. Februar\n\nDie traditionelle Kleinfamilie – Vater, Mutter, zwei Kinder – ist in Deutschland längst nicht mehr die einzige Lebensform. Laut dem Statistischen Bundesamt lebten 2023 rund 41 Prozent aller Haushalte als Einpersonenhaushalte, während Patchwork-Familien, gleichgeschlechtliche Partnerschaften und Alleinerziehende eine immer größere Rolle spielen.\n\nBesonders auffällig ist der Anstieg der Mehrgenerationenhaushalte: Immer mehr junge Erwachsene ziehen nach dem Studium wieder zu ihren Eltern, nicht zuletzt wegen der steigenden Mietpreise in Großstädten wie München, Hamburg und Berlin. Gleichzeitig kehren ältere Menschen, die früher in Seniorenheimen lebten, zunehmend in den Familienkreis zurück.\n\n„Die Familie bleibt der wichtigste soziale Anker für die meisten Menschen\", sagt Prof. Dr. Heike Maaß, Soziologin an der Universität Frankfurt. „Doch ihre Formen werden vielfältiger, und das ist kein Zeichen des Niedergangs, sondern des Wandels.\"\n\nKritiker hingegen warnen vor dem Verlust gemeinsamer Familienmahlzeiten und des Zusammenhalts über Generationen. Studien zeigen, dass Kinder aus Familien, in denen regelmäßig zusammen gegessen wird, im Schnitt bessere schulische Leistungen und ein stärkeres Gemeinschaftsgefühl entwickeln.</pre></div><b>14.</b> Welcher Anteil der deutschen Haushalte bestand 2023 aus Einpersonenhaushalten?", choices:["Etwa 25 Prozent","Etwa 41 Prozent","Mehr als die Hälfte","Weniger als ein Fünftel"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DAS WANDEL DER DEUTSCHEN FAMILIE\n\nFrankfurter Allgemeine Zeitung, 12. Februar\n\nDie traditionelle Kleinfamilie – Vater, Mutter, zwei Kinder – ist in Deutschland längst nicht mehr die einzige Lebensform. Laut dem Statistischen Bundesamt lebten 2023 rund 41 Prozent aller Haushalte als Einpersonenhaushalte, während Patchwork-Familien, gleichgeschlechtliche Partnerschaften und Alleinerziehende eine immer größere Rolle spielen.\n\nBesonders auffällig ist der Anstieg der Mehrgenerationenhaushalte: Immer mehr junge Erwachsene ziehen nach dem Studium wieder zu ihren Eltern, nicht zuletzt wegen der steigenden Mietpreise in Großstädten wie München, Hamburg und Berlin. Gleichzeitig kehren ältere Menschen, die früher in Seniorenheimen lebten, zunehmend in den Familienkreis zurück.\n\n„Die Familie bleibt der wichtigste soziale Anker für die meisten Menschen\", sagt Prof. Dr. Heike Maaß, Soziologin an der Universität Frankfurt. „Doch ihre Formen werden vielfältiger, und das ist kein Zeichen des Niedergangs, sondern des Wandels.\"\n\nKritiker hingegen warnen vor dem Verlust gemeinsamer Familienmahlzeiten und des Zusammenhalts über Generationen. Studien zeigen, dass Kinder aus Familien, in denen regelmäßig zusammen gegessen wird, im Schnitt bessere schulische Leistungen und ein stärkeres Gemeinschaftsgefühl entwickeln.</pre></div><b>15.</b> Warum ziehen viele junge Erwachsene wieder zu ihren Eltern?", choices:["Wegen strenger Universitätsregeln für Wohnheimplätze","Wegen steigender Mietpreise in deutschen Großstädten","Wegen des Wunsches nach einem traditionelleren Lebensstil","Weil sie keine Arbeit finden können"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DAS WANDEL DER DEUTSCHEN FAMILIE\n\nFrankfurter Allgemeine Zeitung, 12. Februar\n\nDie traditionelle Kleinfamilie – Vater, Mutter, zwei Kinder – ist in Deutschland längst nicht mehr die einzige Lebensform. Laut dem Statistischen Bundesamt lebten 2023 rund 41 Prozent aller Haushalte als Einpersonenhaushalte, während Patchwork-Familien, gleichgeschlechtliche Partnerschaften und Alleinerziehende eine immer größere Role spielen.\n\nBesonders auffällig ist der Anstieg der Mehrgenerationenhaushalte: Immer mehr junge Erwachsene ziehen nach dem Studium wieder zu ihren Eltern, nicht zuletzt wegen der steigenden Mietpreise in Großstädten wie München, Hamburg und Berlin. Gleichzeitig kehren ältere Menschen, die früher in Seniorenheimen lebten, zunehmend in den Familienkreis zurück.\n\n„Die Familie bleibt der wichtigste soziale Anker für die meisten Menschen\", sagt Prof. Dr. Heike Maaß, Soziologin an der Universität Frankfurt. „Doch ihre Formen werden vielfältiger, und das ist kein Zeichen des Niedergangs, sondern des Wandels.\"\n\nKritiker hingegen warnen vor dem Verlust gemeinsamer Familienmahlzeiten und des Zusammenhalts über Generationen. Studien zeigen, dass Kinder aus Familien, in denen regelmäßig zusammen gegessen wird, im Schnitt bessere schulische Leistungen und ein stärkeres Gemeinschaftsgefühl entwickeln.</pre></div><b>16.</b> Was sagt Prof. Dr. Maaß über den Wandel der Familie?", choices:["Der Wandel sei gefährlich und müsse gestoppt werden","Die vielfältigeren Formen seien ein Zeichen des Wandels, kein Niedergang","Mehrgenerationenhaushalte seien wirtschaftlich nicht tragbar","Die Kleinfamilie sei immer noch die beste Form des Zusammenlebens"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DAS WANDEL DER DEUTSCHEN FAMILIE\n\nFrankfurter Allgemeine Zeitung, 12. Februar\n\nDie traditionelle Kleinfamilie – Vater, Mutter, zwei Kinder – ist in Deutschland längst nicht mehr die einzige Lebensform. Laut dem Statistischen Bundesamt lebten 2023 rund 41 Prozent aller Haushalte als Einpersonenhaushalte, während Patchwork-Familien, gleichgeschlechtliche Partnerschaften und Alleinerziehende eine immer größere Rolle spielen.\n\nBesonders auffällig ist der Anstieg der Mehrgenerationenhaushalte: Immer mehr junge Erwachsene ziehen nach dem Studium wieder zu ihren Eltern, nicht zuletzt wegen der steigenden Mietpreise in Großstädten wie München, Hamburg und Berlin. Gleichzeitig kehren ältere Menschen, die früher in Seniorenheimen lebten, zunehmend in den Familienkreis zurück.\n\n„Die Familie bleibt der wichtigste soziale Anker für die meisten Menschen\", sagt Prof. Dr. Heike Maaß, Soziologin an der Universität Frankfurt. „Doch ihre Formen werden vielfältiger, und das ist kein Zeichen des Niedergangs, sondern des Wandels.\"\n\nKritiker hingegen warnen vor dem Verlust gemeinsamer Familienmahlzeiten und des Zusammenhalts über Generationen. Studien zeigen, dass Kinder aus Familien, in denen regelmäßig zusammen gegessen wird, im Schnitt bessere schulische Leistungen und ein stärkeres Gemeinschaftsgefühl entwickeln.</pre></div><b>17.</b> Welchen Vorteil haben laut Studien gemeinsame Familienmahlzeiten?", choices:["Kinder lernen dadurch bessere Tischmanieren","Kinder entwickeln bessere schulische Leistungen und ein stärkeres Gemeinschaftsgefühl","Eltern sparen dadurch Zeit und Geld","Kinder werden gesünder und sind seltener krank"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DAS WANDEL DER DEUTSCHEN FAMILIE\n\nFrankfurter Allgemeine Zeitung, 12. Februar\n\nDie traditionelle Kleinfamilie – Vater, Mutter, zwei Kinder – ist in Deutschland längst nicht mehr die einzige Lebensform. Laut dem Statistischen Bundesamt lebten 2023 rund 41 Prozent aller Haushalte als Einpersonenhaushalte, während Patchwork-Familien, gleichgeschlechtliche Partnerschaften und Alleinerziehende eine immer größere Rolle spielen.\n\nBesonders auffällig ist der Anstieg der Mehrgenerationenhaushalte: Immer mehr junge Erwachsene ziehen nach dem Studium wieder zu ihren Eltern, nicht zuletzt wegen der steigenden Mietpreise in Großstädten wie München, Hamburg und Berlin. Gleichzeitig kehren ältere Menschen, die früher in Seniorenheimen lebten, zunehmend in den Familienkreis zurück.\n\n„Die Familie bleibt der wichtigste soziale Anker für die meisten Menschen\", sagt Prof. Dr. Heike Maaß, Soziologin an der Universität Frankfurt. „Doch ihre Formen werden vielfältiger, und das ist kein Zeichen des Niedergangs, sondern des Wandels.\"\n\nKritiker hingegen warnen vor dem Verlust gemeinsamer Familienmahlzeiten und des Zusammenhalts über Generationen. Studien zeigen, dass Kinder aus Familien, in denen regelmäßig zusammen gegessen wird, im Schnitt bessere schulische Leistungen und ein stärkeres Gemeinschaftsgefühl entwickeln.</pre></div><b>18.</b> Welche Aussage beschreibt die Haltung der Kritiker im Text am besten?", choices:["Sie befürworten den gesellschaftlichen Wandel der Familienformen","Sie befürchten, dass der Zusammenhalt zwischen Generationen verloren geht","Sie fordern staatliche Unterstützung für Einpersonenhaushalte","Sie glauben, dass Mehrgenerationenhaushalte unpraktisch sind"], answer:1},

  // ── Questions 19–24 ── Interview / Dialog: regionale vs. nationale Identität ─
  {q:"<div class=\"stimulus\"><pre>INTERVIEW: „BAYER ZUERST ODER DEUTSCHER ZUERST?\"\nDie Schülerzeitung „Echo\" interviewt drei Jugendliche aus Bayern.\n\nEcho: Fühlt ihr euch zuerst als Bayern oder als Deutsche?\n\nMarkus (17, München): Ich sag's ehrlich – ich bin zuerst Bayer. Das ist keine Absage an Deutschland, aber Bayern hat eine eigene Sprache, eigene Traditionen, eigenes Selbstbewusstsein. Wenn ich ins Ausland fahre, sag ich trotzdem, ich komme aus Deutschland. Aber zu Hause bin ich Bayer durch und durch.\n\nAylin (16, Nürnberg): Ich bin in einer türkisch-deutschen Familie groß geworden. Für mich ist das komplizierter. Ich bin Deutsche, Bayerin und gleichzeitig auch ein Teil der türkischen Kultur. Ich finde es schön, mehrere Identitäten zu haben – das macht mich reicher, nicht ärmer.\n\nLukas (17, Rosenheim): Ich denke, das hängt vom Kontext ab. Bei der Fußball-WM bin ich hundertprozentig Deutscher. Beim Oktoberfest bin ich Bayer. Identität ist nicht entweder-oder, sondern ein Mosaikstein, der sich je nach Situation ändert.</pre></div><b>19.</b> Was sagt Markus über seine Identität?", choices:["Er fühlt sich hauptsächlich als Europäer","Er identifiziert sich zuerst als Bayer, nennt sich aber im Ausland Deutschen","Er lehnt das Konzept nationaler Identität vollständig ab","Er fühlt sich gleichermaßen bayerisch und deutsch"], answer:1},

  {q:"<div class=\"stimulus\"><pre>INTERVIEW: „BAYER ZUERST ODER DEUTSCHER ZUERST?\"\nDie Schülerzeitung „Echo\" interviewt drei Jugendliche aus Bayern.\n\nEcho: Fühlt ihr euch zuerst als Bayern oder als Deutsche?\n\nMarkus (17, München): Ich sag's ehrlich – ich bin zuerst Bayer. Das ist keine Absage an Deutschland, aber Bayern hat eine eigene Sprache, eigene Traditionen, eigenes Selbstbewusstsein. Wenn ich ins Ausland fahre, sag ich trotzdem, ich komme aus Deutschland. Aber zu Hause bin ich Bayer durch und durch.\n\nAylin (16, Nürnberg): Ich bin in einer türkisch-deutschen Familie groß geworden. Für mich ist das komplizierter. Ich bin Deutsche, Bayerin und gleichzeitig auch ein Teil der türkischen Kultur. Ich finde es schön, mehrere Identitäten zu haben – das macht mich reicher, nicht ärmer.\n\nLukas (17, Rosenheim): Ich denke, das hängt vom Kontext ab. Bei der Fußball-WM bin ich hundertprozentig Deutscher. Beim Oktoberfest bin ich Bayer. Identität ist nicht entweder-oder, sondern ein Mosaikstein, der sich je nach Situation ändert.</pre></div><b>20.</b> Wie beschreibt Aylin ihre Identität?", choices:["Als rein deutsch, trotz ihrer türkischen Herkunft","Als Mosaik aus deutschen, bayerischen und türkischen Elementen","Als hauptsächlich türkisch, da sie in dieser Kultur aufgewachsen ist","Als schwierig, weil sie keine klare Zugehörigkeit fühlt"], answer:1},

  {q:"<div class=\"stimulus\"><pre>INTERVIEW: „BAYER ZUERST ODER DEUTSCHER ZUERST?\"\nDie Schülerzeitung „Echo\" interviewt drei Jugendliche aus Bayern.\n\nEcho: Fühlt ihr euch zuerst als Bayern oder als Deutsche?\n\nMarkus (17, München): Ich sag's ehrlich – ich bin zuerst Bayer. Das ist keine Absage an Deutschland, aber Bayern hat eine eigene Sprache, eigene Traditionen, eigenes Selbstbewusstsein. Wenn ich ins Ausland fahre, sag ich trotzdem, ich komme aus Deutschland. Aber zu Hause bin ich Bayer durch und durch.\n\nAylin (16, Nürnberg): Ich bin in einer türkisch-deutschen Familie groß geworden. Für mich ist das komplizierter. Ich bin Deutsche, Bayerin und gleichzeitig auch ein Teil der türkischen Kultur. Ich finde es schön, mehrere Identitäten zu haben – das macht mich reicher, nicht ärmer.\n\nLukas (17, Rosenheim): Ich denke, das hängt vom Kontext ab. Bei der Fußball-WM bin ich hundertprozentig Deutscher. Beim Oktoberfest bin ich Bayer. Identität ist nicht entweder-oder, sondern ein Mosaikstein, der sich je nach Situation ändert.</pre></div><b>21.</b> Was versteht Lukas unter dem Begriff \"Mosaik\" in Bezug auf Identität?", choices:["Identität ist festgelegt und unveränderlich","Identität setzt sich aus verschiedenen Teilen zusammen und ändert sich je nach Kontext","Identität entsteht nur durch nationale Symbole wie Flaggen und Hymnen","Man kann immer nur eine einzige Identität haben"], answer:1},

  {q:"<div class=\"stimulus\"><pre>INTERVIEW: „BAYER ZUERST ODER DEUTSCHER ZUERST?\"\nDie Schülerzeitung „Echo\" interviewt drei Jugendliche aus Bayern.\n\nEcho: Fühlt ihr euch zuerst als Bayern oder als Deutsche?\n\nMarkus (17, München): Ich sag's ehrlich – ich bin zuerst Bayer. Das ist keine Absage an Deutschland, aber Bayern hat eine eigene Sprache, eigene Traditionen, eigenes Selbstbewusstsein. Wenn ich ins Ausland fahre, sag ich trotzdem, ich komme aus Deutschland. Aber zu Hause bin ich Bayer durch und durch.\n\nAylin (16, Nürnberg): Ich bin in einer türkisch-deutschen Familie groß geworden. Für mich ist das komplizierter. Ich bin Deutsche, Bayerin und gleichzeitig auch ein Teil der türkischen Kultur. Ich finde es schön, mehrere Identitäten zu haben – das macht mich reicher, nicht ärmer.\n\nLukas (17, Rosenheim): Ich denke, das hängt vom Kontext ab. Bei der Fußball-WM bin ich hundertprozentig Deutscher. Beim Oktoberfest bin ich Bayer. Identität ist nicht entweder-oder, sondern ein Mosaikstein, der sich je nach Situation ändert.</pre></div><b>22.</b> Welche der drei Jugendlichen hat eine bikulturelle Hintergrundgeschichte?", choices:["Markus, weil er in München aufgewachsen ist","Aylin, weil sie in einer türkisch-deutschen Familie groß wurde","Lukas, weil er in Rosenheim und München gelebt hat","Alle drei haben denselben kulturellen Hintergrund"], answer:1},

  {q:"<div class=\"stimulus\"><pre>INTERVIEW: „BAYER ZUERST ODER DEUTSCHER ZUERST?\"\nDie Schülerzeitung „Echo\" interviewt drei Jugendliche aus Bayern.\n\nEcho: Fühlt ihr euch zuerst als Bayern oder als Deutsche?\n\nMarkus (17, München): Ich sag's ehrlich – ich bin zuerst Bayer. Das ist keine Absage an Deutschland, aber Bayern hat eine eigene Sprache, eigene Traditionen, eigenes Selbstbewusstsein. Wenn ich ins Ausland fahre, sag ich trotzdem, ich komme aus Deutschland. Aber zu Hause bin ich Bayer durch und durch.\n\nAylin (16, Nürnberg): Ich bin in einer türkisch-deutschen Familie groß geworden. Für mich ist das komplizierter. Ich bin Deutsche, Bayerin und gleichzeitig auch ein Teil der türkischen Kultur. Ich finde es schön, mehrere Identitäten zu haben – das macht mich reicher, nicht ärmer.\n\nLukas (17, Rosenheim): Ich denke, das hängt vom Kontext ab. Bei der Fußball-WM bin ich hundertprozentig Deutscher. Beim Oktoberfest bin ich Bayer. Identität ist nicht entweder-oder, sondern ein Mosaikstein, der sich je nach Situation ändert.</pre></div><b>23.</b> Wofür nennt Markus Bayern als Beispiel?", choices:["Bayern hat die höchste Wirtschaftsleistung in Deutschland","Bayern hat eine eigene Sprache, Traditionen und ein starkes Selbstbewusstsein","Bayern ist politisch unabhängig vom Rest Deutschlands","Bayern hat die meisten internationalen Einwanderer"], answer:1},

  {q:"<div class=\"stimulus\"><pre>INTERVIEW: „BAYER ZUERST ODER DEUTSCHER ZUERST?\"\nDie Schülerzeitung „Echo\" interviewt drei Jugendliche aus Bayern.\n\nEcho: Fühlt ihr euch zuerst als Bayern oder als Deutsche?\n\nMarkus (17, München): Ich sag's ehrlich – ich bin zuerst Bayer. Das ist keine Absage an Deutschland, aber Bayern hat eine eigene Sprache, eigene Traditionen, eigenes Selbstbewusstsein. Wenn ich ins Ausland fahre, sag ich trotzdem, ich komme aus Deutschland. Aber zu Hause bin ich Bayer durch und durch.\n\nAylin (16, Nürnberg): Ich bin in einer türkisch-deutschen Familie groß geworden. Für mich ist das komplizierter. Ich bin Deutsche, Bayerin und gleichzeitig auch ein Teil der türkischen Kultur. Ich finde es schön, mehrere Identitäten zu haben – das macht mich reicher, nicht ärmer.\n\nLukas (17, Rosenheim): Ich denke, das hängt vom Kontext ab. Bei der Fußball-WM bin ich hundertprozentig Deutscher. Beim Oktoberfest bin ich Bayer. Identität ist nicht entweder-oder, sondern ein Mosaikstein, der sich je nach Situation ändert.</pre></div><b>24.</b> Welche Schlussfolgerung über Identität kann man aus dem Interview ziehen?", choices:["Identität ist immer eindeutig und unveränderlich","Regionale Identität ist wichtiger als nationale Identität","Identität kann vielschichtig und situationsabhängig sein","Jugendliche in Deutschland lehnen nationale Identität meistens ab"], answer:2},

  // ── Questions 25–30 ── Kulturartikel: Du/Sie und Dialekte ─────────────────
  {q:"<div class=\"stimulus\"><pre>DU ODER SIE? EIN KULTURELLER WEGWEISER\n\nFür Deutschlernende ist eine der kniffligsten Fragen: Wann sage ich \"Du\", wann sage ich \"Sie\"? Dieses sprachliche Phänomen spiegelt tief verwurzelte gesellschaftliche Normen wider.\n\nDas \"Sie\" ist traditionell das Zeichen von Respekt und Distanz – gegenüber Vorgesetzten, älteren Personen, unbekannten Erwachsenen und in formellen Situationen. Das \"Du\" hingegen steht für Vertrautheit, Nähe und Gleichstellung.\n\nDoch in den letzten Jahrzehnten hat sich die deutsche Gesellschaft gewandelt. Start-up-Kulturen, skandinavischer Einfluss und das allgemeine Duzen in sozialen Medien haben das \"Sie\" zunehmend verdrängt. Unternehmen wie IKEA oder Zalando duzten ihre Kunden schon seit Jahren. Auch viele Universitäten sind dazu übergegangen, Professoren und Studierende einander duzen zu lassen.\n\nDennoch gibt es klare Bereiche, in denen das \"Sie\" weiterhin dominiert: Behörden, Gerichte, traditionelle Unternehmen, Arztpraxen und der öffentliche Verkehr. Wer in diesen Kontexten ungefragt duzt, riskiert, als unhöflich oder unprofessionell zu gelten.\n\nDie Faustregel bleibt: Im Zweifel lieber siezen. Die andere Person kann das Duzen anbieten – und das ist dann ein echtes Zeichen von Sympathie und Vertrauen.</pre></div><b>25.</b> Was signalisiert das \"Sie\" im deutschen Sprachgebrauch traditionell?", choices:["Freundschaft und Vertrautheit","Respekt und formelle Distanz","Gleichgültigkeit oder Ablehnung","Ironie oder Humor in bestimmten Regionen"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DU ODER SIE? EIN KULTURELLER WEGWEISER\n\nFür Deutschlernende ist eine der kniffligsten Fragen: Wann sage ich \"Du\", wann sage ich \"Sie\"? Dieses sprachliche Phänomen spiegelt tief verwurzelte gesellschaftliche Normen wider.\n\nDas \"Sie\" ist traditionell das Zeichen von Respekt und Distanz – gegenüber Vorgesetzten, älteren Personen, unbekannten Erwachsenen und in formellen Situationen. Das \"Du\" hingegen steht für Vertrautheit, Nähe und Gleichstellung.\n\nDoch in den letzten Jahrzehnten hat sich die deutsche Gesellschaft gewandelt. Start-up-Kulturen, skandinavischer Einfluss und das allgemeine Duzen in sozialen Medien haben das \"Sie\" zunehmend verdrängt. Unternehmen wie IKEA oder Zalando duzten ihre Kunden schon seit Jahren. Auch viele Universitäten sind dazu übergegangen, Professoren und Studierende einander duzen zu lassen.\n\nDennoch gibt es klare Bereiche, in denen das \"Sie\" weiterhin dominiert: Behörden, Gerichte, traditionelle Unternehmen, Arztpraxen und der öffentliche Verkehr. Wer in diesen Kontexten ungefragt duzt, riskiert, als unhöflich oder unprofessionell zu gelten.\n\nDie Faustregel bleibt: Im Zweifel lieber siezen. Die andere Person kann das Duzen anbieten – und das ist dann ein echtes Zeichen von Sympathie und Vertrauen.</pre></div><b>26.</b> Welche Faktoren haben laut dem Text das Duzen in Deutschland verbreitet?", choices:["Politische Reformen und neue Schulgesetze","Start-up-Kulturen, skandinavischer Einfluss und soziale Medien","Zunehmende Urbanisierung und Anonymität der Städte","Internationale Einwanderung und Globalisierung"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DU ODER SIE? EIN KULTURELLER WEGWEISER\n\nFür Deutschlernende ist eine der kniffligsten Fragen: Wann sage ich \"Du\", wann sage ich \"Sie\"? Dieses sprachliche Phänomen spiegelt tief verwurzelte gesellschaftliche Normen wider.\n\nDas \"Sie\" ist traditionell das Zeichen von Respekt und Distanz – gegenüber Vorgesetzten, älteren Personen, unbekannten Erwachsenen und in formellen Situationen. Das \"Du\" hingegen steht für Vertrautheit, Nähe und Gleichstellung.\n\nDoch in den letzten Jahrzehnten hat sich die deutsche Gesellschaft gewandelt. Start-up-Kulturen, skandinavischer Einfluss und das allgemeine Duzen in sozialen Medien haben das \"Sie\" zunehmend verdrängt. Unternehmen wie IKEA oder Zalando duzten ihre Kunden schon seit Jahren. Auch viele Universitäten sind dazu übergegangen, Professoren und Studierende einander duzen zu lassen.\n\nDennoch gibt es klare Bereiche, in denen das \"Sie\" weiterhin dominiert: Behörden, Gerichte, traditionelle Unternehmen, Arztpraxen und der öffentliche Verkehr. Wer in diesen Kontexten ungefragt duzt, riskiert, als unhöflich oder unprofessionell zu gelten.\n\nDie Faustregel bleibt: Im Zweifel lieber siezen. Die andere Person kann das Duzen anbieten – und das ist dann ein echtes Zeichen von Sympathie und Vertrauen.</pre></div><b>27.</b> In welchen Bereichen bleibt das \"Sie\" laut dem Text dominant?", choices:["In Schulen und Universitäten","In Behörden, Gerichten und Arztpraxen","In der Mode- und Kreativbranche","In sozialen Medien und Online-Foren"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DU ODER SIE? EIN KULTURELLER WEGWEISER\n\nFür Deutschlernende ist eine der kniffligsten Fragen: Wann sage ich \"Du\", wann sage ich \"Sie\"? Dieses sprachliche Phänomen spiegelt tief verwurzelte gesellschaftliche Normen wider.\n\nDas \"Sie\" ist traditionell das Zeichen von Respekt und Distanz – gegenüber Vorgesetzten, älteren Personen, unbekannten Erwachsenen und in formellen Situationen. Das \"Du\" hingegen steht für Vertrautheit, Nähe und Gleichstellung.\n\nDoch in den letzten Jahrzehnten hat sich die deutsche Gesellschaft gewandelt. Start-up-Kulturen, skandinavischer Einfluss und das allgemeine Duzen in sozialen Medien haben das \"Sie\" zunehmend verdrängt. Unternehmen wie IKEA oder Zalando duzten ihre Kunden schon seit Jahren. Auch viele Universitäten sind dazu übergegangen, Professoren und Studierende einander duzen zu lassen.\n\nDennoch gibt es klare Bereiche, in denen das \"Sie\" weiterhin dominiert: Behörden, Gerichte, traditionelle Unternehmen, Arztpraxen und der öffentliche Verkehr. Wer in diesen Kontexten ungefragt duzt, riskiert, als unhöflich oder unprofessionell zu gelten.\n\nDie Faustregel bleibt: Im Zweifel lieber siezen. Die andere Person kann das Duzen anbieten – und das ist dann ein echtes Zeichen von Sympathie und Vertrauen.</pre></div><b>28.</b> Was bedeutet es laut dem Text, wenn jemand das Duzen anbietet?", choices:["Es ist eine bloße Höflichkeitsfloskel ohne tiefere Bedeutung","Es ist ein echtes Zeichen von Sympathie und Vertrauen","Es bedeutet, dass man gleichaltrig ist","Es zeigt, dass man in einer modernen Stadt wohnt"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DU ODER SIE? EIN KULTURELLER WEGWEISER\n\nFür Deutschlernende ist eine der kniffligsten Fragen: Wann sage ich \"Du\", wann sage ich \"Sie\"? Dieses sprachliche Phänomen spiegelt tief verwurzelte gesellschaftliche Normen wider.\n\nDas \"Sie\" ist traditionell das Zeichen von Respekt und Distanz – gegenüber Vorgesetzten, älteren Personen, unbekannten Erwachsenen und in formellen Situationen. Das \"Du\" hingegen steht für Vertrautheit, Nähe und Gleichstellung.\n\nDoch in den letzten Jahrzehnten hat sich die deutsche Gesellschaft gewandelt. Start-up-Kulturen, skandinavischer Einfluss und das allgemeine Duzen in sozialen Medien haben das \"Sie\" zunehmend verdrängt. Unternehmen wie IKEA oder Zalando duzten ihre Kunden schon seit Jahren. Auch viele Universitäten sind dazu übergegangen, Professoren und Studierende einander duzen zu lassen.\n\nDennoch gibt es klare Bereiche, in denen das \"Sie\" weiterhin dominiert: Behörden, Gerichte, traditionelle Unternehmen, Arztpraxen und der öffentliche Verkehr. Wer in diesen Kontexten ungefragt duzt, riskiert, als unhöflich oder unprofessionell zu gelten.\n\nDie Faustregel bleibt: Im Zweifel lieber siezen. Die andere Person kann das Duzen anbieten – und das ist dann ein echtes Zeichen von Sympathie und Vertrauen.</pre></div><b>29.</b> Welche Faustregel empfiehlt der Artikel?", choices:["Im Zweifel lieber duzen, um modern zu wirken","Im Zweifel lieber siezen und das Duzen der anderen Person überlassen","Immer die gleiche Anrede wie der Gesprächspartner verwenden","Jüngere duzen, Ältere immer siezen"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DU ODER SIE? EIN KULTURELLER WEGWEISER\n\nFür Deutschlernende ist eine der kniffligsten Fragen: Wann sage ich \"Du\", wann sage ich \"Sie\"? Dieses sprachliche Phänomen spiegelt tief verwurzelte gesellschaftliche Normen wider.\n\nDas \"Sie\" ist traditionell das Zeichen von Respekt und Distanz – gegenüber Vorgesetzten, älteren Personen, unbekannten Erwachsenen und in formellen Situationen. Das \"Du\" hingegen steht für Vertrautheit, Nähe und Gleichstellung.\n\nDoch in den letzten Jahrzehnten hat sich die deutsche Gesellschaft gewandelt. Start-up-Kulturen, skandinavischer Einfluss und das allgemeine Duzen in sozialen Medien haben das \"Sie\" zunehmend verdrängt. Unternehmen wie IKEA oder Zalando duzten ihre Kunden schon seit Jahren. Auch viele Universitäten sind dazu übergegangen, Professoren und Studierende einander duzen zu lassen.\n\nDennoch gibt es klare Bereiche, in denen das \"Sie\" weiterhin dominiert: Behörden, Gerichte, traditionelle Unternehmen, Arztpraxen und der öffentliche Verkehr. Wer in diesen Kontexten ungefragt duzt, riskiert, als unhöflich oder unprofessionell zu gelten.\n\nDie Faustregel bleibt: Im Zweifel lieber siezen. Die andere Person kann das Duzen anbieten – und das ist dann ein echtes Zeichen von Sympathie und Vertrauen.</pre></div><b>30.</b> Was macht das Du/Sie-Phänomen laut dem Text besonders interessant?", choices:["Es ist eine rein grammatikalische Erscheinung ohne soziale Bedeutung","Es spiegelt tief verwurzelte gesellschaftliche Normen und Werte wider","Es hat sich in den letzten Jahrzehnten kaum verändert","Es wird nur noch von älteren Generationen beachtet"], answer:1},

  // ── Questions 31–36 ── Statistiktext mit Tabelle: Haushaltsformen ──────────
  {q:"<div class=\"stimulus\"><pre>HAUSHALTSFORMEN IN DEUTSCHLAND – STATISTISCHER ÜBERBLICK (2023)\n\nQuelle: Statistisches Bundesamt, Mikrozensus 2023\n\n<table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.95em\">\n<tr><th>Haushaltsform</th><th>Anteil 2013</th><th>Anteil 2023</th><th>Veränderung</th></tr>\n<tr><td>Einpersonenhaushalt</td><td>38%</td><td>41%</td><td>+3 Pp</td></tr>\n<tr><td>Paar ohne Kinder</td><td>28%</td><td>27%</td><td>-1 Pp</td></tr>\n<tr><td>Paar mit Kindern</td><td>22%</td><td>19%</td><td>-3 Pp</td></tr>\n<tr><td>Alleinerziehend</td><td>8%</td><td>9%</td><td>+1 Pp</td></tr>\n<tr><td>Mehrgenerationenhaushalt</td><td>4%</td><td>4%</td><td>±0 Pp</td></tr>\n</table>\n\nDie Daten zeigen, dass Einpersonenhaushalte in Deutschland weiterhin zunehmen und nun die häufigste Lebensform darstellen. Paare mit Kindern sind dagegen deutlich seltener geworden. Mehrgenerationenhaushalte blieben stabil, verzeichnen aber regional starke Unterschiede: In ländlichen Gebieten Bayerns und Baden-Württembergs liegt ihr Anteil bei bis zu 9 Prozent.</pre></div><b>31.</b> Welche Haushaltsform ist 2023 in Deutschland am häufigsten?", choices:["Paar mit Kindern","Paar ohne Kinder","Einpersonenhaushalt","Mehrgenerationenhaushalt"], answer:2},

  {q:"<div class=\"stimulus\"><pre>HAUSHALTSFORMEN IN DEUTSCHLAND – STATISTISCHER ÜBERBLICK (2023)\n\nQuelle: Statistisches Bundesamt, Mikrozensus 2023\n\n<table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.95em\">\n<tr><th>Haushaltsform</th><th>Anteil 2013</th><th>Anteil 2023</th><th>Veränderung</th></tr>\n<tr><td>Einpersonenhaushalt</td><td>38%</td><td>41%</td><td>+3 Pp</td></tr>\n<tr><td>Paar ohne Kinder</td><td>28%</td><td>27%</td><td>-1 Pp</td></tr>\n<tr><td>Paar mit Kindern</td><td>22%</td><td>19%</td><td>-3 Pp</td></tr>\n<tr><td>Alleinerziehend</td><td>8%</td><td>9%</td><td>+1 Pp</td></tr>\n<tr><td>Mehrgenerationenhaushalt</td><td>4%</td><td>4%</td><td>±0 Pp</td></tr>\n</table>\n\nDie Daten zeigen, dass Einpersonenhaushalte in Deutschland weiterhin zunehmen und nun die häufigste Lebensform darstellen. Paare mit Kindern sind dagegen deutlich seltener geworden. Mehrgenerationenhaushalte blieben stabil, verzeichnen aber regional starke Unterschiede: In ländlichen Gebieten Bayerns und Baden-Württembergs liegt ihr Anteil bei bis zu 9 Prozent.</pre></div><b>32.</b> Welche Haushaltsform hat zwischen 2013 und 2023 den größten Rückgang erfahren?", choices:["Einpersonenhaushalte","Alleinerziehende","Paare ohne Kinder","Paare mit Kindern"], answer:3},

  {q:"<div class=\"stimulus\"><pre>HAUSHALTSFORMEN IN DEUTSCHLAND – STATISTISCHER ÜBERBLICK (2023)\n\nQuelle: Statistisches Bundesamt, Mikrozensus 2023\n\n<table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.95em\">\n<tr><th>Haushaltsform</th><th>Anteil 2013</th><th>Anteil 2023</th><th>Veränderung</th></tr>\n<tr><td>Einpersonenhaushalt</td><td>38%</td><td>41%</td><td>+3 Pp</td></tr>\n<tr><td>Paar ohne Kinder</td><td>28%</td><td>27%</td><td>-1 Pp</td></tr>\n<tr><td>Paar mit Kindern</td><td>22%</td><td>19%</td><td>-3 Pp</td></tr>\n<tr><td>Alleinerziehend</td><td>8%</td><td>9%</td><td>+1 Pp</td></tr>\n<tr><td>Mehrgenerationenhaushalt</td><td>4%</td><td>4%</td><td>±0 Pp</td></tr>\n</table>\n\nDie Daten zeigen, dass Einpersonenhaushalte in Deutschland weiterhin zunehmen und nun die häufigste Lebensform darstellen. Paare mit Kindern sind dagegen deutlich seltener geworden. Mehrgenerationenhaushalte blieben stabil, verzeichnen aber regional starke Unterschiede: In ländlichen Gebieten Bayerns und Baden-Württembergs liegt ihr Anteil bei bis zu 9 Prozent.</pre></div><b>33.</b> Was lässt sich über Mehrgenerationenhaushalte aus der Tabelle schließen?", choices:["Sie haben sich seit 2013 verdoppelt","Ihr Anteil ist bundesweit auf 9 Prozent gestiegen","Ihr prozentualer Anteil ist stabil geblieben, mit regionalen Unterschieden","Sie kommen nur noch in Großstädten vor"], answer:2},

  {q:"<div class=\"stimulus\"><pre>HAUSHALTSFORMEN IN DEUTSCHLAND – STATISTISCHER ÜBERBLICK (2023)\n\nQuelle: Statistisches Bundesamt, Mikrozensus 2023\n\n<table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.95em\">\n<tr><th>Haushaltsform</th><th>Anteil 2013</th><th>Anteil 2023</th><th>Veränderung</th></tr>\n<tr><td>Einpersonenhaushalt</td><td>38%</td><td>41%</td><td>+3 Pp</td></tr>\n<tr><td>Paar ohne Kinder</td><td>28%</td><td>27%</td><td>-1 Pp</td></tr>\n<tr><td>Paar mit Kindern</td><td>22%</td><td>19%</td><td>-3 Pp</td></tr>\n<tr><td>Alleinerziehend</td><td>8%</td><td>9%</td><td>+1 Pp</td></tr>\n<tr><td>Mehrgenerationenhaushalt</td><td>4%</td><td>4%</td><td>±0 Pp</td></tr>\n</table>\n\nDie Daten zeigen, dass Einpersonenhaushalte in Deutschland weiterhin zunehmen und nun die häufigste Lebensform darstellen. Paare mit Kindern sind dagegen deutlich seltener geworden. Mehrgenerationenhaushalte blieben stabil, verzeichnen aber regional starke Unterschiede: In ländlichen Gebieten Bayerns und Baden-Württembergs liegt ihr Anteil bei bis zu 9 Prozent.</pre></div><b>34.</b> Wie hoch war der Anteil von Paaren mit Kindern im Jahr 2023?", choices:["22 Prozent","27 Prozent","19 Prozent","4 Prozent"], answer:2},

  {q:"<div class=\"stimulus\"><pre>HAUSHALTSFORMEN IN DEUTSCHLAND – STATISTISCHER ÜBERBLICK (2023)\n\nQuelle: Statistisches Bundesamt, Mikrozensus 2023\n\n<table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.95em\">\n<tr><th>Haushaltsform</th><th>Anteil 2013</th><th>Anteil 2023</th><th>Veränderung</th></tr>\n<tr><td>Einpersonenhaushalt</td><td>38%</td><td>41%</td><td>+3 Pp</td></tr>\n<tr><td>Paar ohne Kinder</td><td>28%</td><td>27%</td><td>-1 Pp</td></tr>\n<tr><td>Paar mit Kindern</td><td>22%</td><td>19%</td><td>-3 Pp</td></tr>\n<tr><td>Alleinerziehend</td><td>8%</td><td>9%</td><td>+1 Pp</td></tr>\n<tr><td>Mehrgenerationenhaushalt</td><td>4%</td><td>4%</td><td>±0 Pp</td></tr>\n</table>\n\nDie Daten zeigen, dass Einpersonenhaushalte in Deutschland weiterhin zunehmen und nun die häufigste Lebensform darstellen. Paare mit Kindern sind dagegen deutlich seltener geworden. Mehrgenerationenhaushalte blieben stabil, verzeichnen aber regional starke Unterschiede: In ländlichen Gebieten Bayerns und Baden-Württembergs liegt ihr Anteil bei bis zu 9 Prozent.</pre></div><b>35.</b> Wo sind Mehrgenerationenhaushalte laut dem Text besonders verbreitet?", choices:["In Großstädten wie Berlin und Hamburg","In ländlichen Gebieten Bayerns und Baden-Württembergs","In ostdeutschen Bundesländern","In Universitätsstädten mit jungen Bevölkerungen"], answer:1},

  {q:"<div class=\"stimulus\"><pre>HAUSHALTSFORMEN IN DEUTSCHLAND – STATISTISCHER ÜBERBLICK (2023)\n\nQuelle: Statistisches Bundesamt, Mikrozensus 2023\n\n<table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.95em\">\n<tr><th>Haushaltsform</th><th>Anteil 2013</th><th>Anteil 2023</th><th>Veränderung</th></tr>\n<tr><td>Einpersonenhaushalt</td><td>38%</td><td>41%</td><td>+3 Pp</td></tr>\n<tr><td>Paar ohne Kinder</td><td>28%</td><td>27%</td><td>-1 Pp</td></tr>\n<tr><td>Paar mit Kindern</td><td>22%</td><td>19%</td><td>-3 Pp</td></tr>\n<tr><td>Alleinerziehend</td><td>8%</td><td>9%</td><td>+1 Pp</td></tr>\n<tr><td>Mehrgenerationenhaushalt</td><td>4%</td><td>4%</td><td>±0 Pp</td></tr>\n</table>\n\nDie Daten zeigen, dass Einpersonenhaushalte in Deutschland weiterhin zunehmen und nun die häufigste Lebensform darstellen. Paare mit Kindern sind dagegen deutlich seltener geworden. Mehrgenerationenhaushalte blieben stabil, verzeichnen aber regional starke Unterschiede: In ländlichen Gebieten Bayerns und Baden-Württembergs liegt ihr Anteil bei bis zu 9 Prozent.</pre></div><b>36.</b> Welche Schlussfolgerung lassen die Daten insgesamt zu?", choices:["Die traditionelle Kernfamilie gewinnt in Deutschland an Bedeutung","Die Gesellschaft wird individualistischer und Kleinfamilien nehmen ab","Mehrgenerationenhaushalte werden bald die dominierende Wohnform","Alleinerziehende sind die am schnellsten wachsende Gruppe"], answer:1},

  // ── Questions 37–45 ── Cloze-Aufgaben (3 Passagen × 3 Fragen) ──────────────

  // Passage A: Elternzeit in Deutschland
  {q:"<div class=\"stimulus\"><pre>Text A: Elternzeit in Deutschland\n\nIn Deutschland haben Eltern das Recht, nach der Geburt eines Kindes bis zu drei Jahre Elternzeit zu ________. Während dieser Zeit ruht der Arbeitsvertrag, und der Arbeitgeber darf die Beschäftigung nicht kündigen. Das Elterngeld, das der Staat zahlt, ________ bis zu 67 Prozent des bisherigen Nettoeinkommens. Viele Väter ________ inzwischen ebenfalls Elternzeit, was sich positiv auf die Gleichstellung der Geschlechter auswirkt.</pre></div><b>37.</b> Welches Wort passt am besten in die erste Lücke (\"Elternzeit zu ________\")?", choices:["beantragen","nehmen","erhalten","beanspruchen"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Text A: Elternzeit in Deutschland\n\nIn Deutschland haben Eltern das Recht, nach der Geburt eines Kindes bis zu drei Jahre Elternzeit zu nehmen. Während dieser Zeit ruht der Arbeitsvertrag, und der Arbeitgeber darf die Beschäftigung nicht kündigen. Das Elterngeld, das der Staat zahlt, ________ bis zu 67 Prozent des bisherigen Nettoeinkommens. Viele Väter ________ inzwischen ebenfalls Elternzeit, was sich positiv auf die Gleichstellung der Geschlechter auswirkt.</pre></div><b>38.</b> Welches Wort passt am besten in die zweite Lücke (\"zahlt, ________ bis zu 67 Prozent\")?", choices:["erreicht","beträgt","umfasst","entspricht"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Text A: Elternzeit in Deutschland\n\nIn Deutschland haben Eltern das Recht, nach der Geburt eines Kindes bis zu drei Jahre Elternzeit zu nehmen. Während dieser Zeit ruht der Arbeitsvertrag, und der Arbeitgeber darf die Beschäftigung nicht kündigen. Das Elterngeld, das der Staat zahlt, beträgt bis zu 67 Prozent des bisherigen Nettoeinkommens. Viele Väter ________ inzwischen ebenfalls Elternzeit, was sich positiv auf die Gleichstellung der Geschlechter auswirkt.</pre></div><b>39.</b> Welches Wort passt am besten in die dritte Lücke (\"Viele Väter ________\")?", choices:["fordern","genießen","nehmen","verlangen"], answer:2},

  // Passage B: Integration und Sprache
  {q:"<div class=\"stimulus\"><pre>Text B: Integration und Sprache\n\nDie deutsche Sprache ist ein wichtiger ________ für die gesellschaftliche Integration. Wer Deutsch gut spricht, findet leichter Arbeit und kann ________ am sozialen Leben teilnehmen. Die Bundesregierung fördert deshalb Integrationskurse, die Sprache, Kultur und Geschichte Deutschlands ________. Viele Einwanderer berichten, dass das Erlernen der Sprache ihnen geholfen hat, sich in der neuen Heimat willkommen zu fühlen.</pre></div><b>40.</b> Welches Wort passt am besten in die erste Lücke (\"wichtiger ________ für die gesellschaftliche Integration\")?", choices:["Hindernis","Schlüssel","Anlass","Maßstab"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Text B: Integration und Sprache\n\nDie deutsche Sprache ist ein wichtiger Schlüssel für die gesellschaftliche Integration. Wer Deutsch gut spricht, findet leichter Arbeit und kann ________ am sozialen Leben teilnehmen. Die Bundesregierung fördert deshalb Integrationskurse, die Sprache, Kultur und Geschichte Deutschlands ________. Viele Einwanderer berichten, dass das Erlernen der Sprache ihnen geholfen hat, sich in der neuen Heimat willkommen zu fühlen.</pre></div><b>41.</b> Welches Wort passt am besten in die zweite Lücke (\"kann ________ am sozialen Leben teilnehmen\")?", choices:["kaum","aktiv","selten","bedingt"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Text B: Integration und Sprache\n\nDie deutsche Sprache ist ein wichtiger Schlüssel für die gesellschaftliche Integration. Wer Deutsch gut spricht, findet leichter Arbeit und kann aktiv am sozialen Leben teilnehmen. Die Bundesregierung fördert deshalb Integrationskurse, die Sprache, Kultur und Geschichte Deutschlands ________. Viele Einwanderer berichten, dass das Erlernen der Sprache ihnen geholfen hat, sich in der neuen Heimat willkommen zu fühlen.</pre></div><b>42.</b> Welches Wort passt am besten in die dritte Lücke (\"Geschichte Deutschlands ________\")?", choices:["beschreiben","vermitteln","erklären","vorstellen"], answer:1},

  // Passage C: Dialekte und Identität
  {q:"<div class=\"stimulus\"><pre>Text C: Dialekte und Identität\n\nDeutschland ist ein Land der Dialekte: Vom Bayerischen im Süden über das Kölsche am Rhein bis zum Plattdeutschen im Norden – die sprachliche ________ ist enorm. Dialekte sind nicht nur Kommunikationsmittel, sondern auch Träger regionaler Identität und kulturellen ________. Dennoch sehen viele junge Menschen Dialekte als ________ für ihre berufliche Zukunft und passen ihre Sprache im Beruf an das Hochdeutsche an.</pre></div><b>43.</b> Welches Wort passt am besten in die erste Lücke (\"die sprachliche ________\")?", choices:["Vereinheitlichung","Vielfalt","Armut","Schwäche"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Text C: Dialekte und Identität\n\nDeutschland ist ein Land der Dialekte: Vom Bayerischen im Süden über das Kölsche am Rhein bis zum Plattdeutschen im Norden – die sprachliche Vielfalt ist enorm. Dialekte sind nicht nur Kommunikationsmittel, sondern auch Träger regionaler Identität und kulturellen ________. Dennoch sehen viele junge Menschen Dialekte als ________ für ihre berufliche Zukunft und passen ihre Sprache im Beruf an das Hochdeutsche an.</pre></div><b>44.</b> Welches Wort passt am besten in die zweite Lücke (\"kulturellen ________\")?", choices:["Vergessens","Erbes","Verlustes","Wandels"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Text C: Dialekte und Identität\n\nDeutschland ist ein Land der Dialekte: Vom Bayerischen im Süden über das Kölsche am Rhein bis zum Plattdeutschen im Norden – die sprachliche Vielfalt ist enorm. Dialekte sind nicht nur Kommunikationsmittel, sondern auch Träger regionaler Identität und kulturellen Erbes. Dennoch sehen viele junge Menschen Dialekte als ________ für ihre berufliche Zukunft und passen ihre Sprache im Beruf an das Hochdeutsche an.</pre></div><b>45.</b> Welches Wort passt am besten in die dritte Lücke (\"Dialekte als ________ für ihre berufliche Zukunft\")?", choices:["Vorteil","Nachteil","Grundlage","Voraussetzung"], answer:1}

];

const GERMAN_SET1_FRQ = [
  {
    "title": "Task 1: Interpersonal Writing — E-Mail-Antwort (2023, 5 Punkte · 15 min)",
    "text": "<strong>📅 OFFICIAL AP German 2023 Exam (College Board)</strong><p><em>The full exam prompt is copyrighted by College Board. This app links to the official PDF — open it and then respond below.</em></p><p><strong>📄 Offizieller Prompt:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap23-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2023 FRQ PDF — Task 1 (Seite 1–2)</a></p><p><strong>📋 Offizielle Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap23-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">Scoring Guidelines PDF</a></p><hr><p><strong>Your task:</strong></p><ul><li>⏱ <strong>15 Minuten</strong>. Lesen Sie die E-Mail im offiziellen PDF.</li><li>✍️ Antworten Sie auf <strong>Deutsch</strong> in formellem Register (<strong>Sie-Form</strong>).</li><li>📌 Beantworten Sie <strong>alle</strong> gestellten Fragen und Anliegen.</li><li>📏 Ca. 150–200 Wörter.</li><li>🎯 Fügen Sie Begrüßung (Sehr geehrte/r …) und Schlussformel (Mit freundlichen Grüßen) ein.</li></ul><p><strong>Schreiben Sie Ihre Antwort unten:</strong></p>",
    "maxPoints": 5,
    "rubric": [
      {
        "part": "Score 5 (Strong)",
        "desc": "Fully addresses all task elements. Appropriate register and tone. Rich vocabulary, varied structures. Minor errors do not impede communication.",
        "pts": 1
      },
      {
        "part": "Score 4 (Good)",
        "desc": "Addresses most task elements well. Generally appropriate register. Good variety in vocabulary and structures. Some errors.",
        "pts": 1
      },
      {
        "part": "Score 3 (Fair)",
        "desc": "Addresses task at a basic level. Register mostly appropriate. Basic vocabulary and structures. Errors may occasionally impede.",
        "pts": 1
      },
      {
        "part": "Score 2 (Weak)",
        "desc": "Partial response. Inconsistent register. Limited vocabulary. Errors frequently impede communication.",
        "pts": 1
      },
      {
        "part": "Score 1 (Poor)",
        "desc": "Minimal response. Inappropriate register or tone. Very limited vocabulary. Errors severely impede communication.",
        "pts": 1
      },
    ]
  },
  {
    "title": "Task 2: Presentational Writing — Argumentativer Aufsatz (2023, 6 Punkte · 55 min)",
    "text": "<strong>📅 OFFICIAL AP German 2023 Exam (College Board)</strong><p><em>Full prompt and sources are copyrighted. Open the official PDF for the essay question, print sources, and chart. Listen to the audio source below.</em></p><p><strong>📄 Offizieller Prompt + Quellen 1 &amp; 2:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap23-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2023 FRQ PDF — Task 2</a></p><p><strong>🎧 Quelle 3 (Audio) — wird zweimal gespielt:</strong><br><audio controls preload=\"none\" style=\"width:100%;max-width:480px\"><source src=\"https://secure-media.collegeboard.org/apc/ap23-german-task-2-argumentative-essay.mp3\" type=\"audio/mpeg\">Ihr Browser unterstützt kein Audio.</audio></p><p><strong>📋 Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap23-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">SG PDF</a></p><hr><p><strong>Your task:</strong></p><ul><li>⏱ <strong>55 Minuten</strong> insgesamt: 6 min Quellen lesen/hören + 40 min schreiben (Audio ~4 min, 2×).</li><li>✍️ Schreiben Sie einen <strong>argumentativen Aufsatz</strong> zur Thesefrage im PDF.</li><li>📚 Integrieren Sie <strong>alle drei Quellen</strong> (Artikel, Grafik/Tabelle, Audio) und zitieren Sie sie (z.B. „Laut Quelle 1 …\").</li><li>🎯 Klare Position + Gegenargumente + Schlussfolgerung.</li><li>📏 Ca. 300–400 Wörter.</li></ul><p><strong>Schreiben Sie Ihren Aufsatz unten:</strong></p>",
    "maxPoints": 6,
    "rubric": [
      {
        "part": "Task Completion",
        "desc": "Response clearly takes a position and thoroughly addresses the prompt's essay question.",
        "pts": 1
      },
      {
        "part": "Source Integration",
        "desc": "Integrates and synthesizes information from ALL 3 sources (print article, visual/chart, audio). Cites sources appropriately.",
        "pts": 1
      },
      {
        "part": "Organization",
        "desc": "Clear thesis; logical paragraph structure; effective use of cohesive devices (außerdem, jedoch, dennoch, etc.).",
        "pts": 1
      },
      {
        "part": "Language Use",
        "desc": "Rich vocabulary and varied grammatical structures appropriate to argumentative essay register.",
        "pts": 1
      },
      {
        "part": "Cultural / Content Knowledge",
        "desc": "Draws on relevant knowledge of German-speaking cultures; examples and analysis are accurate.",
        "pts": 1
      },
      {
        "part": "Grammatical Accuracy",
        "desc": "Errors do not impede communication; accurate use of connectors, verb tenses, and case.",
        "pts": 1
      },
    ]
  },
  {
    "title": "Task 3: Interpersonal Speaking — Gespräch (2023, 5 Punkte · ~5 min)",
    "text": "<strong>🗣️ SPEAKING TASK — nicht automatisch bewertet. Nehmen Sie sich selbst auf.</strong><p><em>This is a spoken task. The app provides the official audio and prompt link; use the notes area for your outline or transcription.</em></p><p><strong>📄 Gesprächsrahmen (Prompt + Outline):</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap23-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2023 FRQ PDF — Task 3</a></p><p><strong>🔗 Speaking Prompts Page:</strong> <a href=\"https://apcentral.collegeboard.org/courses/ap-german-language-and-culture/exam/speaking-prompts-2023\" target=\"_blank\" rel=\"noopener\">AP Central — Speaking Prompts 2023</a></p><p><strong>🎧 Offizielles Audio (5 Wechsel, je 20 Sek. Antwort):</strong><br><audio controls preload=\"none\" style=\"width:100%;max-width:480px\"><source src=\"https://secure-media.collegeboard.org/apc/ap23-german-task-3-conversation.mp3\" type=\"audio/mpeg\">Ihr Browser unterstützt kein Audio.</audio></p><p><strong>📋 Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap23-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">SG PDF</a></p><hr><p><strong>Ablauf:</strong></p><ol><li>Lesen Sie im PDF das Rollenspiel-Szenario und den Gesprächsplan (Outline).</li><li>Starten Sie das Audio. Sie hören 5 Äußerungen des Gesprächspartners.</li><li>Nach jeder Äußerung <strong>20 Sekunden</strong> für Ihre Antwort auf Deutsch.</li><li>Sprechen Sie natürlich, verwenden Sie passendes Register (Du/Sie laut Szenario).</li></ol><p><strong>Notizen / Transkription (optional — nicht bewertet):</strong></p>",
    "maxPoints": 5,
    "rubric": [
      {
        "part": "Score 5 (Strong)",
        "desc": "Fully accomplishes task. Clear pronunciation, appropriate register, rich vocabulary, varied structures. Fluent delivery.",
        "pts": 1
      },
      {
        "part": "Score 4 (Good)",
        "desc": "Accomplishes task well. Mostly clear pronunciation, appropriate register, good vocabulary. Mostly fluent.",
        "pts": 1
      },
      {
        "part": "Score 3 (Fair)",
        "desc": "Basic accomplishment of task. Occasionally unclear pronunciation. Basic vocabulary. Some hesitation.",
        "pts": 1
      },
      {
        "part": "Score 2 (Weak)",
        "desc": "Partial accomplishment. Unclear pronunciation at times. Limited vocabulary. Frequent hesitation.",
        "pts": 1
      },
      {
        "part": "Score 1 (Poor)",
        "desc": "Minimal accomplishment. Pronunciation impedes comprehension. Very limited vocabulary. Severely halting.",
        "pts": 1
      },
    ]
  },
  {
    "title": "Task 4: Presentational Speaking — Kulturvergleich (2023, 5 Punkte · 2 min)",
    "text": "<strong>🗣️ SPEAKING TASK — nicht automatisch bewertet.</strong><p><em>This is a 2-minute oral presentation comparing a cultural aspect of your own community with the German-speaking world.</em></p><p><strong>📄 Offizieller Prompt:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap23-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2023 FRQ PDF — Task 4</a></p><p><strong>🔗 Speaking Prompts Page:</strong> <a href=\"https://apcentral.collegeboard.org/courses/ap-german-language-and-culture/exam/speaking-prompts-2023\" target=\"_blank\" rel=\"noopener\">AP Central — Speaking Prompts 2023</a></p><p><strong>🎧 Offizielles Audio (Prompt + Direktiven):</strong><br><audio controls preload=\"none\" style=\"width:100%;max-width:480px\"><source src=\"https://secure-media.collegeboard.org/apc/ap23-german-task-4-cultural-comparison.mp3\" type=\"audio/mpeg\">Ihr Browser unterstützt kein Audio.</audio></p><p><strong>📋 Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap23-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">SG PDF</a></p><hr><p><strong>Ablauf:</strong></p><ol><li>⏱ <strong>4 Minuten</strong> Vorbereitung + <strong>2 Minuten</strong> Präsentation.</li><li>Vergleichen Sie ein kulturelles Thema (im PDF) zwischen <strong>Ihrer eigenen Gemeinschaft</strong> (USA/Korea/etc.) und <strong>dem deutschsprachigen Raum</strong> (D/A/CH).</li><li>🎯 Struktur: Einleitung → Kulturaspekt A → Kulturaspekt B → Ähnlichkeiten/Unterschiede → Fazit.</li><li>📚 Nennen Sie konkrete Beispiele aus Ihrem kulturellen Wissen.</li><li>Sprechen Sie 2 Minuten ohne Pause.</li></ol><p><strong>Präsentationsgliederung / Notizen:</strong></p>",
    "maxPoints": 5,
    "rubric": [
      {
        "part": "Score 5 (Strong)",
        "desc": "Fully accomplishes task. Clear pronunciation, appropriate register, rich vocabulary, varied structures. Fluent delivery.",
        "pts": 1
      },
      {
        "part": "Score 4 (Good)",
        "desc": "Accomplishes task well. Mostly clear pronunciation, appropriate register, good vocabulary. Mostly fluent.",
        "pts": 1
      },
      {
        "part": "Score 3 (Fair)",
        "desc": "Basic accomplishment of task. Occasionally unclear pronunciation. Basic vocabulary. Some hesitation.",
        "pts": 1
      },
      {
        "part": "Score 2 (Weak)",
        "desc": "Partial accomplishment. Unclear pronunciation at times. Limited vocabulary. Frequent hesitation.",
        "pts": 1
      },
      {
        "part": "Score 1 (Poor)",
        "desc": "Minimal accomplishment. Pronunciation impedes comprehension. Very limited vocabulary. Severely halting.",
        "pts": 1
      },
    ]
  },
];
void GERMAN_SET1_MC; void GERMAN_SET1_FRQ;
