// AP German Language and Culture — Practice Set 3
// Theme: "Globale Herausforderungen" + "Zeitgenössisches Leben"

const GERMAN_SET3_MC = [

  // ── Questions 1–6: Public service announcement / Klimaschutz-Kampagne ──

  {q:"<div class=\"stimulus\"><pre>GEMEINSAM FÜR EIN KLIMANEUTRALES DEUTSCHLAND\n\nDie Bundesregierung ruft alle Bürgerinnen und Bürger auf,\naktiv zum Klimaschutz beizutragen.\n\nWas können SIE tun?\n  • Steigen Sie auf öffentliche Verkehrsmittel oder das Fahrrad um.\n  • Reduzieren Sie Ihren Fleischkonsum — schon ein fleischfreier Tag\n    pro Woche spart bis zu 600 kg CO₂ pro Jahr.\n  • Dämmen Sie Ihr Zuhause und nutzen Sie erneuerbare Energien.\n  • Kaufen Sie regional und saisonal ein.\n\nDeutschland hat sich verpflichtet, bis 2045 klimaneutral zu werden.\nJeder Beitrag zählt — für uns und für künftige Generationen.\n\nMehr Informationen: www.klimaschutz.de\nBundesministerium für Wirtschaft und Klimaschutz</pre></div><b>1.</b> Was ist das Hauptziel dieser Kampagne?", choices:["Den Bürgerinnen und Bürgern Steuervorteile für Klimaschutz zu erklären","Die Bevölkerung zu klimafreundlichem Verhalten zu motivieren","Für eine neue Bundesministeriumswebseite zu werben","Die Leistungen der Bundesregierung beim Klimaschutz darzustellen"], answer:1},

  {q:"<div class=\"stimulus\"><pre>GEMEINSAM FÜR EIN KLIMANEUTRALES DEUTSCHLAND\n\nDie Bundesregierung ruft alle Bürgerinnen und Bürger auf,\naktiv zum Klimaschutz beizutragen.\n\nWas können SIE tun?\n  • Steigen Sie auf öffentliche Verkehrsmittel oder das Fahrrad um.\n  • Reduzieren Sie Ihren Fleischkonsum — schon ein fleischfreier Tag\n    pro Woche spart bis zu 600 kg CO₂ pro Jahr.\n  • Dämmen Sie Ihr Zuhause und nutzen Sie erneuerbare Energien.\n  • Kaufen Sie regional und saisonal ein.\n\nDeutschland hat sich verpflichtet, bis 2045 klimaneutral zu werden.\nJeder Beitrag zählt — für uns und für künftige Generationen.\n\nMehr Informationen: www.klimaschutz.de\nBundesministerium für Wirtschaft und Klimaschutz</pre></div><b>2.</b> Welche Einsparung wird laut dem Text durch einen fleischfreien Tag pro Woche erreicht?", choices:["Bis zu 200 kg CO₂ jährlich","Bis zu 400 kg CO₂ jährlich","Bis zu 600 kg CO₂ jährlich","Bis zu 1000 kg CO₂ jährlich"], answer:2},

  {q:"<div class=\"stimulus\"><pre>GEMEINSAM FÜR EIN KLIMANEUTRALES DEUTSCHLAND\n\nDie Bundesregierung ruft alle Bürgerinnen und Bürger auf,\naktiv zum Klimaschutz beizutragen.\n\nWas können SIE tun?\n  • Steigen Sie auf öffentliche Verkehrsmittel oder das Fahrrad um.\n  • Reduzieren Sie Ihren Fleischkonsum — schon ein fleischfreier Tag\n    pro Woche spart bis zu 600 kg CO₂ pro Jahr.\n  • Dämmen Sie Ihr Zuhause und nutzen Sie erneuerbare Energien.\n  • Kaufen Sie regional und saisonal ein.\n\nDeutschland hat sich verpflichtet, bis 2045 klimaneutral zu werden.\nJeder Beitrag zählt — für uns und für künftige Generationen.\n\nMehr Informationen: www.klimaschutz.de\nBundesministerium für Wirtschaft und Klimaschutz</pre></div><b>3.</b> Bis wann hat sich Deutschland laut dieser Ankündigung verpflichtet, klimaneutral zu werden?", choices:["Bis 2030","Bis 2035","Bis 2040","Bis 2045"], answer:3},

  {q:"<div class=\"stimulus\"><pre>GEMEINSAM FÜR EIN KLIMANEUTRALES DEUTSCHLAND\n\nDie Bundesregierung ruft alle Bürgerinnen und Bürger auf,\naktiv zum Klimaschutz beizutragen.\n\nWas können SIE tun?\n  • Steigen Sie auf öffentliche Verkehrsmittel oder das Fahrrad um.\n  • Reduzieren Sie Ihren Fleischkonsum — schon ein fleischfreier Tag\n    pro Woche spart bis zu 600 kg CO₂ pro Jahr.\n  • Dämmen Sie Ihr Zuhause und nutzen Sie erneuerbare Energien.\n  • Kaufen Sie regional und saisonal ein.\n\nDeutschland hat sich verpflichtet, bis 2045 klimaneutral zu werden.\nJeder Beitrag zählt — für uns und für künftige Generationen.\n\nMehr Informationen: www.klimaschutz.de\nBundesministerium für Wirtschaft und Klimaschutz</pre></div><b>4.</b> Welche der folgenden Empfehlungen wird in der Kampagne NICHT erwähnt?", choices:["Den öffentlichen Nahverkehr nutzen","Erneuerbare Energien verwenden","Auf Fernreisen verzichten","Regional einkaufen"], answer:2},

  {q:"<div class=\"stimulus\"><pre>GEMEINSAM FÜR EIN KLIMANEUTRALES DEUTSCHLAND\n\nDie Bundesregierung ruft alle Bürgerinnen und Bürger auf,\naktiv zum Klimaschutz beizutragen.\n\nWas können SIE tun?\n  • Steigen Sie auf öffentliche Verkehrsmittel oder das Fahrrad um.\n  • Reduzieren Sie Ihren Fleischkonsum — schon ein fleischfreier Tag\n    pro Woche spart bis zu 600 kg CO₂ pro Jahr.\n  • Dämmen Sie Ihr Zuhause und nutzen Sie erneuerbare Energien.\n  • Kaufen Sie regional und saisonal ein.\n\nDeutschland hat sich verpflichtet, bis 2045 klimaneutral zu werden.\nJeder Beitrag zählt — für uns und für künftige Generationen.\n\nMehr Informationen: www.klimaschutz.de\nBundesministerium für Wirtschaft und Klimaschutz</pre></div><b>5.</b> An welche Zielgruppe richtet sich diese Kampagne hauptsächlich?", choices:["Nur an Unternehmen und Industrie","An alle Bürgerinnen und Bürger","Ausschließlich an junge Menschen","An politische Entscheidungsträger"], answer:1},

  {q:"<div class=\"stimulus\"><pre>GEMEINSAM FÜR EIN KLIMANEUTRALES DEUTSCHLAND\n\nDie Bundesregierung ruft alle Bürgerinnen und Bürger auf,\naktiv zum Klimaschutz beizutragen.\n\nWas können SIE tun?\n  • Steigen Sie auf öffentliche Verkehrsmittel oder das Fahrrad um.\n  • Reduzieren Sie Ihren Fleischkonsum — schon ein fleischfreier Tag\n    pro Woche spart bis zu 600 kg CO₂ pro Jahr.\n  • Dämmen Sie Ihr Zuhause und nutzen Sie erneuerbare Energien.\n  • Kaufen Sie regional und saisonal ein.\n\nDeutschland hat sich verpflichtet, bis 2045 klimaneutral zu werden.\nJeder Beitrag zählt — für uns und für künftige Generationen.\n\nMehr Informationen: www.klimaschutz.de\nBundesministerium für Wirtschaft und Klimaschutz</pre></div><b>6.</b> Welchen Ton verwendet diese Kampagne, um ihr Publikum anzusprechen?", choices:["Drohend und warnend","Sachlich und wissenschaftlich","Ermutigend und gemeinschaftsorientiert","Kritisch gegenüber der Regierungspolitik"], answer:2},

  // ── Questions 7–12: E-Mail von einer NGO / Austauschorganisation ──

  {q:"<div class=\"stimulus\"><pre>Von: info@jugend-weltweit.de\nAn: teilnehmer@schule-beispiel.de\nBetreff: Einladung zum Internationalen Jugendforum \"Zukunft gestalten\" 2025\n\nSehr geehrte Damen und Herren,\n\nim Namen der Organisation Jugend Weltweit e.V. freuen wir uns,\nSie herzlich zu unserem diesjährigen Internationalen Jugendforum\n\"Zukunft gestalten\" einzuladen, das vom 15. bis 22. Juli 2025\nin Berlin stattfinden wird.\n\nDas Forum bringt 200 Jugendliche aus 40 Ländern zusammen, die\nsich gemeinsam mit den drängendsten globalen Herausforderungen\nunserer Zeit auseinandersetzen: Klimawandel, soziale Gerechtigkeit,\ndigitale Transformation und nachhaltige Entwicklung.\n\nDie Teilnahme umfasst:\n  – Workshops mit internationalen Expertinnen und Experten\n  – Projektarbeit in interkulturellen Teams\n  – Besuch von Bundestagsabgeordneten und EU-Delegierten\n  – Kulturelles Rahmenprogramm\n\nDie Teilnahmegebühr beträgt 150 Euro und beinhaltet Unterkunft\nund Verpflegung. Reisekosten werden auf Antrag bezuschusst.\n\nBewerbungsschluss: 1. Mai 2025\nBewerbungsformular und weitere Informationen finden Sie\nauf unserer Website: www.jugend-weltweit.de/forum2025\n\nWir freuen uns auf Ihre Bewerbung!\n\nMit freundlichen Grüßen\nDr. Anna Bergmann\nProgrammleiterin, Jugend Weltweit e.V.</pre></div><b>7.</b> Was ist der Hauptzweck dieser E-Mail?", choices:["Jugendliche zu einer Spende für eine NGO zu bitten","Schülerinnen und Schüler zu einem internationalen Jugendforum einzuladen","Über die Ergebnisse eines vergangenen Forums zu berichten","Für ein Austauschjahr in Berlin zu werben"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Von: info@jugend-weltweit.de\nAn: teilnehmer@schule-beispiel.de\nBetreff: Einladung zum Internationalen Jugendforum \"Zukunft gestalten\" 2025\n\nSehr geehrte Damen und Herren,\n\nim Namen der Organisation Jugend Weltweit e.V. freuen wir uns,\nSie herzlich zu unserem diesjährigen Internationalen Jugendforum\n\"Zukunft gestalten\" einzuladen, das vom 15. bis 22. Juli 2025\nin Berlin stattfinden wird.\n\nDas Forum bringt 200 Jugendliche aus 40 Ländern zusammen, die\nsich gemeinsam mit den drängendsten globalen Herausforderungen\nunserer Zeit auseinandersetzen: Klimawandel, soziale Gerechtigkeit,\ndigitale Transformation und nachhaltige Entwicklung.\n\nDie Teilnahme umfasst:\n  – Workshops mit internationalen Expertinnen und Experten\n  – Projektarbeit in interkulturellen Teams\n  – Besuch von Bundestagsabgeordneten und EU-Delegierten\n  – Kulturelles Rahmenprogramm\n\nDie Teilnahmegebühr beträgt 150 Euro und beinhaltet Unterkunft\nund Verpflegung. Reisekosten werden auf Antrag bezuschusst.\n\nBewerbungsschluss: 1. Mai 2025\nBewerbungsformular und weitere Informationen finden Sie\nauf unserer Website: www.jugend-weltweit.de/forum2025\n\nWir freuen uns auf Ihre Bewerbung!\n\nMit freundlichen Grüßen\nDr. Anna Bergmann\nProgrammleiterin, Jugend Weltweit e.V.</pre></div><b>8.</b> Wie viele Teilnehmer aus wie vielen Ländern werden zu dem Forum erwartet?", choices:["100 Teilnehmer aus 20 Ländern","200 Teilnehmer aus 40 Ländern","300 Teilnehmer aus 50 Ländern","150 Teilnehmer aus 30 Ländern"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Von: info@jugend-weltweit.de\nAn: teilnehmer@schule-beispiel.de\nBetreff: Einladung zum Internationalen Jugendforum \"Zukunft gestalten\" 2025\n\nSehr geehrte Damen und Herren,\n\nim Namen der Organisation Jugend Weltweit e.V. freuen wir uns,\nSie herzlich zu unserem diesjährigen Internationalen Jugendforum\n\"Zukunft gestalten\" einzuladen, das vom 15. bis 22. Juli 2025\nin Berlin stattfinden wird.\n\nDas Forum bringt 200 Jugendliche aus 40 Ländern zusammen, die\nsich gemeinsam mit den drängendsten globalen Herausforderungen\nunserer Zeit auseinandersetzen: Klimawandel, soziale Gerechtigkeit,\ndigitale Transformation und nachhaltige Entwicklung.\n\nDie Teilnahme umfasst:\n  – Workshops mit internationalen Expertinnen und Experten\n  – Projektarbeit in interkulturellen Teams\n  – Besuch von Bundestagsabgeordneten und EU-Delegierten\n  – Kulturelles Rahmenprogramm\n\nDie Teilnahmegebühr beträgt 150 Euro und beinhaltet Unterkunft\nund Verpflegung. Reisekosten werden auf Antrag bezuschusst.\n\nWir freuen uns auf Ihre Bewerbung!\n\nMit freundlichen Grüßen\nDr. Anna Bergmann\nProgrammleiterin, Jugend Weltweit e.V.</pre></div><b>9.</b> Was ist in der Teilnahmegebühr von 150 Euro enthalten?", choices:["Nur die Unterkunft, ohne Verpflegung","Unterkunft und Verpflegung, jedoch keine Reisekosten","Unterkunft, Verpflegung und Reisekosten","Nur die Verpflegung, ohne Unterkunft"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Von: info@jugend-weltweit.de\nAn: teilnehmer@schule-beispiel.de\nBetreff: Einladung zum Internationalen Jugendforum \"Zukunft gestalten\" 2025\n\nSehr geehrte Damen und Herren,\n\nim Namen der Organisation Jugend Weltweit e.V. freuen wir uns,\nSie herzlich zu unserem diesjährigen Internationalen Jugendforum\n\"Zukunft gestalten\" einzuladen, das vom 15. bis 22. Juli 2025\nin Berlin stattfinden wird.\n\nDas Forum bringt 200 Jugendliche aus 40 Ländern zusammen, die\nsich gemeinsam mit den drängendsten globalen Herausforderungen\nunserer Zeit auseinandersetzen: Klimawandel, soziale Gerechtigkeit,\ndigitale Transformation und nachhaltige Entwicklung.\n\nDie Teilnahme umfasst:\n  – Workshops mit internationalen Expertinnen und Experten\n  – Projektarbeit in interkulturellen Teams\n  – Besuch von Bundestagsabgeordneten und EU-Delegierten\n  – Kulturelles Rahmenprogramm\n\nDie Teilnahmegebühr beträgt 150 Euro und beinhaltet Unterkunft\nund Verpflegung. Reisekosten werden auf Antrag bezuschusst.\n\nBewerbungsschluss: 1. Mai 2025\n\nMit freundlichen Grüßen\nDr. Anna Bergmann\nProgrammleiterin, Jugend Weltweit e.V.</pre></div><b>10.</b> Bis wann müssen sich Interessierte bewerben?", choices:["1. April 2025","15. Mai 2025","1. Mai 2025","22. Juli 2025"], answer:2},

  {q:"<div class=\"stimulus\"><pre>Von: info@jugend-weltweit.de\nAn: teilnehmer@schule-beispiel.de\nBetreff: Einladung zum Internationalen Jugendforum \"Zukunft gestalten\" 2025\n\nDas Forum bringt 200 Jugendliche aus 40 Ländern zusammen, die\nsich gemeinsam mit den drängendsten globalen Herausforderungen\nunserer Zeit auseinandersetzen: Klimawandel, soziale Gerechtigkeit,\ndigitale Transformation und nachhaltige Entwicklung.\n\nDie Teilnahme umfasst:\n  – Workshops mit internationalen Expertinnen und Experten\n  – Projektarbeit in interkulturellen Teams\n  – Besuch von Bundestagsabgeordneten und EU-Delegierten\n  – Kulturelles Rahmenprogramm\n\nMit freundlichen Grüßen\nDr. Anna Bergmann\nProgrammleiterin, Jugend Weltweit e.V.</pre></div><b>11.</b> Welches der folgenden Themen wird beim Forum laut E-Mail NICHT behandelt?", choices:["Klimawandel","Soziale Gerechtigkeit","Internationale Sportwettbewerbe","Digitale Transformation"], answer:2},

  {q:"<div class=\"stimulus\"><pre>Von: info@jugend-weltweit.de\nAn: teilnehmer@schule-beispiel.de\nBetreff: Einladung zum Internationalen Jugendforum \"Zukunft gestalten\" 2025\n\nDie Teilnahme umfasst:\n  – Workshops mit internationalen Expertinnen und Experten\n  – Projektarbeit in interkulturellen Teams\n  – Besuch von Bundestagsabgeordneten und EU-Delegierten\n  – Kulturelles Rahmenprogramm\n\nMit freundlichen Grüßen\nDr. Anna Bergmann\nProgrammleiterin, Jugend Weltweit e.V.</pre></div><b>12.</b> Was bedeutet der Satz \"Reisekosten werden auf Antrag bezuschusst\"?", choices:["Die Reisekosten sind automatisch im Preis inbegriffen","Man kann einen Antrag stellen, um einen Zuschuss zu den Reisekosten zu erhalten","Die Reisekosten werden vollständig von der Organisation übernommen","Teilnehmer müssen ihre Reisekosten selbst tragen, ohne Ausnahme"], answer:1},

  // ── Questions 13–18: Zeitungsartikel über Klimawandel / Flüchtlinge ──

  {q:"<div class=\"stimulus\"><pre>KLIMAWANDEL TREIBT MILLIONEN IN DIE FLUCHT\n\nFrankfurter Allgemeine Zeitung | 12. März 2025\n\nDer Klimawandel gilt längst nicht mehr nur als ökologisches\nProblem — er ist zu einem der stärksten Treiber menschlicher\nMigration geworden. Nach Angaben des Welternährungsprogramms\n(WFP) sind bis 2050 bis zu 216 Millionen Menschen weltweit\nzur Binnenmigration gezwungen, wenn keine wirksamen\nKlimamaßnahmen ergriffen werden.\n\nBesonders betroffen sind Regionen in Subsahara-Afrika,\nSüdasien und Lateinamerika. Dort führen Dürren, Überschwemmungen\nund der Anstieg des Meeresspiegels dazu, dass Ackerland\nunbewirtschaftbar wird und ganze Küstenstädte verschwinden.\n\n\"Wir sehen heute schon, was Klimamigration bedeutet\",\nsagt Dr. Lena Hoffmann vom Deutschen Institut für\nEntwicklungspolitik. \"Familien verlassen ihre Heimat\nnicht aus freiem Willen, sondern weil Überleben anderswo\nmöglich ist — und zu Hause nicht mehr.\"\n\nDie internationale Gemeinschaft streitet derweil über\nRechtsstatus und Aufnahmepflichten für Klimaflüchtlinge.\nEin verbindliches internationales Abkommen existiert\nbis heute nicht. Nichtregierungsorganisationen fordern\ndringend eine Reform des Genfer Flüchtlingsabkommens,\num auch klimabedingte Vertreibung zu erfassen.\n\nDeutschland diskutiert vor dem Hintergrund der Bundestagswahl\n2025 intensiv über seine Migrationspolitik und die Frage,\nwelche Verantwortung reiche Industrienationen gegenüber\nKlimaflüchtlingen tragen.</pre></div><b>13.</b> Was ist das Hauptthema dieses Zeitungsartikels?", choices:["Die wirtschaftlichen Folgen des Klimawandels für Europa","Der Zusammenhang zwischen Klimawandel und menschlicher Migration","Die Ergebnisse der Bundestagswahl 2025","Deutschlands neue Asylgesetzgebung"], answer:1},

  {q:"<div class=\"stimulus\"><pre>KLIMAWANDEL TREIBT MILLIONEN IN DIE FLUCHT\n\nFrankfurter Allgemeine Zeitung | 12. März 2025\n\nNach Angaben des Welternährungsprogramms (WFP) sind bis 2050\nbis zu 216 Millionen Menschen weltweit zur Binnenmigration\ngezwungen, wenn keine wirksamen Klimamaßnahmen ergriffen werden.\n\nBesonders betroffen sind Regionen in Subsahara-Afrika,\nSüdasien und Lateinamerika.\n\nDr. Lena Hoffmann vom Deutschen Institut für Entwicklungspolitik\nsagt: \"Familien verlassen ihre Heimat nicht aus freiem Willen,\nsondern weil Überleben anderswo möglich ist — und zu Hause nicht mehr.\"\n\nNichtregierungsorganisationen fordern dringend eine Reform des\nGenfer Flüchtlingsabkommens, um auch klimabedingte Vertreibung\nzu erfassen.</pre></div><b>14.</b> Wie viele Menschen könnten laut WFP bis 2050 zur Binnenmigration gezwungen werden?", choices:["Bis zu 100 Millionen","Bis zu 150 Millionen","Bis zu 216 Millionen","Bis zu 300 Millionen"], answer:2},

  {q:"<div class=\"stimulus\"><pre>KLIMAWANDEL TREIBT MILLIONEN IN DIE FLUCHT\n\nFrankfurter Allgemeine Zeitung | 12. März 2025\n\nBesonders betroffen sind Regionen in Subsahara-Afrika,\nSüdasien und Lateinamerika. Dort führen Dürren, Überschwemmungen\nund der Anstieg des Meeresspiegels dazu, dass Ackerland\nunbewirtschaftbar wird und ganze Küstenstädte verschwinden.\n\n\"Familien verlassen ihre Heimat nicht aus freiem Willen,\nsondern weil Überleben anderswo möglich ist — und zu Hause nicht mehr.\"\n— Dr. Lena Hoffmann, Deutsches Institut für Entwicklungspolitik\n\nNichtregierungsorganisationen fordern eine Reform des\nGenfer Flüchtlingsabkommens.</pre></div><b>15.</b> Welche Naturkatastrophen werden im Artikel als Ursachen für Klimamigration genannt?", choices:["Erdbeben, Vulkanausbrüche und Tsunamis","Dürren, Überschwemmungen und Anstieg des Meeresspiegels","Waldbrände, Schneestürme und Tornados","Taifune, Sandstürme und Frostperioden"], answer:1},

  {q:"<div class=\"stimulus\"><pre>KLIMAWANDEL TREIBT MILLIONEN IN DIE FLUCHT\n\nFrankfurter Allgemeine Zeitung | 12. März 2025\n\n\"Wir sehen heute schon, was Klimamigration bedeutet\",\nsagt Dr. Lena Hoffmann vom Deutschen Institut für\nEntwicklungspolitik. \"Familien verlassen ihre Heimat\nnicht aus freiem Willen, sondern weil Überleben anderswo\nmöglich ist — und zu Hause nicht mehr.\"\n\nNichtregierungsorganisationen fordern dringend eine Reform\ndes Genfer Flüchtlingsabkommens, um auch klimabedingte\nVertreibung zu erfassen.</pre></div><b>16.</b> Was fordert Dr. Lena Hoffmanns Aussage implizit?", choices:["Strengere Grenzkontrollen in Europa","Mehr Verständnis für die Lage von Klimaflüchtlingen","Wirtschaftliche Sanktionen gegen CO₂-Großverursacher","Eine Reduzierung der Entwicklungshilfe"], answer:1},

  {q:"<div class=\"stimulus\"><pre>KLIMAWANDEL TREIBT MILLIONEN IN DIE FLUCHT\n\nFrankfurter Allgemeine Zeitung | 12. März 2025\n\nDie internationale Gemeinschaft streitet derweil über\nRechtsstatus und Aufnahmepflichten für Klimaflüchtlinge.\nEin verbindliches internationales Abkommen existiert\nbis heute nicht. Nichtregierungsorganisationen fordern\ndringend eine Reform des Genfer Flüchtlingsabkommens,\num auch klimabedingte Vertreibung zu erfassen.</pre></div><b>17.</b> Warum fordern NGOs eine Reform des Genfer Flüchtlingsabkommens?", choices:["Weil das Abkommen zu viele Länder ausschließt","Weil klimabedingte Vertreibung darin bisher nicht erfasst wird","Weil das Abkommen finanzielle Unterstützung für Klimaprojekte verhindert","Weil das Abkommen nur für Kriege innerhalb Europas gilt"], answer:1},

  {q:"<div class=\"stimulus\"><pre>KLIMAWANDEL TREIBT MILLIONEN IN DIE FLUCHT\n\nFrankfurter Allgemeine Zeitung | 12. März 2025\n\nDeutschland diskutiert vor dem Hintergrund der Bundestagswahl\n2025 intensiv über seine Migrationspolitik und die Frage,\nwelche Verantwortung reiche Industrienationen gegenüber\nKlimaflüchtlingen tragen.</pre></div><b>18.</b> Was sagt der letzte Absatz über Deutschlands aktuelle Situation aus?", choices:["Deutschland hat bereits ein neues Klimaflüchtlingsgesetz verabschiedet","Migrationspolitik ist kein wichtiges Thema bei der Bundestagswahl","Deutschland diskutiert intensiv, welche Verantwortung Industrienationen gegenüber Klimaflüchtlingen haben","Deutschland plant, keine weiteren Flüchtlinge aufzunehmen"], answer:2},

  // ── Questions 19–24: Interview mit einer Aktivistin / Jugendlichen ──

  {q:"<div class=\"stimulus\"><pre>\"POLITIK FÄNGT BEI UNS AN\"\nInterview mit Klimaaktivistin Mia Schreiber (19) aus Hamburg\n\nInterviewerin: Mia, du bist seit drei Jahren bei Fridays for Future aktiv.\nWas hat dich dazu bewogen?\n\nMia: Ich habe mit 16 einen Dokumentarfilm über das Abschmelzen der\nArktis gesehen und war schockiert. Mir wurde klar, dass diese Krise\nnicht irgendwann in der Zukunft liegt — sie passiert jetzt. Ich\nkann nicht einfach weggucken.\n\nInterviewerin: Manche Kritiker sagen, Schülerstreiks bringen nichts.\n\nMia: Das stimmt einfach nicht. Unsere Bewegung hat dazu beigetragen,\ndass das Thema Klimaschutz dauerhaft auf der politischen Agenda steht.\nIn Deutschland wurde das Klimaschutzgesetz 2021 nach einem Urteil des\nBundesverfassungsgerichts verschärft — und der öffentliche Druck durch\nBewegungen wie unsere hat dabei eine Rolle gespielt.\n\nInterviewerin: Wie vereinbarst du dein Engagement mit dem Abitur?\n\nMia: Es ist nicht immer leicht. Ich schlafe manchmal wenig und muss\nPrioritäten setzen. Aber ich glaube, dass gesellschaftliches Engagement\nzur Bildung gehört. Ich lerne durch mein Aktivismus genauso viel wie\nim Unterricht — über Rhetorik, Organisieren, internationale Vernetzung.\n\nInterviewerin: Was wünschst du dir von der Politik?\n\nMia: Konkrete Maßnahmen statt leerer Versprechen. Eine Solarpflicht\nfür Neubauten. Den sofortigen Kohleausstieg. Und vor allem: dass\nJugendliche endlich mitentscheiden dürfen — durch ein Wahlrecht\nab 16 Jahren.</pre></div><b>19.</b> Was hat Mia Schreibers Engagement bei Fridays for Future ausgelöst?", choices:["Ein Gespräch mit Greta Thunberg auf einer Konferenz","Ein Dokumentarfilm über das Abschmelzen der Arktis","Ein schlechtes Ergebnis beim Klimagipfel in Paris","Ein Schulprojekt über erneuerbare Energien"], answer:0},

  {q:"<div class=\"stimulus\"><pre>\"POLITIK FÄNGT BEI UNS AN\"\nInterview mit Klimaaktivistin Mia Schreiber (19) aus Hamburg\n\nInterviewerin: Manche Kritiker sagen, Schülerstreiks bringen nichts.\n\nMia: Das stimmt einfach nicht. Unsere Bewegung hat dazu beigetragen,\ndass das Thema Klimaschutz dauerhaft auf der politischen Agenda steht.\nIn Deutschland wurde das Klimaschutzgesetz 2021 nach einem Urteil des\nBundesverfassungsgerichts verschärft — und der öffentliche Druck durch\nBewegungen wie unsere hat dabei eine Rolle gespielt.</pre></div><b>20.</b> Welches konkrete politische Ergebnis nennt Mia als Beweis für die Wirkung ihres Engagements?", choices:["Die Einführung des Deutschlandtickets","Die Verschärfung des Klimaschutzgesetzes 2021","Den Beschluss zum Kohleausstieg bis 2030","Die Einführung des Wahlrechts ab 16 Jahren"], answer:1},

  {q:"<div class=\"stimulus\"><pre>\"POLITIK FÄNGT BEI UNS AN\"\nInterview mit Klimaaktivistin Mia Schreiber (19) aus Hamburg\n\nInterviewerin: Wie vereinbarst du dein Engagement mit dem Abitur?\n\nMia: Es ist nicht immer leicht. Ich schlafe manchmal wenig und muss\nPrioritäten setzen. Aber ich glaube, dass gesellschaftliches Engagement\nzur Bildung gehört. Ich lerne durch meinen Aktivismus genauso viel wie\nim Unterricht — über Rhetorik, Organisieren, internationale Vernetzung.</pre></div><b>21.</b> Wie beschreibt Mia die Verbindung zwischen Aktivismus und Bildung?", choices:["Aktivismus schadet der schulischen Leistung dauerhaft","Aktivismus und Bildung schließen sich gegenseitig aus","Sie lernt durch den Aktivismus ebenso viel wie im Unterricht","Bildung ist wichtiger als politisches Engagement"], answer:2},

  {q:"<div class=\"stimulus\"><pre>\"POLITIK FÄNGT BEI UNS AN\"\nInterview mit Klimaaktivistin Mia Schreiber (19) aus Hamburg\n\nMia: Konkrete Maßnahmen statt leerer Versprechen. Eine Solarpflicht\nfür Neubauten. Den sofortigen Kohleausstieg. Und vor allem: dass\nJugendliche endlich mitentscheiden dürfen — durch ein Wahlrecht\nab 16 Jahren.</pre></div><b>22.</b> Was ist Mias wichtigste politische Forderung, die sie \"vor allem\" nennt?", choices:["Sofortiger Kohleausstieg","Solarpflicht für Neubauten","Wahlrecht ab 16 Jahren","Mehr Klimaschutzgesetze auf EU-Ebene"], answer:2},

  {q:"<div class=\"stimulus\"><pre>\"POLITIK FÄNGT BEI UNS AN\"\nInterview mit Klimaaktivistin Mia Schreiber (19) aus Hamburg\n\nMia: Ich habe mit 16 einen Dokumentarfilm über das Abschmelzen der\nArktis gesehen und war schockiert. Mir wurde klar, dass diese Krise\nnicht irgendwann in der Zukunft liegt — sie passiert jetzt. Ich\nkann nicht einfach weggucken.\n\nMia: Es ist nicht immer leicht. Ich schlafe manchmal wenig und muss\nPrioritäten setzen.</pre></div><b>23.</b> Welche Herausforderung nennt Mia beim Vereinbaren von Schule und Aktivismus?", choices:["Sie muss oft auf Reisen verzichten","Sie hat Schwierigkeiten mit ihren Lehrern","Sie schläft manchmal wenig und muss Prioritäten setzen","Ihre Eltern unterstützen ihr Engagement nicht"], answer:2},

  {q:"<div class=\"stimulus\"><pre>\"POLITIK FÄNGT BEI UNS AN\"\nInterview mit Klimaaktivistin Mia Schreiber (19) aus Hamburg\n\nMia: Ich kann nicht einfach weggucken.\n\nMia: Unsere Bewegung hat dazu beigetragen, dass das Thema Klimaschutz\ndauerhaft auf der politischen Agenda steht.\n\nMia: Ich lerne durch meinen Aktivismus genauso viel wie im Unterricht\n— über Rhetorik, Organisieren, internationale Vernetzung.</pre></div><b>24.</b> Welches Wort beschreibt Mias allgemeine Haltung gegenüber ihrem Engagement am besten?", choices:["Resigniert","Überzeugt und engagiert","Zögernd und unsicher","Gleichgültig gegenüber politischen Veränderungen"], answer:1},

  // ── Questions 25–30: Artikel über zeitgenössisches Leben in Deutschland ──

  {q:"<div class=\"stimulus\"><pre>WORK-LIFE-BALANCE IN DEUTSCHLAND: ZWISCHEN ANSPRUCH UND WIRKLICHKEIT\n\nDer Spiegel | 5. Februar 2025\n\nDie Deutschen gelten international als fleißige Arbeitnehmer —\ndoch das Bild wandelt sich. Immer mehr Beschäftigte, vor allem\nder Generation Z, stellen die Frage: Wozu arbeite ich, wenn ich\nkein erfülltes Leben außerhalb des Büros führen kann?\n\nLaut einer aktuellen Studie des Instituts der deutschen Wirtschaft\n(IW) arbeiteten Vollzeitbeschäftigte in Deutschland 2024 im Schnitt\n40,3 Stunden pro Woche — einer der niedrigsten Werte in der EU.\nGleichzeitig gaben 67 Prozent der Befragten an, sich \"häufig\" oder\n\"manchmal\" ausgebrannt zu fühlen.\n\nDer Trend zum Homeoffice, der durch die Corona-Pandemie beschleunigt\nwurde, hat die Grenzen zwischen Arbeit und Freizeit für viele\nunschärfer gemacht. \"Ich bin zwar zu Hause, aber bin ich wirklich\nfrei?\", fragt Lukas Werner (32), Marketing-Manager aus Köln.\n\"Das Laptop liegt immer griffbereit.\"\n\nEhrenamt und Gemeinschaftsprojekte erleben dagegen einen Aufschwung:\n31 Prozent der Deutschen engagieren sich laut Bundesfamilienministerium\nfreiwillig — Tendenz steigend. Viele suchen in der Freizeitgestaltung\nSinn und Gemeinschaft, die der Beruf nicht mehr bieten kann.\n\nExperten empfehlen klare digitale Grenzen: feste Offline-Zeiten,\nUrlaub ohne E-Mail-Zugang und das bewusste Pflegen sozialer Kontakte\naußerhalb der Arbeit.</pre></div><b>25.</b> Was ist das Hauptthema dieses Artikels?", choices:["Deutschlands schlechte Wirtschaftslage im Jahr 2025","Die Herausforderungen der Work-Life-Balance in Deutschland","Die Einführung einer Vier-Tage-Woche in deutschen Unternehmen","Den Anstieg der Arbeitslosigkeit durch Homeoffice"], answer:1},

  {q:"<div class=\"stimulus\"><pre>WORK-LIFE-BALANCE IN DEUTSCHLAND: ZWISCHEN ANSPRUCH UND WIRKLICHKEIT\n\nLaut einer aktuellen Studie des Instituts der deutschen Wirtschaft\n(IW) arbeiteten Vollzeitbeschäftigte in Deutschland 2024 im Schnitt\n40,3 Stunden pro Woche — einer der niedrigsten Werte in der EU.\nGleichzeitig gaben 67 Prozent der Befragten an, sich \"häufig\" oder\n\"manchmal\" ausgebrannt zu fühlen.</pre></div><b>26.</b> Welchen Widerspruch zeigt die IW-Studie auf?", choices:["Deutsche arbeiten viel, verdienen aber weniger als EU-Nachbarn","Deutschland hat viele Arbeitsstunden, aber hohe Produktivität","Obwohl die Arbeitsstunden relativ niedrig sind, fühlen sich viele Beschäftigte ausgebrannt","Die Deutschen arbeiten mehr als der EU-Durchschnitt, ohne Ausgleich"], answer:2},

  {q:"<div class=\"stimulus\"><pre>WORK-LIFE-BALANCE IN DEUTSCHLAND: ZWISCHEN ANSPRUCH UND WIRKLICHKEIT\n\nDer Trend zum Homeoffice, der durch die Corona-Pandemie beschleunigt\nwurde, hat die Grenzen zwischen Arbeit und Freizeit für viele\nunschärfer gemacht. \"Ich bin zwar zu Hause, aber bin ich wirklich\nfrei?\", fragt Lukas Werner (32), Marketing-Manager aus Köln.\n\"Das Laptop liegt immer griffbereit.\"</pre></div><b>27.</b> Was kritisiert Lukas Werner mit seiner Aussage?", choices:["Die schlechte Internetverbindung im Homeoffice","Den Mangel an Rückzugsmöglichkeiten in kleinen Wohnungen","Dass die Grenze zwischen Arbeitszeit und Freizeit im Homeoffice verschwimmt","Die höheren Kosten durch Heizung und Strom im Homeoffice"], answer:2},

  {q:"<div class=\"stimulus\"><pre>WORK-LIFE-BALANCE IN DEUTSCHLAND: ZWISCHEN ANSPRUCH UND WIRKLICHKEIT\n\nEhrenamt und Gemeinschaftsprojekte erleben dagegen einen Aufschwung:\n31 Prozent der Deutschen engagieren sich laut Bundesfamilienministerium\nfreiwillig — Tendenz steigend. Viele suchen in der Freizeitgestaltung\nSinn und Gemeinschaft, die der Beruf nicht mehr bieten kann.</pre></div><b>28.</b> Warum engagieren sich laut Artikel viele Deutsche ehrenamtlich?", choices:["Weil sie gesetzlich dazu verpflichtet sind","Weil sie Sinn und Gemeinschaft suchen, die der Beruf nicht bietet","Weil Ehrenamt die beste Vorbereitung auf den Arbeitsmarkt ist","Weil das Ehrenamt gut bezahlt wird"], answer:1},

  {q:"<div class=\"stimulus\"><pre>WORK-LIFE-BALANCE IN DEUTSCHLAND: ZWISCHEN ANSPRUCH UND WIRKLICHKEIT\n\nExperten empfehlen klare digitale Grenzen: feste Offline-Zeiten,\nUrlaub ohne E-Mail-Zugang und das bewusste Pflegen sozialer Kontakte\naußerhalb der Arbeit.</pre></div><b>29.</b> Welche Empfehlung geben Experten laut Artikel für eine bessere Work-Life-Balance?", choices:["Mehr Überstunden, um Projekte schneller abzuschließen","Feste Offline-Zeiten und Urlaub ohne E-Mail-Zugang","Den Wechsel zu einem weniger anspruchsvollen Beruf","Die komplette Ablehnung von Homeoffice-Arbeit"], answer:1},

  {q:"<div class=\"stimulus\"><pre>WORK-LIFE-BALANCE IN DEUTSCHLAND: ZWISCHEN ANSPRUCH UND WIRKLICHKEIT\n\nImmer mehr Beschäftigte, vor allem der Generation Z, stellen\ndie Frage: Wozu arbeite ich, wenn ich kein erfülltes Leben\naußerhalb des Büros führen kann?\n\n31 Prozent der Deutschen engagieren sich laut Bundesfamilienministerium\nfreiwillig — Tendenz steigend.</pre></div><b>30.</b> Welche Generation stellt laut Artikel besonders die Frage nach dem Sinn der Arbeit?", choices:["Die Babyboomer","Generation X","Generation Z","Die Millennials"], answer:2},

  // ── Questions 31–36: Tabelle / Umfrageergebnisse zu Nachhaltigkeit ──

  {q:"<div class=\"stimulus\"><table style=\"border-collapse:collapse;width:100%;font-size:0.9em\"><caption style=\"font-weight:bold;margin-bottom:6px\">Umfrage: Nachhaltige Verhaltensweisen in Deutschland 2024<br><small>(Befragte: 2.000 Personen ab 18 Jahren; Angaben in Prozent)</small></caption><thead><tr style=\"background:#d0e8d0\"><th style=\"border:1px solid #999;padding:4px 8px\">Verhalten</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich regelmäßig</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich gelegentlich</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich nie</th></tr></thead><tbody><tr><td style=\"border:1px solid #999;padding:4px 8px\">Mülltrennung</td><td style=\"border:1px solid #999;padding:4px 8px\">88%</td><td style=\"border:1px solid #999;padding:4px 8px\">9%</td><td style=\"border:1px solid #999;padding:4px 8px\">3%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Regionales Einkaufen</td><td style=\"border:1px solid #999;padding:4px 8px\">41%</td><td style=\"border:1px solid #999;padding:4px 8px\">38%</td><td style=\"border:1px solid #999;padding:4px 8px\">21%</td></tr><tr><td style=\"border:1px solid #999;padding:4px 8px\">Öffentlicher Nahverkehr</td><td style=\"border:1px solid #999;padding:4px 8px\">55%</td><td style=\"border:1px solid #999;padding:4px 8px\">28%</td><td style=\"border:1px solid #999;padding:4px 8px\">17%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Fleischreduzierung</td><td style=\"border:1px solid #999;padding:4px 8px\">29%</td><td style=\"border:1px solid #999;padding:4px 8px\">33%</td><td style=\"border:1px solid #999;padding:4px 8px\">38%</td></tr><tr><td style=\"border:1px solid #999;padding:4px 8px\">Second-Hand-Kleidung</td><td style=\"border:1px solid #999;padding:4px 8px\">22%</td><td style=\"border:1px solid #999;padding:4px 8px\">41%</td><td style=\"border:1px solid #999;padding:4px 8px\">37%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Solar-/Ökostrom zu Hause</td><td style=\"border:1px solid #999;padding:4px 8px\">34%</td><td style=\"border:1px solid #999;padding:4px 8px\">12%</td><td style=\"border:1px solid #999;padding:4px 8px\">54%</td></tr></tbody></table></div><b>31.</b> Welches nachhaltige Verhalten wird laut der Umfrage am häufigsten \"regelmäßig\" praktiziert?", choices:["Regionales Einkaufen","Öffentlicher Nahverkehr","Mülltrennung","Fleischreduzierung"], answer:2},

  {q:"<div class=\"stimulus\"><table style=\"border-collapse:collapse;width:100%;font-size:0.9em\"><caption style=\"font-weight:bold;margin-bottom:6px\">Umfrage: Nachhaltige Verhaltensweisen in Deutschland 2024</caption><thead><tr style=\"background:#d0e8d0\"><th style=\"border:1px solid #999;padding:4px 8px\">Verhalten</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich regelmäßig</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich gelegentlich</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich nie</th></tr></thead><tbody><tr><td style=\"border:1px solid #999;padding:4px 8px\">Mülltrennung</td><td style=\"border:1px solid #999;padding:4px 8px\">88%</td><td style=\"border:1px solid #999;padding:4px 8px\">9%</td><td style=\"border:1px solid #999;padding:4px 8px\">3%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Regionales Einkaufen</td><td style=\"border:1px solid #999;padding:4px 8px\">41%</td><td style=\"border:1px solid #999;padding:4px 8px\">38%</td><td style=\"border:1px solid #999;padding:4px 8px\">21%</td></tr><tr><td style=\"border:1px solid #999;padding:4px 8px\">Öffentlicher Nahverkehr</td><td style=\"border:1px solid #999;padding:4px 8px\">55%</td><td style=\"border:1px solid #999;padding:4px 8px\">28%</td><td style=\"border:1px solid #999;padding:4px 8px\">17%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Fleischreduzierung</td><td style=\"border:1px solid #999;padding:4px 8px\">29%</td><td style=\"border:1px solid #999;padding:4px 8px\">33%</td><td style=\"border:1px solid #999;padding:4px 8px\">38%</td></tr><tr><td style=\"border:1px solid #999;padding:4px 8px\">Second-Hand-Kleidung</td><td style=\"border:1px solid #999;padding:4px 8px\">22%</td><td style=\"border:1px solid #999;padding:4px 8px\">41%</td><td style=\"border:1px solid #999;padding:4px 8px\">37%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Solar-/Ökostrom zu Hause</td><td style=\"border:1px solid #999;padding:4px 8px\">34%</td><td style=\"border:1px solid #999;padding:4px 8px\">12%</td><td style=\"border:1px solid #999;padding:4px 8px\">54%</td></tr></tbody></table></div><b>32.</b> Bei welchem Verhalten ist der Anteil der Antwort \"Tue ich nie\" am höchsten?", choices:["Regionales Einkaufen","Fleischreduzierung","Second-Hand-Kleidung","Solar-/Ökostrom zu Hause"], answer:3},

  {q:"<div class=\"stimulus\"><table style=\"border-collapse:collapse;width:100%;font-size:0.9em\"><caption style=\"font-weight:bold;margin-bottom:6px\">Umfrage: Nachhaltige Verhaltensweisen in Deutschland 2024</caption><thead><tr style=\"background:#d0e8d0\"><th style=\"border:1px solid #999;padding:4px 8px\">Verhalten</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich regelmäßig</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich gelegentlich</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich nie</th></tr></thead><tbody><tr><td style=\"border:1px solid #999;padding:4px 8px\">Mülltrennung</td><td style=\"border:1px solid #999;padding:4px 8px\">88%</td><td style=\"border:1px solid #999;padding:4px 8px\">9%</td><td style=\"border:1px solid #999;padding:4px 8px\">3%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Regionales Einkaufen</td><td style=\"border:1px solid #999;padding:4px 8px\">41%</td><td style=\"border:1px solid #999;padding:4px 8px\">38%</td><td style=\"border:1px solid #999;padding:4px 8px\">21%</td></tr><tr><td style=\"border:1px solid #999;padding:4px 8px\">Öffentlicher Nahverkehr</td><td style=\"border:1px solid #999;padding:4px 8px\">55%</td><td style=\"border:1px solid #999;padding:4px 8px\">28%</td><td style=\"border:1px solid #999;padding:4px 8px\">17%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Fleischreduzierung</td><td style=\"border:1px solid #999;padding:4px 8px\">29%</td><td style=\"border:1px solid #999;padding:4px 8px\">33%</td><td style=\"border:1px solid #999;padding:4px 8px\">38%</td></tr><tr><td style=\"border:1px solid #999;padding:4px 8px\">Second-Hand-Kleidung</td><td style=\"border:1px solid #999;padding:4px 8px\">22%</td><td style=\"border:1px solid #999;padding:4px 8px\">41%</td><td style=\"border:1px solid #999;padding:4px 8px\">37%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Solar-/Ökostrom zu Hause</td><td style=\"border:1px solid #999;padding:4px 8px\">34%</td><td style=\"border:1px solid #999;padding:4px 8px\">12%</td><td style=\"border:1px solid #999;padding:4px 8px\">54%</td></tr></tbody></table></div><b>33.</b> Welches nachhaltige Verhalten wird am häufigsten \"gelegentlich\" praktiziert (zusammen mit einem anderen auf gleichem Niveau)?", choices:["Öffentlicher Nahverkehr und Fleischreduzierung","Regionales Einkaufen und Second-Hand-Kleidung (je 38-41%)","Mülltrennung und Solar-/Ökostrom","Fleischreduzierung und Solar-/Ökostrom"], answer:1},

  {q:"<div class=\"stimulus\"><table style=\"border-collapse:collapse;width:100%;font-size:0.9em\"><caption style=\"font-weight:bold;margin-bottom:6px\">Umfrage: Nachhaltige Verhaltensweisen in Deutschland 2024</caption><thead><tr style=\"background:#d0e8d0\"><th style=\"border:1px solid #999;padding:4px 8px\">Verhalten</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich regelmäßig</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich gelegentlich</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich nie</th></tr></thead><tbody><tr><td style=\"border:1px solid #999;padding:4px 8px\">Mülltrennung</td><td style=\"border:1px solid #999;padding:4px 8px\">88%</td><td style=\"border:1px solid #999;padding:4px 8px\">9%</td><td style=\"border:1px solid #999;padding:4px 8px\">3%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Regionales Einkaufen</td><td style=\"border:1px solid #999;padding:4px 8px\">41%</td><td style=\"border:1px solid #999;padding:4px 8px\">38%</td><td style=\"border:1px solid #999;padding:4px 8px\">21%</td></tr><tr><td style=\"border:1px solid #999;padding:4px 8px\">Öffentlicher Nahverkehr</td><td style=\"border:1px solid #999;padding:4px 8px\">55%</td><td style=\"border:1px solid #999;padding:4px 8px\">28%</td><td style=\"border:1px solid #999;padding:4px 8px\">17%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Fleischreduzierung</td><td style=\"border:1px solid #999;padding:4px 8px\">29%</td><td style=\"border:1px solid #999;padding:4px 8px\">33%</td><td style=\"border:1px solid #999;padding:4px 8px\">38%</td></tr><tr><td style=\"border:1px solid #999;padding:4px 8px\">Second-Hand-Kleidung</td><td style=\"border:1px solid #999;padding:4px 8px\">22%</td><td style=\"border:1px solid #999;padding:4px 8px\">41%</td><td style=\"border:1px solid #999;padding:4px 8px\">37%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Solar-/Ökostrom zu Hause</td><td style=\"border:1px solid #999;padding:4px 8px\">34%</td><td style=\"border:1px solid #999;padding:4px 8px\">12%</td><td style=\"border:1px solid #999;padding:4px 8px\">54%</td></tr></tbody></table></div><b>34.</b> Was lässt sich aus der Tabelle über die Fleischreduzierung schlussfolgern?", choices:["Die Mehrheit der Deutschen reduziert ihren Fleischkonsum regelmäßig","Die Einstellung zur Fleischreduzierung ist in der Bevölkerung sehr gespalten","Fast alle Deutschen essen niemals Fleisch","Fleischreduzierung ist das beliebteste nachhaltige Verhalten"], answer:1},

  {q:"<div class=\"stimulus\"><table style=\"border-collapse:collapse;width:100%;font-size:0.9em\"><caption style=\"font-weight:bold;margin-bottom:6px\">Umfrage: Nachhaltige Verhaltensweisen in Deutschland 2024</caption><thead><tr style=\"background:#d0e8d0\"><th style=\"border:1px solid #999;padding:4px 8px\">Verhalten</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich regelmäßig</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich gelegentlich</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich nie</th></tr></thead><tbody><tr><td style=\"border:1px solid #999;padding:4px 8px\">Mülltrennung</td><td style=\"border:1px solid #999;padding:4px 8px\">88%</td><td style=\"border:1px solid #999;padding:4px 8px\">9%</td><td style=\"border:1px solid #999;padding:4px 8px\">3%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Öffentlicher Nahverkehr</td><td style=\"border:1px solid #999;padding:4px 8px\">55%</td><td style=\"border:1px solid #999;padding:4px 8px\">28%</td><td style=\"border:1px solid #999;padding:4px 8px\">17%</td></tr></tbody></table></div><b>35.</b> Welche zwei Verhaltensweisen haben zusammen den höchsten kombinierten Anteil von \"Tue ich regelmäßig\" + \"Tue ich gelegentlich\"?", choices:["Fleischreduzierung und Second-Hand-Kleidung","Mülltrennung und Öffentlicher Nahverkehr","Solar-/Ökostrom und Regionales Einkaufen","Mülltrennung und Second-Hand-Kleidung"], answer:1},

  {q:"<div class=\"stimulus\"><table style=\"border-collapse:collapse;width:100%;font-size:0.9em\"><caption style=\"font-weight:bold;margin-bottom:6px\">Umfrage: Nachhaltige Verhaltensweisen in Deutschland 2024</caption><thead><tr style=\"background:#d0e8d0\"><th style=\"border:1px solid #999;padding:4px 8px\">Verhalten</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich regelmäßig</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich gelegentlich</th><th style=\"border:1px solid #999;padding:4px 8px\">Tue ich nie</th></tr></thead><tbody><tr><td style=\"border:1px solid #999;padding:4px 8px\">Mülltrennung</td><td style=\"border:1px solid #999;padding:4px 8px\">88%</td><td style=\"border:1px solid #999;padding:4px 8px\">9%</td><td style=\"border:1px solid #999;padding:4px 8px\">3%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Regionales Einkaufen</td><td style=\"border:1px solid #999;padding:4px 8px\">41%</td><td style=\"border:1px solid #999;padding:4px 8px\">38%</td><td style=\"border:1px solid #999;padding:4px 8px\">21%</td></tr><tr><td style=\"border:1px solid #999;padding:4px 8px\">Öffentlicher Nahverkehr</td><td style=\"border:1px solid #999;padding:4px 8px\">55%</td><td style=\"border:1px solid #999;padding:4px 8px\">28%</td><td style=\"border:1px solid #999;padding:4px 8px\">17%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Fleischreduzierung</td><td style=\"border:1px solid #999;padding:4px 8px\">29%</td><td style=\"border:1px solid #999;padding:4px 8px\">33%</td><td style=\"border:1px solid #999;padding:4px 8px\">38%</td></tr><tr><td style=\"border:1px solid #999;padding:4px 8px\">Second-Hand-Kleidung</td><td style=\"border:1px solid #999;padding:4px 8px\">22%</td><td style=\"border:1px solid #999;padding:4px 8px\">41%</td><td style=\"border:1px solid #999;padding:4px 8px\">37%</td></tr><tr style=\"background:#f5f5f5\"><td style=\"border:1px solid #999;padding:4px 8px\">Solar-/Ökostrom zu Hause</td><td style=\"border:1px solid #999;padding:4px 8px\">34%</td><td style=\"border:1px solid #999;padding:4px 8px\">12%</td><td style=\"border:1px solid #999;padding:4px 8px\">54%</td></tr></tbody></table></div><b>36.</b> Welche Schlussfolgerung lässt die Tabelle insgesamt zu?", choices:["Nachhaltige Verhaltensweisen sind in Deutschland kaum verbreitet","Mülltrennung ist die einzige weit verbreitete nachhaltige Praxis","Die Bereitschaft zu nachhaltigem Verhalten variiert stark je nach Bequemlichkeit und Aufwand","Die meisten Deutschen kaufen regelmäßig Second-Hand-Kleidung"], answer:2},

  // ── Questions 37–45: Cloze / Grammatik im Kontext (3 Passagen × 3 Fragen) ──

  // Passage A: Wohnungsnot
  {q:"<div class=\"stimulus\"><pre>Wohnungsnot in deutschen Großstädten\n\nIn Städten wie München, Berlin und Hamburg wird bezahlbarer\nWohnraum immer knapper. Laut einer Studie fehlen in Deutschland\nbis zu 700.000 Wohnungen. Die Mieten sind in den letzten zehn\nJahren in manchen Stadtteilen um mehr als 80 Prozent (1)______.\nViele junge Menschen können sich die Innenstädte nicht mehr\n(2)______, und ziehen in die Randgebiete oder aufs Land.\nPolitiker diskutieren über einen bundesweiten Mietendeckel,\ndoch Experten sind (3)______ über die langfristige Wirksamkeit\nsolcher Maßnahmen geteilter Meinung.</pre></div><b>37.</b> Welches Wort passt am besten in Lücke (1)?", choices:["gefallen","gestiegen","gesenkt","geblieben"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Wohnungsnot in deutschen Großstädten\n\nIn Städten wie München, Berlin und Hamburg wird bezahlbarer\nWohnraum immer knapper. Die Mieten sind in den letzten zehn\nJahren in manchen Stadtteilen um mehr als 80 Prozent gestiegen.\nViele junge Menschen können sich die Innenstädte nicht mehr\n(2)______, und ziehen in die Randgebiete oder aufs Land.\nPolitiker diskutieren über einen bundesweiten Mietendeckel,\ndoch Experten sind (3)______ über die langfristige Wirksamkeit\nsolcher Maßnahmen geteilter Meinung.</pre></div><b>38.</b> Welches Wort passt am besten in Lücke (2)?", choices:["leisten","erlauben","besorgen","kaufen"], answer:0},

  {q:"<div class=\"stimulus\"><pre>Wohnungsnot in deutschen Großstädten\n\nDie Mieten sind gestiegen. Viele junge Menschen können sich\ndie Innenstädte nicht mehr leisten, und ziehen in die Randgebiete\noder aufs Land. Politiker diskutieren über einen bundesweiten\nMietendeckel, doch Experten sind (3)______ über die langfristige\nWirksamkeit solcher Maßnahmen geteilter Meinung.</pre></div><b>39.</b> Welches Wort passt am besten in Lücke (3)?", choices:["jedoch","sich","dennoch","weiterhin"], answer:1},

  // Passage B: Energiewende
  {q:"<div class=\"stimulus\"><pre>Deutschlands Energiewende auf dem Prüfstand\n\nDie Energiewende — Deutschlands Plan, die Stromversorgung\nauf erneuerbare Quellen (4)______ — gilt international als\nambitioniertes Projekt. Wind- und Solarenergie decken\ninzwischen mehr als 50 Prozent des deutschen Strombedarfs.\nAllerdings bleibt die Netzstabilität eine Herausforderung:\nWenn weder Wind noch Sonne ausreichend (5)______ vorhanden\nsind, entstehen Versorgungslücken. Zudem haben die gestiegenen\nStrompreise viele Haushalte finanziell (6)______, was die\ngesellschaftliche Akzeptanz der Energiewende belastet.</pre></div><b>40.</b> Welches Wort passt am besten in Lücke (4)?", choices:["abzuschalten","umzustellen","einzusparen","herzustellen"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Deutschlands Energiewende auf dem Prüfstand\n\nWind- und Solarenergie decken inzwischen mehr als 50 Prozent\ndes deutschen Strombedarfs. Allerdings bleibt die Netzstabilität\neine Herausforderung: Wenn weder Wind noch Sonne ausreichend\n(5)______ vorhanden sind, entstehen Versorgungslücken.\nZudem haben die gestiegenen Strompreise viele Haushalte\nfinanziell (6)______, was die gesellschaftliche Akzeptanz\nder Energiewende belastet.</pre></div><b>41.</b> Welches Wort passt am besten in Lücke (5)?", choices:["parallel","gleichzeitig","wiederholt","nacheinander"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Deutschlands Energiewende auf dem Prüfstand\n\nDie gestiegenen Strompreise haben viele Haushalte finanziell\n(6)______, was die gesellschaftliche Akzeptanz der Energiewende\nbelastet.</pre></div><b>42.</b> Welches Wort passt am besten in Lücke (6)?", choices:["entlastet","gefördert","belastet","vernachlässigt"], answer:2},

  // Passage C: Social Media und Jugend
  {q:"<div class=\"stimulus\"><pre>Social Media und die Jugend in Deutschland\n\nEine aktuelle Studie der Bundeszentrale für politische Bildung\nzeigt, dass 94 Prozent der 14- bis 24-Jährigen täglich\nSocial-Media-Plattformen (7)______. Jugendliche informieren\nsich darüber über Nachrichten, knüpfen Kontakte und\n(8)______ sich kulturell aus. Gleichzeitig warnen\nPsychologen vor den negativen Auswirkungen: Vergleiche\nmit idealisierten Lebensbildern können das Selbstwertgefühl\n(9)______ und zu Angstzuständen führen. Experten empfehlen\neine bewusste Mediennutzung und regelmäßige digitale Pausen.</pre></div><b>43.</b> Welches Wort passt am besten in Lücke (7)?", choices:["lesen","nutzen","besuchen","gestalten"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Social Media und die Jugend in Deutschland\n\nJugendliche informieren sich darüber über Nachrichten, knüpfen\nKontakte und (8)______ sich kulturell aus. Gleichzeitig warnen\nPsychologen vor den negativen Auswirkungen: Vergleiche mit\nidealisierten Lebensbildern können das Selbstwertgefühl\n(9)______ und zu Angstzuständen führen.</pre></div><b>44.</b> Welches Wort passt am besten in Lücke (8)?", choices:["tauschen","beschäftigen","entwickeln","unterhalten"], answer:0},

  {q:"<div class=\"stimulus\"><pre>Social Media und die Jugend in Deutschland\n\nVergleiche mit idealisierten Lebensbildern können das\nSelbstwertgefühl (9)______ und zu Angstzuständen führen.\nExperten empfehlen eine bewusste Mediennutzung und\nregelmäßige digitale Pausen.</pre></div><b>45.</b> Welches Wort passt am besten in Lücke (9)?", choices:["stärken","mindern","ignorieren","prägen"], answer:1}

];

const GERMAN_SET3_FRQ = [
  {
    "title": "Task 1: Interpersonal Writing — E-Mail-Antwort (2025, 5 Punkte · 15 min)",
    "text": "<strong>📅 OFFICIAL AP German 2025 Exam (College Board)</strong><p><em>The full exam prompt is copyrighted by College Board. This app links to the official PDF — open it and then respond below.</em></p><p><strong>📄 Offizieller Prompt:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap25-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2025 FRQ PDF — Task 1 (Seite 1–2)</a></p><p><strong>📋 Offizielle Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap25-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">Scoring Guidelines PDF</a></p><hr><p><strong>Your task:</strong></p><ul><li>⏱ <strong>15 Minuten</strong>. Lesen Sie die E-Mail im offiziellen PDF.</li><li>✍️ Antworten Sie auf <strong>Deutsch</strong> in formellem Register (<strong>Sie-Form</strong>).</li><li>📌 Beantworten Sie <strong>alle</strong> gestellten Fragen und Anliegen.</li><li>📏 Ca. 150–200 Wörter.</li><li>🎯 Fügen Sie Begrüßung (Sehr geehrte/r …) und Schlussformel (Mit freundlichen Grüßen) ein.</li></ul><p><strong>Schreiben Sie Ihre Antwort unten:</strong></p>",
    "maxPoints": 5,
    "rubric": [
      {
        "part": "Score 5 (Strong)",
        "desc": "Fully addresses all task elements. Appropriate register and tone. Rich vocabulary, varied structures. Minor errors do not impede communication.",
        "pts": 1
      },
      {
        "part": "Score 4 (Good)",
        "desc": "Addresses most task elements well. Generally appropriate register. Good variety in vocabulary and structures. Some errors.",
        "pts": 1
      },
      {
        "part": "Score 3 (Fair)",
        "desc": "Addresses task at a basic level. Register mostly appropriate. Basic vocabulary and structures. Errors may occasionally impede.",
        "pts": 1
      },
      {
        "part": "Score 2 (Weak)",
        "desc": "Partial response. Inconsistent register. Limited vocabulary. Errors frequently impede communication.",
        "pts": 1
      },
      {
        "part": "Score 1 (Poor)",
        "desc": "Minimal response. Inappropriate register or tone. Very limited vocabulary. Errors severely impede communication.",
        "pts": 1
      },
    ]
  },
  {
    "title": "Task 2: Presentational Writing — Argumentativer Aufsatz (2025, 6 Punkte · 55 min)",
    "text": "<strong>📅 OFFICIAL AP German 2025 Exam (College Board)</strong><p><em>Full prompt and sources are copyrighted. Open the official PDF for the essay question, print sources, and chart. Listen to the audio source below.</em></p><p><strong>📄 Offizieller Prompt + Quellen 1 &amp; 2:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap25-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2025 FRQ PDF — Task 2</a></p><p><strong>🎧 Quelle 3 (Audio) — wird zweimal gespielt:</strong><br><audio controls preload=\"none\" style=\"width:100%;max-width:480px\"><source src=\"https://secure-media.collegeboard.org/apc/ap25-german-task-2-argumentative-essay.mp3\" type=\"audio/mpeg\">Ihr Browser unterstützt kein Audio.</audio></p><p><strong>📋 Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap25-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">SG PDF</a></p><hr><p><strong>Your task:</strong></p><ul><li>⏱ <strong>55 Minuten</strong> insgesamt: 6 min Quellen lesen/hören + 40 min schreiben (Audio ~4 min, 2×).</li><li>✍️ Schreiben Sie einen <strong>argumentativen Aufsatz</strong> zur Thesefrage im PDF.</li><li>📚 Integrieren Sie <strong>alle drei Quellen</strong> (Artikel, Grafik/Tabelle, Audio) und zitieren Sie sie (z.B. „Laut Quelle 1 …\").</li><li>🎯 Klare Position + Gegenargumente + Schlussfolgerung.</li><li>📏 Ca. 300–400 Wörter.</li></ul><p><strong>Schreiben Sie Ihren Aufsatz unten:</strong></p>",
    "maxPoints": 6,
    "rubric": [
      {
        "part": "Task Completion",
        "desc": "Response clearly takes a position and thoroughly addresses the prompt's essay question.",
        "pts": 1
      },
      {
        "part": "Source Integration",
        "desc": "Integrates and synthesizes information from ALL 3 sources (print article, visual/chart, audio). Cites sources appropriately.",
        "pts": 1
      },
      {
        "part": "Organization",
        "desc": "Clear thesis; logical paragraph structure; effective use of cohesive devices (außerdem, jedoch, dennoch, etc.).",
        "pts": 1
      },
      {
        "part": "Language Use",
        "desc": "Rich vocabulary and varied grammatical structures appropriate to argumentative essay register.",
        "pts": 1
      },
      {
        "part": "Cultural / Content Knowledge",
        "desc": "Draws on relevant knowledge of German-speaking cultures; examples and analysis are accurate.",
        "pts": 1
      },
      {
        "part": "Grammatical Accuracy",
        "desc": "Errors do not impede communication; accurate use of connectors, verb tenses, and case.",
        "pts": 1
      },
    ]
  },
  {
    "title": "Task 3: Interpersonal Speaking — Gespräch (2025, 5 Punkte · ~5 min)",
    "text": "<strong>🗣️ SPEAKING TASK — nicht automatisch bewertet. Nehmen Sie sich selbst auf.</strong><p><em>This is a spoken task. The app provides the official audio and prompt link; use the notes area for your outline or transcription.</em></p><p><strong>📄 Gesprächsrahmen (Prompt + Outline):</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap25-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2025 FRQ PDF — Task 3</a></p><p><strong>🔗 Speaking Prompts Page:</strong> <a href=\"https://apcentral.collegeboard.org/courses/ap-german-language-and-culture/exam/speaking-prompts-2025\" target=\"_blank\" rel=\"noopener\">AP Central — Speaking Prompts 2025</a></p><p><strong>🎧 Offizielles Audio (5 Wechsel, je 20 Sek. Antwort):</strong><br><audio controls preload=\"none\" style=\"width:100%;max-width:480px\"><source src=\"https://secure-media.collegeboard.org/apc/ap25-german-task-3-conversation.mp3\" type=\"audio/mpeg\">Ihr Browser unterstützt kein Audio.</audio></p><p><strong>📋 Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap25-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">SG PDF</a></p><hr><p><strong>Ablauf:</strong></p><ol><li>Lesen Sie im PDF das Rollenspiel-Szenario und den Gesprächsplan (Outline).</li><li>Starten Sie das Audio. Sie hören 5 Äußerungen des Gesprächspartners.</li><li>Nach jeder Äußerung <strong>20 Sekunden</strong> für Ihre Antwort auf Deutsch.</li><li>Sprechen Sie natürlich, verwenden Sie passendes Register (Du/Sie laut Szenario).</li></ol><p><strong>Notizen / Transkription (optional — nicht bewertet):</strong></p>",
    "maxPoints": 5,
    "rubric": [
      {
        "part": "Score 5 (Strong)",
        "desc": "Fully accomplishes task. Clear pronunciation, appropriate register, rich vocabulary, varied structures. Fluent delivery.",
        "pts": 1
      },
      {
        "part": "Score 4 (Good)",
        "desc": "Accomplishes task well. Mostly clear pronunciation, appropriate register, good vocabulary. Mostly fluent.",
        "pts": 1
      },
      {
        "part": "Score 3 (Fair)",
        "desc": "Basic accomplishment of task. Occasionally unclear pronunciation. Basic vocabulary. Some hesitation.",
        "pts": 1
      },
      {
        "part": "Score 2 (Weak)",
        "desc": "Partial accomplishment. Unclear pronunciation at times. Limited vocabulary. Frequent hesitation.",
        "pts": 1
      },
      {
        "part": "Score 1 (Poor)",
        "desc": "Minimal accomplishment. Pronunciation impedes comprehension. Very limited vocabulary. Severely halting.",
        "pts": 1
      },
    ]
  },
  {
    "title": "Task 4: Presentational Speaking — Kulturvergleich (2025, 5 Punkte · 2 min)",
    "text": "<strong>🗣️ SPEAKING TASK — nicht automatisch bewertet.</strong><p><em>This is a 2-minute oral presentation comparing a cultural aspect of your own community with the German-speaking world.</em></p><p><strong>📄 Offizieller Prompt:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap25-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2025 FRQ PDF — Task 4</a></p><p><strong>🔗 Speaking Prompts Page:</strong> <a href=\"https://apcentral.collegeboard.org/courses/ap-german-language-and-culture/exam/speaking-prompts-2025\" target=\"_blank\" rel=\"noopener\">AP Central — Speaking Prompts 2025</a></p><p><strong>🎧 Offizielles Audio (Prompt + Direktiven):</strong><br><audio controls preload=\"none\" style=\"width:100%;max-width:480px\"><source src=\"https://secure-media.collegeboard.org/apc/ap25-german-task-4-cultural-comparison.mp3\" type=\"audio/mpeg\">Ihr Browser unterstützt kein Audio.</audio></p><p><strong>📋 Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap25-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">SG PDF</a></p><hr><p><strong>Ablauf:</strong></p><ol><li>⏱ <strong>4 Minuten</strong> Vorbereitung + <strong>2 Minuten</strong> Präsentation.</li><li>Vergleichen Sie ein kulturelles Thema (im PDF) zwischen <strong>Ihrer eigenen Gemeinschaft</strong> (USA/Korea/etc.) und <strong>dem deutschsprachigen Raum</strong> (D/A/CH).</li><li>🎯 Struktur: Einleitung → Kulturaspekt A → Kulturaspekt B → Ähnlichkeiten/Unterschiede → Fazit.</li><li>📚 Nennen Sie konkrete Beispiele aus Ihrem kulturellen Wissen.</li><li>Sprechen Sie 2 Minuten ohne Pause.</li></ol><p><strong>Präsentationsgliederung / Notizen:</strong></p>",
    "maxPoints": 5,
    "rubric": [
      {
        "part": "Score 5 (Strong)",
        "desc": "Fully accomplishes task. Clear pronunciation, appropriate register, rich vocabulary, varied structures. Fluent delivery.",
        "pts": 1
      },
      {
        "part": "Score 4 (Good)",
        "desc": "Accomplishes task well. Mostly clear pronunciation, appropriate register, good vocabulary. Mostly fluent.",
        "pts": 1
      },
      {
        "part": "Score 3 (Fair)",
        "desc": "Basic accomplishment of task. Occasionally unclear pronunciation. Basic vocabulary. Some hesitation.",
        "pts": 1
      },
      {
        "part": "Score 2 (Weak)",
        "desc": "Partial accomplishment. Unclear pronunciation at times. Limited vocabulary. Frequent hesitation.",
        "pts": 1
      },
      {
        "part": "Score 1 (Poor)",
        "desc": "Minimal accomplishment. Pronunciation impedes comprehension. Very limited vocabulary. Severely halting.",
        "pts": 1
      },
    ]
  },
];
void GERMAN_SET3_MC; void GERMAN_SET3_FRQ;
