const GERMAN_SET2_MC = [

  // ── Questions 1–6: Product description / Technical poster (Neues E-Auto) ──

  {q:"<div class=\"stimulus\"><pre>NOVA ELEKTRO X7 — Das Fahrzeug der Zukunft\n\nReichweite:        620 km (WLTP-Norm)\nLadedauer:         18 Minuten (10 % → 80 %)\nAntrieb:           Dual-Motor, Allradantrieb\nLeistung:          350 kW / 476 PS\nBatteriekapazität: 100 kWh (Lithium-Eisenphosphat)\nFahrassistenz:     Level 3 Autonomes Fahren\nPreis ab:          54 990 € (inkl. MwSt.)\nVerfügbar:         ab März 2026 beim autorisierten Fachhändler\n\nNachhaltigkeitsversprechen: 85 % der Fahrzeugkomponenten sind\nrecyclingfähig. Die Produktion erfolgt CO₂-neutral im Werk Zwickau.</pre></div><b>1.</b> Wie lange dauert es, den Akku des Nova Elektro X7 von 10 % auf 80 % aufzuladen?", choices:["Etwa 45 Minuten","18 Minuten","Eine Stunde","30 Minuten"], answer:1},

  {q:"<div class=\"stimulus\"><pre>NOVA ELEKTRO X7 — Das Fahrzeug der Zukunft\n\nReichweite:        620 km (WLTP-Norm)\nLadedauer:         18 Minuten (10 % → 80 %)\nAntrieb:           Dual-Motor, Allradantrieb\nLeistung:          350 kW / 476 PS\nBatteriekapazität: 100 kWh (Lithium-Eisenphosphat)\nFahrassistenz:     Level 3 Autonomes Fahren\nPreis ab:          54 990 € (inkl. MwSt.)\nVerfügbar:         ab März 2026 beim autorisierten Fachhändler\n\nNachhaltigkeitsversprechen: 85 % der Fahrzeugkomponenten sind\nrecyclingfähig. Die Produktion erfolgt CO₂-neutral im Werk Zwickau.</pre></div><b>2.</b> Welche Aussage über das Nachhaltigkeitsversprechen des Fahrzeugs ist korrekt?", choices:["Das Fahrzeug wird vollständig aus recycelten Materialien hergestellt.","Die gesamte Lieferkette ist CO₂-neutral zertifiziert.","85 % der Komponenten können recycelt werden und die Produktion ist CO₂-neutral.","Das Fahrzeug emittiert während der Fahrt kein CO₂."], answer:2},

  {q:"<div class=\"stimulus\"><pre>NOVA ELEKTRO X7 — Das Fahrzeug der Zukunft\n\nReichweite:        620 km (WLTP-Norm)\nLadedauer:         18 Minuten (10 % → 80 %)\nAntrieb:           Dual-Motor, Allradantrieb\nLeistung:          350 kW / 476 PS\nBatteriekapazität: 100 kWh (Lithium-Eisenphosphat)\nFahrassistenz:     Level 3 Autonomes Fahren\nPreis ab:          54 990 € (inkl. MwSt.)\nVerfügbar:         ab März 2026 beim autorisierten Fachhändler\n\nNachhaltigkeitsversprechen: 85 % der Fahrzeugkomponenten sind\nrecyclingfähig. Die Produktion erfolgt CO₂-neutral im Werk Zwickau.</pre></div><b>3.</b> Was beschreibt das Fahrassistenzsystem des Nova Elektro X7 am genauesten?", choices:["Es ermöglicht vollständig autonomes Fahren ohne menschliche Aufsicht.","Es unterstützt teilautomatisiertes Fahren auf Level 3.","Es bietet lediglich eine Spurhalteassistenz.","Es entspricht dem höchsten Autonomiegrad nach SAE-Norm."], answer:1},

  {q:"<div class=\"stimulus\"><pre>NOVA ELEKTRO X7 — Das Fahrzeug der Zukunft\n\nReichweite:        620 km (WLTP-Norm)\nLadedauer:         18 Minuten (10 % → 80 %)\nAntrieb:           Dual-Motor, Allradantrieb\nLeistung:          350 kW / 476 PS\nBatteriekapazität: 100 kWh (Lithium-Eisenphosphat)\nFahrassistenz:     Level 3 Autonomes Fahren\nPreis ab:          54 990 € (inkl. MwSt.)\nVerfügbar:         ab März 2026 beim autorisierten Fachhändler\n\nNachhaltigkeitsversprechen: 85 % der Fahrzeugkomponenten sind\nrecyclingfähig. Die Produktion erfolgt CO₂-neutral im Werk Zwickau.</pre></div><b>4.</b> Welche Antriebstechnologie verwendet der Nova Elektro X7?", choices:["Einen Elektromotor mit Frontantrieb","Einen Hybridantrieb mit Verbrennungsmotor","Zwei Elektromotoren mit Allradantrieb","Einen Wasserstoffbrennstoffzellenantrieb"], answer:2},

  {q:"<div class=\"stimulus\"><pre>NOVA ELEKTRO X7 — Das Fahrzeug der Zukunft\n\nReichweite:        620 km (WLTP-Norm)\nLadedauer:         18 Minuten (10 % → 80 %)\nAntrieb:           Dual-Motor, Allradantrieb\nLeistung:          350 kW / 476 PS\nBatteriekapazität: 100 kWh (Lithium-Eisenphosphat)\nFahrassistenz:     Level 3 Autonomes Fahren\nPreis ab:          54 990 € (inkl. MwSt.)\nVerfügbar:         ab März 2026 beim autorisierten Fachhändler\n\nNachhaltigkeitsversprechen: 85 % der Fahrzeugkomponenten sind\nrecyclingfähig. Die Produktion erfolgt CO₂-neutral im Werk Zwickau.</pre></div><b>5.</b> Wann und wo kann man den Nova Elektro X7 erwerben?", choices:["Sofort online direkt beim Hersteller","Ab März 2026 beim autorisierten Fachhändler","Exklusiv im Werk Zwickau ab Januar 2026","Ab sofort in ausgewählten Autohäusern bundesweit"], answer:1},

  {q:"<div class=\"stimulus\"><pre>NOVA ELEKTRO X7 — Das Fahrzeug der Zukunft\n\nReichweite:        620 km (WLTP-Norm)\nLadedauer:         18 Minuten (10 % → 80 %)\nAntrieb:           Dual-Motor, Allradantrieb\nLeistung:          350 kW / 476 PS\nBatteriekapazität: 100 kWh (Lithium-Eisenphosphat)\nFahrassistenz:     Level 3 Autonomes Fahren\nPreis ab:          54 990 € (inkl. MwSt.)\nVerfügbar:         ab März 2026 beim autorisierten Fachhändler\n\nNachhaltigkeitsversprechen: 85 % der Fahrzeugkomponenten sind\nrecyclingfähig. Die Produktion erfolgt CO₂-neutral im Werk Zwickau.</pre></div><b>6.</b> Welchen Batterietyp verwendet der Nova Elektro X7?", choices:["Lithium-Ionen (NMC)","Feststoffbatterie","Lithium-Eisenphosphat (LFP)","Nickel-Metallhydrid"], answer:2},

  // ── Questions 7–12: Email from a university researcher ──

  {q:"<div class=\"stimulus\"><pre>Von: Dr. Miriam Schreiber <m.schreiber@kit.edu>\nAn: Forschungsgruppe Klimatechnologie\nBetreff: Projektupdate – KI-gestützte Klimamodellierung\nDatum: 14. April 2026\n\nSehr geehrte Kolleginnen und Kollegen,\n\nic​h freue mich, Ihnen mitteilen zu können, dass unser Verbundprojekt\n„KlimaNet 2030\" eine wichtige Meilensteinphase erreicht hat. Mithilfe\neines neuronalen Netzes mit 12 Milliarden Parametern konnten wir\nregionale Niederschlagsmuster in Mitteleuropa mit einer Genauigkeit\nvon 94 % über einen Zeitraum von 90 Tagen vorhersagen — ein Ergebnis,\ndas bisherige numerische Wettermodelle um 18 Prozentpunkte übertrifft.\n\nDiese Durchbruchergebnisse wurden gestern beim European Climate\nResearch Summit in Genf präsentiert und stießen auf großes Interesse\nbei der Europäischen Kommission, die zusätzliche Fördermittel in Höhe\nvon 3,2 Millionen Euro signalisiert hat.\n\nDer nächste Schritt besteht darin, das Modell auf Extremwetterereignisse\nwie Dürren und Starkregen zu spezialisieren. Ich bitte alle Teilprojekte,\nrelevante Datensätze bis zum 30. April einzureichen.\n\nMit freundlichen Grüßen,\nDr. Miriam Schreiber\nKarlsruher Institut für Technologie (KIT)</pre></div><b>7.</b> Was ist das Hauptziel des Projekts „KlimaNet 2030\"?", choices:["Die Entwicklung neuer Solarenergieanlagen in Mitteleuropa","Die KI-gestützte Vorhersage regionaler Klimamuster","Die Reduzierung des CO₂-Ausstoßes durch maschinelles Lernen","Die Automatisierung von Wetterstationen in ganz Deutschland"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Von: Dr. Miriam Schreiber <m.schreiber@kit.edu>\nAn: Forschungsgruppe Klimatechnologie\nBetreff: Projektupdate – KI-gestützte Klimamodellierung\nDatum: 14. April 2026\n\nSehr geehrte Kolleginnen und Kollegen,\n\nIch freue mich, Ihnen mitteilen zu können, dass unser Verbundprojekt\n„KlimaNet 2030\" eine wichtige Meilensteinphase erreicht hat. Mithilfe\neines neuronalen Netzes mit 12 Milliarden Parametern konnten wir\nregionale Niederschlagsmuster in Mitteleuropa mit einer Genauigkeit\nvon 94 % über einen Zeitraum von 90 Tagen vorhersagen — ein Ergebnis,\ndas bisherige numerische Wettermodelle um 18 Prozentpunkte übertrifft.\n\nDiese Durchbruchergebnisse wurden gestern beim European Climate\nResearch Summit in Genf präsentiert und stießen auf großes Interesse\nbei der Europäischen Kommission, die zusätzliche Fördermittel in Höhe\nvon 3,2 Millionen Euro signalisiert hat.\n\nDer nächste Schritt besteht darin, das Modell auf Extremwetterereignisse\nwie Dürren und Starkregen zu spezialisieren. Ich bitte alle Teilprojekte,\nrelevante Datensätze bis zum 30. April einzureichen.\n\nMit freundlichen Grüßen,\nDr. Miriam Schreiber\nKarlsruher Institut für Technologie (KIT)</pre></div><b>8.</b> Um wie viel Prozentpunkte übertrifft das KI-Modell herkömmliche numerische Wettermodelle?", choices:["14 Prozentpunkte","94 Prozentpunkte","18 Prozentpunkte","12 Prozentpunkte"], answer:2},

  {q:"<div class=\"stimulus\"><pre>Von: Dr. Miriam Schreiber <m.schreiber@kit.edu>\nAn: Forschungsgruppe Klimatechnologie\nBetreff: Projektupdate – KI-gestützte Klimamodellierung\nDatum: 14. April 2026\n\nSehr geehrte Kolleginnen und Kollegen,\n\nIch freue mich, Ihnen mitteilen zu können, dass unser Verbundprojekt\n„KlimaNet 2030\" eine wichtige Meilensteinphase erreicht hat. Mithilfe\neines neuronalen Netzes mit 12 Milliarden Parametern konnten wir\nregionale Niederschlagsmuster in Mitteleuropa mit einer Genauigkeit\nvon 94 % über einen Zeitraum von 90 Tagen vorhersagen — ein Ergebnis,\ndas bisherige numerische Wettermodelle um 18 Prozentpunkte übertrifft.\n\nDiese Durchbruchergebnisse wurden gestern beim European Climate\nResearch Summit in Genf präsentiert und stießen auf großes Interesse\nbei der Europäischen Kommission, die zusätzliche Fördermittel in Höhe\nvon 3,2 Millionen Euro signalisiert hat.\n\nMit freundlichen Grüßen,\nDr. Miriam Schreiber\nKarlsruher Institut für Technologie (KIT)</pre></div><b>9.</b> Wo wurden die Ergebnisse des Projekts präsentiert?", choices:["Auf einer Konferenz in Berlin","Beim European Climate Research Summit in Genf","Im Deutschen Bundestag in Berlin","An der Universität Heidelberg"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Von: Dr. Miriam Schreiber <m.schreiber@kit.edu>\nAn: Forschungsgruppe Klimatechnologie\nBetreff: Projektupdate – KI-gestützte Klimamodellierung\nDatum: 14. April 2026\n\nSehr geehrte Kolleginnen und Kollegen,\n\nIch freue mich, Ihnen mitteilen zu können, dass unser Verbundprojekt\n„KlimaNet 2030\" eine wichtige Meilensteinphase erreicht hat. Mithilfe\neines neuronalen Netzes mit 12 Milliarden Parametern konnten wir\nregionale Niederschlagsmuster in Mitteleuropa mit einer Genauigkeit\nvon 94 % über einen Zeitraum von 90 Tagen vorhersagen — ein Ergebnis,\ndas bisherige numerische Wettermodelle um 18 Prozentpunkte übertrifft.\n\nDiese Durchbruchergebnisse wurden gestern beim European Climate\nResearch Summit in Genf präsentiert und stießen auf großes Interesse\nbei der Europäischen Kommission, die zusätzliche Fördermittel in Höhe\nvon 3,2 Millionen Euro signalisiert hat.\n\nDer nächste Schritt besteht darin, das Modell auf Extremwetterereignisse\nwie Dürren und Starkregen zu spezialisieren. Ich bitte alle Teilprojekte,\nrelevante Datensätze bis zum 30. April einzureichen.\n\nMit freundlichen Grüßen,\nDr. Miriam Schreiber\nKarlsruher Institut für Technologie (KIT)</pre></div><b>10.</b> Welche Reaktion zeigte die Europäische Kommission auf die Ergebnisse?", choices:["Sie lehnte eine weitere Förderung des Projekts ab.","Sie forderte eine vollständige Überarbeitung der Methodik.","Sie signalisierte zusätzliche Fördermittel von 3,2 Millionen Euro.","Sie übertrug das Projekt an eine andere Forschungsgruppe."], answer:2},

  {q:"<div class=\"stimulus\"><pre>Von: Dr. Miriam Schreiber <m.schreiber@kit.edu>\nAn: Forschungsgruppe Klimatechnologie\nBetreff: Projektupdate – KI-gestützte Klimamodellierung\nDatum: 14. April 2026\n\nSehr geehrte Kolleginnen und Kollegen,\n\nIch freue mich, Ihnen mitteilen zu können, dass unser Verbundprojekt\n„KlimaNet 2030\" eine wichtige Meilensteinphase erreicht hat. Mithilfe\neines neuronalen Netzes mit 12 Milliarden Parametern konnten wir\nregionale Niederschlagsmuster in Mitteleuropa mit einer Genauigkeit\nvon 94 % über einen Zeitraum von 90 Tagen vorhersagen — ein Ergebnis,\ndas bisherige numerische Wettermodelle um 18 Prozentpunkte übertrifft.\n\nDer nächste Schritt besteht darin, das Modell auf Extremwetterereignisse\nwie Dürren und Starkregen zu spezialisieren. Ich bitte alle Teilprojekte,\nrelevante Datensätze bis zum 30. April einzureichen.\n\nMit freundlichen Grüßen,\nDr. Miriam Schreiber\nKarlsruher Institut für Technologie (KIT)</pre></div><b>11.</b> Was wird als nächster Entwicklungsschritt für das KI-Modell genannt?", choices:["Integration in kommerzielle Wetter-Apps","Ausweitung auf Vorhersagen für die nächsten fünf Jahre","Spezialisierung auf Extremwetterereignisse wie Dürren und Starkregen","Zusammenarbeit mit dem Deutschen Wetterdienst"], answer:2},

  {q:"<div class=\"stimulus\"><pre>Von: Dr. Miriam Schreiber <m.schreiber@kit.edu>\nAn: Forschungsgruppe Klimatechnologie\nBetreff: Projektupdate – KI-gestützte Klimamodellierung\nDatum: 14. April 2026\n\nSehr geehrte Kolleginnen und Kollegen,\n\nIch freue mich, Ihnen mitteilen zu können, dass unser Verbundprojekt\n„KlimaNet 2030\" eine wichtige Meilensteinphase erreicht hat. Mithilfe\neines neuronalen Netzes mit 12 Milliarden Parametern konnten wir\nregionale Niederschlagsmuster in Mitteleuropa mit einer Genauigkeit\nvon 94 % über einen Zeitraum von 90 Tagen vorhersagen — ein Ergebnis,\ndas bisherige numerische Wettermodelle um 18 Prozentpunkte übertrifft.\n\nDer nächste Schritt besteht darin, das Modell auf Extremwetterereignisse\nwie Dürren und Starkregen zu spezialisieren. Ich bitte alle Teilprojekte,\nrelevante Datensätze bis zum 30. April einzureichen.\n\nMit freundlichen Grüßen,\nDr. Miriam Schreiber\nKarlsruher Institut für Technologie (KIT)</pre></div><b>12.</b> Welchen Ton verwendet Dr. Schreiber in ihrer E-Mail an die Forschungsgruppe?", choices:["Kritisch und mahnend","Informell und persönlich","Förmlich und sachlich mit positiver Grundstimmung","Pessimistisch und besorgniserregend"], answer:2},

  // ── Questions 13–18: Newspaper article on technology's impact ──

  {q:"<div class=\"stimulus\"><pre>DIGITALISIERUNG AN DEUTSCHEN SCHULEN: CHANCEN UND HERAUSFORDERUNGEN\nFrankfurter Allgemeine Zeitung, 10. April 2026\n\nDie Digitalisierung des deutschen Bildungssystems schreitet mit\nunterschiedlichem Tempo voran. Während Bundesländer wie Bayern und\nBaden-Württemberg digitale Lernplattformen flächendeckend eingeführt\nhaben, kämpfen strukturschwache Regionen noch immer mit unzureichender\nInfrastruktur und mangelnden Lehrerfortbildungen.\n\nEin zentrales Problem bleibt der sogenannte „digitale Graben\": Schüler\naus einkommensschwachen Haushalten haben seltener Zugang zu leistungs-\nfähigen Endgeräten und schnellem Internet. Laut einer aktuellen PISA-\nErgänzungsstudie verfügen nur 61 % der Schüler in ländlichen Gebieten\nüber eine stabile Breitbandverbindung, gegenüber 89 % in Großstädten.\n\nBefürworter der Digitalisierung betonen die Vorteile individualisierter\nLernalgorithmen, die das Lerntempo jedes Schülers anpassen und\nLehrkräfte entlasten können. Kritiker hingegen warnen vor einer\nÜberabhängigkeit von Technologie und dem Verlust sozialer Lernprozesse.\n\nDas Bundesministerium für Bildung und Forschung hat angekündigt, bis\n2028 insgesamt 6 Milliarden Euro in den Ausbau digitaler Infrastruktur\nan Schulen zu investieren — ein Vorhaben, das von Bildungsexperten als\nnotwendig, aber nicht hinreichend bezeichnet wird.</pre></div><b>13.</b> Was beschreibt der Begriff „digitaler Graben\" im Kontext des Artikels?", choices:["Den technologischen Rückstand Deutschlands gegenüber anderen EU-Ländern","Die Kluft zwischen Schülern mit und ohne Zugang zu digitalen Ressourcen","Den Unterschied zwischen digitalen und analogen Unterrichtsmethoden","Die fehlende Integration von KI in den Lehrplan"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DIGITALISIERUNG AN DEUTSCHEN SCHULEN: CHANCEN UND HERAUSFORDERUNGEN\nFrankfurter Allgemeine Zeitung, 10. April 2026\n\nDie Digitalisierung des deutschen Bildungssystems schreitet mit\nunterschiedlichem Tempo voran. Während Bundesländer wie Bayern und\nBaden-Württemberg digitale Lernplattformen flächendeckend eingeführt\nhaben, kämpfen strukturschwache Regionen noch immer mit unzureichender\nInfrastruktur und mangelnden Lehrerfortbildungen.\n\nEin zentrales Problem bleibt der sogenannte „digitale Graben\": Schüler\naus einkommensschwachen Haushalten haben seltener Zugang zu leistungs-\nfähigen Endgeräten und schnellem Internet. Laut einer aktuellen PISA-\nErgänzungsstudie verfügen nur 61 % der Schüler in ländlichen Gebieten\nüber eine stabile Breitbandverbindung, gegenüber 89 % in Großstädten.\n\nBefürworter der Digitalisierung betonen die Vorteile individualisierter\nLernalgorithmen, die das Lerntempo jedes Schülers anpassen und\nLehrkräfte entlasten können. Kritiker hingegen warnen vor einer\nÜberabhängigkeit von Technologie und dem Verlust sozialer Lernprozesse.\n\nDas Bundesministerium für Bildung und Forschung hat angekündigt, bis\n2028 insgesamt 6 Milliarden Euro in den Ausbau digitaler Infrastruktur\nan Schulen zu investieren — ein Vorhaben, das von Bildungsexperten als\nnotwendig, aber nicht hinreichend bezeichnet wird.</pre></div><b>14.</b> Wie hoch ist der Anteil der Schüler in ländlichen Gebieten mit stabiler Breitbandverbindung laut der PISA-Ergänzungsstudie?", choices:["89 %","74 %","61 %","45 %"], answer:2},

  {q:"<div class=\"stimulus\"><pre>DIGITALISIERUNG AN DEUTSCHEN SCHULEN: CHANCEN UND HERAUSFORDERUNGEN\nFrankfurter Allgemeine Zeitung, 10. April 2026\n\nDie Digitalisierung des deutschen Bildungssystems schreitet mit\nunterschiedlichem Tempo voran. Während Bundesländer wie Bayern und\nBaden-Württemberg digitale Lernplattformen flächendeckend eingeführt\nhaben, kämpfen strukturschwache Regionen noch immer mit unzureichender\nInfrastruktur und mangelnden Lehrerfortbildungen.\n\nBefürworter der Digitalisierung betonen die Vorteile individualisierter\nLernalgorithmen, die das Lerntempo jedes Schülers anpassen und\nLehrkräfte entlasten können. Kritiker hingegen warnen vor einer\nÜberabhängigkeit von Technologie und dem Verlust sozialer Lernprozesse.\n\nDas Bundesministerium für Bildung und Forschung hat angekündigt, bis\n2028 insgesamt 6 Milliarden Euro in den Ausbau digitaler Infrastruktur\nan Schulen zu investieren — ein Vorhaben, das von Bildungsexperten als\nnotwendig, aber nicht hinreichend bezeichnet wird.</pre></div><b>15.</b> Welchen Hauptvorteil individualisierter Lernalgorithmen nennt der Artikel?", choices:["Sie ermöglichen den vollständigen Verzicht auf Lehrkräfte.","Sie passen das Lerntempo individuell an und entlasten Lehrkräfte.","Sie ersetzen traditionelle Prüfungsverfahren vollständig.","Sie garantieren gleiche Lernchancen unabhängig vom Einkommen."], answer:1},

  {q:"<div class=\"stimulus\"><pre>DIGITALISIERUNG AN DEUTSCHEN SCHULEN: CHANCEN UND HERAUSFORDERUNGEN\nFrankfurter Allgemeine Zeitung, 10. April 2026\n\nDie Digitalisierung des deutschen Bildungssystems schreitet mit\nunterschiedlichem Tempo voran. Während Bundesländer wie Bayern und\nBaden-Württemberg digitale Lernplattformen flächendeckend eingeführt\nhaben, kämpfen strukturschwache Regionen noch immer mit unzureichender\nInfrastruktur und mangelnden Lehrerfortbildungen.\n\nBefürworter der Digitalisierung betonen die Vorteile individualisierter\nLernalgorithmen, die das Lerntempo jedes Schülers anpassen und\nLehrkräfte entlasten können. Kritiker hingegen warnen vor einer\nÜberabhängigkeit von Technologie und dem Verlust sozialer Lernprozesse.\n\nDas Bundesministerium für Bildung und Forschung hat angekündigt, bis\n2028 insgesamt 6 Milliarden Euro in den Ausbau digitaler Infrastruktur\nan Schulen zu investieren — ein Vorhaben, das von Bildungsexperten als\nnotwendig, aber nicht hinreichend bezeichnet wird.</pre></div><b>16.</b> Wie bewerten Bildungsexperten die geplante Investition des Bundesministeriums?", choices:["Als ausreichend und weitreichend","Als notwendig, aber nicht hinreichend","Als übertrieben und schlecht geplant","Als zu gering angesichts der Herausforderungen"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DIGITALISIERUNG AN DEUTSCHEN SCHULEN: CHANCEN UND HERAUSFORDERUNGEN\nFrankfurter Allgemeine Zeitung, 10. April 2026\n\nDie Digitalisierung des deutschen Bildungssystems schreitet mit\nunterschiedlichem Tempo voran. Während Bundesländer wie Bayern und\nBaden-Württemberg digitale Lernplattformen flächendeckend eingeführt\nhaben, kämpfen strukturschwache Regionen noch immer mit unzureichender\nInfrastruktur und mangelnden Lehrerfortbildungen.\n\nBefürworter der Digitalisierung betonen die Vorteile individualisierter\nLernalgorithmen, die das Lerntempo jedes Schülers anpassen und\nLehrkräfte entlasten können. Kritiker hingegen warnen vor einer\nÜberabhängigkeit von Technologie und dem Verlust sozialer Lernprozesse.\n\nDas Bundesministerium für Bildung und Forschung hat angekündigt, bis\n2028 insgesamt 6 Milliarden Euro in den Ausbau digitaler Infrastruktur\nan Schulen zu investieren.</pre></div><b>17.</b> Wovor warnen Kritiker der schulischen Digitalisierung?", choices:["Vor zu hohen Kosten für Schulbücher","Vor Überabhängigkeit von Technologie und Verlust sozialer Lernprozesse","Vor dem Rückgang der Schülerzahlen in ländlichen Regionen","Vor mangelnder Kompatibilität der Lernsoftware mit EU-Standards"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DIGITALISIERUNG AN DEUTSCHEN SCHULEN: CHANCEN UND HERAUSFORDERUNGEN\nFrankfurter Allgemeine Zeitung, 10. April 2026\n\nDie Digitalisierung des deutschen Bildungssystems schreitet mit\nunterschiedlichem Tempo voran. Während Bundesländer wie Bayern und\nBaden-Württemberg digitale Lernplattformen flächendeckend eingeführt\nhaben, kämpfen strukturschwache Regionen noch immer mit unzureichender\nInfrastruktur und mangelnden Lehrerfortbildungen.</pre></div><b>18.</b> Welche Bundesländer werden im Artikel als Vorreiter der Digitalisierung erwähnt?", choices:["Berlin und Hamburg","Nordrhein-Westfalen und Sachsen","Bayern und Baden-Württemberg","Hessen und Thüringen"], answer:2},

  // ── Questions 19–24: Interview with a German artist / architect ──

  {q:"<div class=\"stimulus\"><pre>INTERVIEW MIT DER ARCHITEKTIN PROF. DR. LEILA HARTMANN\n(Veröffentlicht in: Architektur & Kultur, Ausgabe 3/2026)\n\nFrage: Frau Prof. Hartmann, Sie haben sich intensiv mit dem Erbe des\nBauhauses beschäftigt. Inwiefern beeinflusst das Bauhaus noch heute\ndie zeitgenössische Architektur?\n\nHartmann: Das Bauhaus war eine Revolution — nicht nur ästhetisch, sondern\nphilosophisch. Die Idee, dass Form der Funktion folgen soll und dass\nKunst und Handwerk keine getrennten Disziplinen sind, ist heute\nrelevanter denn je. In meinen eigenen Entwürfen versuche ich, diese\nGrundsätze mit modernen Materialien wie Carbonbeton und Photovoltaik-\nGlas zu verbinden.\n\nFrage: Ist „form follows function\" in der Ära nachhaltiger Architektur\nnoch zeitgemäß?\n\nHartmann: Ich erweitere dieses Prinzip um eine dritte Dimension: „form\nfollows function follows ecology.\" Gebäude müssen nicht nur funktional\nund ästhetisch sein, sie müssen ihrem ökologischen Kontext dienen. Die\nBerliner Philharmonie von Hans Scharoun ist für mich ein Vorbild:\ndie Akustik bestimmt die Form, und das Ergebnis ist magisch.\n\nFrage: Welche Rolle spielt digitale Technologie in Ihrem Entwurfsprozess?\n\nHartmann: Parametrisches Design und KI-gestützte Optimierungstools\nermöglichen es uns, in Minuten tausende von Varianten zu testen, die\nfrüher Monate erfordert hätten. Dennoch bleibt die kreative Intuition\ndes Architekten unersetzlich — Algorithmen können noch keine\narchitektonische Empathie entwickeln.</pre></div><b>19.</b> Welches Grundprinzip des Bauhauses erwähnt Prof. Hartmann als besonders bedeutsam?", choices:["Die Trennung von Kunst und Handwerk","Die Überzeugung, dass Form der Funktion folgen soll","Die Verwendung traditioneller Baumaterialien","Die Ablehnung industrieller Fertigungsmethoden"], answer:1},

  {q:"<div class=\"stimulus\"><pre>INTERVIEW MIT DER ARCHITEKTIN PROF. DR. LEILA HARTMANN\n(Veröffentlicht in: Architektur & Kultur, Ausgabe 3/2026)\n\nHartmann: Ich erweitere dieses Prinzip um eine dritte Dimension: „form\nfollows function follows ecology.\" Gebäude müssen nicht nur funktional\nund ästhetisch sein, sie müssen ihrem ökologischen Kontext dienen. Die\nBerliner Philharmonie von Hans Scharoun ist für mich ein Vorbild:\ndie Akustik bestimmt die Form, und das Ergebnis ist magisch.\n\nFrage: Welche Rolle spielt digitale Technologie in Ihrem Entwurfsprozess?\n\nHartmann: Parametrisches Design und KI-gestützte Optimierungstools\nermöglichen es uns, in Minuten tausende von Varianten zu testen, die\nfrüher Monate erfordert hätten. Dennoch bleibt die kreative Intuition\ndes Architekten unersetzlich — Algorithmen können noch keine\narchitektonische Empathie entwickeln.</pre></div><b>20.</b> Wie erweitert Prof. Hartmann das Prinzip „form follows function\"?", choices:["Sie fügt Wirtschaftlichkeit als dritte Dimension hinzu.","Sie ergänzt es um die ökologische Verantwortung des Gebäudes.","Sie ersetzt es durch ein rein ästhetisches Konzept.","Sie lehnt das Prinzip als veraltet ab."], answer:1},

  {q:"<div class=\"stimulus\"><pre>INTERVIEW MIT DER ARCHITEKTIN PROF. DR. LEILA HARTMANN\n(Veröffentlicht in: Architektur & Kultur, Ausgabe 3/2026)\n\nHartmann: Die Berliner Philharmonie von Hans Scharoun ist für mich ein\nVorbild: die Akustik bestimmt die Form, und das Ergebnis ist magisch.\n\nFrage: Welche Rolle spielt digitale Technologie in Ihrem Entwurfsprozess?\n\nHartmann: Parametrisches Design und KI-gestützte Optimierungstools\nermöglichen es uns, in Minuten tausende von Varianten zu testen, die\nfrüher Monate erfordert hätten. Dennoch bleibt die kreative Intuition\ndes Architekten unersetzlich — Algorithmen können noch keine\narchitektonische Empathie entwickeln.</pre></div><b>21.</b> Warum nennt Prof. Hartmann die Berliner Philharmonie als Vorbild?", choices:["Weil sie das älteste Konzerthaus Deutschlands ist","Weil die Akustik die Form des Gebäudes bestimmt","Weil sie ausschließlich aus recycelten Materialien erbaut wurde","Weil Hans Scharoun ein Schüler des Bauhauses war"], answer:1},

  {q:"<div class=\"stimulus\"><pre>INTERVIEW MIT DER ARCHITEKTIN PROF. DR. LEILA HARTMANN\n(Veröffentlicht in: Architektur & Kultur, Ausgabe 3/2026)\n\nHartmann: Parametrisches Design und KI-gestützte Optimierungstools\nermöglichen es uns, in Minuten tausende von Varianten zu testen, die\nfrüher Monate erfordert hätten. Dennoch bleibt die kreative Intuition\ndes Architekten unersetzlich — Algorithmen können noch keine\narchitektonische Empathie entwickeln.</pre></div><b>22.</b> Welchen Vorteil nennt Prof. Hartmann beim Einsatz von parametrischem Design und KI?", choices:["Es ersetzt vollständig die Notwendigkeit menschlicher Architekten.","Es ermöglicht, in Minuten tausende Varianten zu testen.","Es reduziert die Baukosten um mehr als 50 %.","Es garantiert, dass alle Entwürfe nachhaltig sind."], answer:1},

  {q:"<div class=\"stimulus\"><pre>INTERVIEW MIT DER ARCHITEKTIN PROF. DR. LEILA HARTMANN\n(Veröffentlicht in: Architektur & Kultur, Ausgabe 3/2026)\n\nHartmann: Parametrisches Design und KI-gestützte Optimierungstools\nermöglichen es uns, in Minuten tausende von Varianten zu testen, die\nfrüher Monate erfordert hätten. Dennoch bleibt die kreative Intuition\ndes Architekten unersetzlich — Algorithmen können noch keine\narchitektonische Empathie entwickeln.</pre></div><b>23.</b> Welche Einschränkung sieht Prof. Hartmann bei KI-gestützten Entwurfstools?", choices:["Sie sind zu kostspielig für kleine Architekturbüros.","Sie produzieren ästhetisch minderwertige Ergebnisse.","Sie können keine architektonische Empathie entwickeln.","Sie sind mit deutschen Bauvorschriften unvereinbar."], answer:2},

  {q:"<div class=\"stimulus\"><pre>INTERVIEW MIT DER ARCHITEKTIN PROF. DR. LEILA HARTMANN\n(Veröffentlicht in: Architektur & Kultur, Ausgabe 3/2026)\n\nIn meinen eigenen Entwürfen versuche ich, diese Grundsätze mit modernen\nMaterialien wie Carbonbeton und Photovoltaik-Glas zu verbinden.</pre></div><b>24.</b> Welche modernen Materialien verwendet Prof. Hartmann in ihren Entwürfen, um Bauhaus-Prinzipien umzusetzen?", choices:["Stahl und traditionellen Ziegel","Carbonbeton und Photovoltaik-Glas","Recyceltes Holz und Bambus","Aluminium und Verbundwerkstoffe"], answer:1},

  // ── Questions 25–30: Magazine article on German design / Bauhaus ──

  {q:"<div class=\"stimulus\"><pre>DAS BAUHAUS-ERBE: 100 JAHRE DESIGN-REVOLUTION\n(Auszug aus: Design Magazin Deutschland, März 2026)\n\nAls Walter Gropius 1919 das Staatliche Bauhaus in Weimar gründete,\nkonnte er kaum ahnen, welchen nachhaltigen Einfluss diese Schule auf\ndie globale Designgeschichte haben würde. Die Grundidee war provokativ\neinfach: Kunst, Handwerk und Technologie sollten in einer Einheit\nverschmelzen, um alltagstaugliche, schöne und erschwingliche Objekte\nfür alle Menschen zu schaffen — nicht nur für eine elitäre Oberschicht.\n\nDie bedeutendsten Leistungen des Bauhauses liegen nicht nur in\nikonischen Produkten wie der Wagenfeld-Lampe oder dem Barcelona-Sessel,\nsondern in der Pädagogik: Der Vorkurs, ein revolutionäres erstes\nSemester, in dem alle Studierenden — unabhängig von ihrer Disziplin —\ndie Grundlagen von Material, Form und Farbe erkundeten, prägt noch\nheute zahlreiche Designstudiengänge weltweit.\n\nNach der Schließung durch die Nationalsozialisten 1933 emigrierten\nviele Bauhaus-Meister in die USA und beeinflussten dort Schulen wie\ndas Illinois Institute of Technology. Der sogenannte „Internationale\nStil\" in der Architektur — geprägt durch Flachdächer, Glasbauweise\nund den Verzicht auf Ornamentik — ist sein direktes Erbe.\n\nIn Deutschland selbst wurde das Bauhaus-Erbe lange ambivalent\nbetrachtet. Erst die UNESCO-Aufnahme der Bauhaus-Stätten in Dessau\nund Weimar in die Welterbeliste 1996 führte zu einem breiten gesell-\nschaftlichen Umdenken und einem neuen Stolz auf dieses kulturelle Erbe.</pre></div><b>25.</b> Was war die Kernidee bei der Gründung des Bauhauses laut dem Artikel?", choices:["Die Förderung elitärer Kunstformen für eine gehobene Gesellschaftsschicht","Die Trennung von Kunst und industrieller Produktion","Die Verbindung von Kunst, Handwerk und Technologie für alltagstaugliche Objekte","Die Rückkehr zu handwerklichen Traditionen des Mittelalters"], answer:2},

  {q:"<div class=\"stimulus\"><pre>DAS BAUHAUS-ERBE: 100 JAHRE DESIGN-REVOLUTION\n(Auszug aus: Design Magazin Deutschland, März 2026)\n\nDie bedeutendsten Leistungen des Bauhauses liegen nicht nur in\nikonischen Produkten wie der Wagenfeld-Lampe oder dem Barcelona-Sessel,\nsondern in der Pädagogik: Der Vorkurs, ein revolutionäres erstes\nSemester, in dem alle Studierenden — unabhängig von ihrer Disziplin —\ndie Grundlagen von Material, Form und Farbe erkundeten, prägt noch\nheute zahlreiche Designstudiengänge weltweit.</pre></div><b>26.</b> Worin sieht der Artikel die bedeutendste pädagogische Innovation des Bauhauses?", choices:["In der Einführung digitaler Entwurfsmethoden","Im Vorkurs, der allen Studierenden Grundlagen von Material, Form und Farbe vermittelte","In der Spezialisierung auf Architektur als Hauptdisziplin","In der Kooperation mit der deutschen Industrie"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DAS BAUHAUS-ERBE: 100 JAHRE DESIGN-REVOLUTION\n(Auszug aus: Design Magazin Deutschland, März 2026)\n\nNach der Schließung durch die Nationalsozialisten 1933 emigrierten\nviele Bauhaus-Meister in die USA und beeinflussten dort Schulen wie\ndas Illinois Institute of Technology. Der sogenannte „Internationale\nStil\" in der Architektur — geprägt durch Flachdächer, Glasbauweise\nund den Verzicht auf Ornamentik — ist sein direktes Erbe.</pre></div><b>27.</b> Welche Folge hatte die Schließung des Bauhauses 1933 für die Verbreitung seiner Ideen?", choices:["Die Ideen des Bauhauses gerieten in Vergessenheit.","Viele Meister emigrierten in die USA und beeinflussten dortige Schulen.","Das Bauhaus wurde nach dem Krieg in seiner ursprünglichen Form wiedereröffnet.","Die Nationalsozialisten übernahmen die Bauhaus-Ästhetik für ihre Propaganda."], answer:1},

  {q:"<div class=\"stimulus\"><pre>DAS BAUHAUS-ERBE: 100 JAHRE DESIGN-REVOLUTION\n(Auszug aus: Design Magazin Deutschland, März 2026)\n\nDer sogenannte „Internationale Stil\" in der Architektur — geprägt durch\nFlachdächer, Glasbauweise und den Verzicht auf Ornamentik — ist sein\ndirekt​es Erbe.</pre></div><b>28.</b> Durch welche Merkmale ist der „Internationale Stil\" laut dem Artikel gekennzeichnet?", choices:["Spitzdächer, Ziegelmauerwerk und reiche Ornamentik","Flachdächer, Glasbauweise und Verzicht auf Ornamentik","Holzkonstruktionen, begrünte Dächer und lokale Baumaterialien","Historisierende Fassaden und klassische Säulenarchitektur"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DAS BAUHAUS-ERBE: 100 JAHRE DESIGN-REVOLUTION\n(Auszug aus: Design Magazin Deutschland, März 2026)\n\nIn Deutschland selbst wurde das Bauhaus-Erbe lange ambivalent\nbetrachtet. Erst die UNESCO-Aufnahme der Bauhaus-Stätten in Dessau\nund Weimar in die Welterbeliste 1996 führte zu einem breiten gesell-\nschaftlichen Umdenken und einem neuen Stolz auf dieses kulturelle Erbe.</pre></div><b>29.</b> Was veränderte die Wahrnehmung des Bauhaus-Erbes in Deutschland?", choices:["Die Feierlichkeiten zum 100. Jahrestag der Gründung im Jahr 2019","Die UNESCO-Aufnahme der Bauhaus-Stätten in Dessau und Weimar 1996","Ein erfolgreicher Dokumentarfilm über Walter Gropius","Die Neuauflage von Bauhaus-Produkten durch große Möbelkonzerne"], answer:1},

  {q:"<div class=\"stimulus\"><pre>DAS BAUHAUS-ERBE: 100 JAHRE DESIGN-REVOLUTION\n(Auszug aus: Design Magazin Deutschland, März 2026)\n\nAls Walter Gropius 1919 das Staatliche Bauhaus in Weimar gründete,\nkonnte er kaum ahnen, welchen nachhaltigen Einfluss diese Schule auf\ndie globale Designgeschichte haben würde.</pre></div><b>30.</b> In welcher Stadt und in welchem Jahr wurde das Bauhaus gegründet?", choices:["Dessau, 1923","Berlin, 1919","Weimar, 1919","Weimar, 1933"], answer:2},

  // ── Questions 31–36: Science text with HTML table ──

  {q:"<div class=\"stimulus\"><pre>ENERGIEVERBRAUCH NACH BUNDESLÄNDERN (2025)\nQuelle: Bundesnetzagentur, Jahresbericht 2025\n\nDer Anteil erneuerbarer Energien am Bruttostromverbrauch variiert\nerheblich zwischen den deutschen Bundesländern. Während norddeutsche\nKüstenländer wie Schleswig-Holstein von Wind- und Solarenergie\nprofitieren, stehen Industrieländer wie Nordrhein-Westfalen noch immer\nvor großen Herausforderungen beim Kohleausstieg.\n</pre><table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.9em\">\n<tr><th>Bundesland</th><th>Erneuerbare (%)</th><th>Kohle (%)</th><th>Gas (%)</th></tr>\n<tr><td>Schleswig-Holstein</td><td>104</td><td>0</td><td>3</td></tr>\n<tr><td>Bayern</td><td>62</td><td>4</td><td>22</td></tr>\n<tr><td>Baden-Württemberg</td><td>48</td><td>8</td><td>28</td></tr>\n<tr><td>Nordrhein-Westfalen</td><td>32</td><td>38</td><td>24</td></tr>\n<tr><td>Sachsen</td><td>41</td><td>29</td><td>18</td></tr>\n<tr><td>Brandenburg</td><td>87</td><td>9</td><td>2</td></tr>\n</table><br/></div><b>31.</b> Welches Bundesland produziert laut der Tabelle mehr erneuerbare Energie als es verbraucht?", choices:["Brandenburg","Bayern","Baden-Württemberg","Schleswig-Holstein"], answer:3},

  {q:"<div class=\"stimulus\"><pre>ENERGIEVERBRAUCH NACH BUNDESLÄNDERN (2025)\nQuelle: Bundesnetzagentur, Jahresbericht 2025\n\nDer Anteil erneuerbarer Energien am Bruttostromverbrauch variiert\nerheblich zwischen den deutschen Bundesländern.\n</pre><table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.9em\">\n<tr><th>Bundesland</th><th>Erneuerbare (%)</th><th>Kohle (%)</th><th>Gas (%)</th></tr>\n<tr><td>Schleswig-Holstein</td><td>104</td><td>0</td><td>3</td></tr>\n<tr><td>Bayern</td><td>62</td><td>4</td><td>22</td></tr>\n<tr><td>Baden-Württemberg</td><td>48</td><td>8</td><td>28</td></tr>\n<tr><td>Nordrhein-Westfalen</td><td>32</td><td>38</td><td>24</td></tr>\n<tr><td>Sachsen</td><td>41</td><td>29</td><td>18</td></tr>\n<tr><td>Brandenburg</td><td>87</td><td>9</td><td>2</td></tr>\n</table><br/></div><b>32.</b> Welches Bundesland hat laut der Tabelle den höchsten Kohleanteil am Stromverbrauch?", choices:["Sachsen","Schleswig-Holstein","Baden-Württemberg","Nordrhein-Westfalen"], answer:3},

  {q:"<div class=\"stimulus\"><pre>ENERGIEVERBRAUCH NACH BUNDESLÄNDERN (2025)\nQuelle: Bundesnetzagentur, Jahresbericht 2025\n</pre><table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.9em\">\n<tr><th>Bundesland</th><th>Erneuerbare (%)</th><th>Kohle (%)</th><th>Gas (%)</th></tr>\n<tr><td>Schleswig-Holstein</td><td>104</td><td>0</td><td>3</td></tr>\n<tr><td>Bayern</td><td>62</td><td>4</td><td>22</td></tr>\n<tr><td>Baden-Württemberg</td><td>48</td><td>8</td><td>28</td></tr>\n<tr><td>Nordrhein-Westfalen</td><td>32</td><td>38</td><td>24</td></tr>\n<tr><td>Sachsen</td><td>41</td><td>29</td><td>18</td></tr>\n<tr><td>Brandenburg</td><td>87</td><td>9</td><td>2</td></tr>\n</table><br/></div><b>33.</b> Welches Bundesland weist den höchsten Gasanteil auf?", choices:["Nordrhein-Westfalen","Bayern","Baden-Württemberg","Brandenburg"], answer:2},

  {q:"<div class=\"stimulus\"><pre>ENERGIEVERBRAUCH NACH BUNDESLÄNDERN (2025)\nQuelle: Bundesnetzagentur, Jahresbericht 2025\n\nWährend norddeutsche Küstenländer wie Schleswig-Holstein von Wind-\nund Solarenergie profitieren, stehen Industrieländer wie Nordrhein-\nWestfalen noch immer vor großen Herausforderungen beim Kohleausstieg.\n</pre><table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.9em\">\n<tr><th>Bundesland</th><th>Erneuerbare (%)</th><th>Kohle (%)</th><th>Gas (%)</th></tr>\n<tr><td>Schleswig-Holstein</td><td>104</td><td>0</td><td>3</td></tr>\n<tr><td>Bayern</td><td>62</td><td>4</td><td>22</td></tr>\n<tr><td>Baden-Württemberg</td><td>48</td><td>8</td><td>28</td></tr>\n<tr><td>Nordrhein-Westfalen</td><td>32</td><td>38</td><td>24</td></tr>\n<tr><td>Sachsen</td><td>41</td><td>29</td><td>18</td></tr>\n<tr><td>Brandenburg</td><td>87</td><td>9</td><td>2</td></tr>\n</table><br/></div><b>34.</b> Welche Schlussfolgerung lässt sich aus dem Text und der Tabelle ziehen?", choices:["Alle deutschen Bundesländer haben den Kohleausstieg bereits vollzogen.","Norddeutsche Bundesländer haben im Allgemeinen einen höheren Anteil erneuerbarer Energien.","Süddeutsche Bundesländer sind am stärksten von fossilen Brennstoffen abhängig.","Brandenburg hat den niedrigsten Anteil an erneuerbaren Energien."], answer:1},

  {q:"<div class=\"stimulus\"><pre>ENERGIEVERBRAUCH NACH BUNDESLÄNDERN (2025)\nQuelle: Bundesnetzagentur, Jahresbericht 2025\n</pre><table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.9em\">\n<tr><th>Bundesland</th><th>Erneuerbare (%)</th><th>Kohle (%)</th><th>Gas (%)</th></tr>\n<tr><td>Schleswig-Holstein</td><td>104</td><td>0</td><td>3</td></tr>\n<tr><td>Bayern</td><td>62</td><td>4</td><td>22</td></tr>\n<tr><td>Baden-Württemberg</td><td>48</td><td>8</td><td>28</td></tr>\n<tr><td>Nordrhein-Westfalen</td><td>32</td><td>38</td><td>24</td></tr>\n<tr><td>Sachsen</td><td>41</td><td>29</td><td>18</td></tr>\n<tr><td>Brandenburg</td><td>87</td><td>9</td><td>2</td></tr>\n</table><br/></div><b>35.</b> Wie viel Prozent seines Stroms bezieht Brandenburg aus erneuerbaren Quellen?", choices:["62 %","41 %","104 %","87 %"], answer:3},

  {q:"<div class=\"stimulus\"><pre>ENERGIEVERBRAUCH NACH BUNDESLÄNDERN (2025)\nQuelle: Bundesnetzagentur, Jahresbericht 2025\n\nDer Anteil erneuerbarer Energien am Bruttostromverbrauch variiert\nerheblich zwischen den deutschen Bundesländern.\n</pre><table border=\"1\" cellpadding=\"4\" style=\"border-collapse:collapse;font-size:0.9em\">\n<tr><th>Bundesland</th><th>Erneuerbare (%)</th><th>Kohle (%)</th><th>Gas (%)</th></tr>\n<tr><td>Schleswig-Holstein</td><td>104</td><td>0</td><td>3</td></tr>\n<tr><td>Bayern</td><td>62</td><td>4</td><td>22</td></tr>\n<tr><td>Baden-Württemberg</td><td>48</td><td>8</td><td>28</td></tr>\n<tr><td>Nordrhein-Westfalen</td><td>32</td><td>38</td><td>24</td></tr>\n<tr><td>Sachsen</td><td>41</td><td>29</td><td>18</td></tr>\n<tr><td>Brandenburg</td><td>87</td><td>9</td><td>2</td></tr>\n</table><br/></div><b>36.</b> Welches der folgenden Bundesländer hat den geringsten Kohleanteil nach Schleswig-Holstein?", choices:["Brandenburg","Sachsen","Baden-Württemberg","Bayern"], answer:3},

  // ── Questions 37–45: Mixed vocab / grammar-in-context (cloze) ──

  // Passage A (Q 37–39)
  {q:"<div class=\"stimulus\"><pre>Passage A:\nDie Fraunhofer-Gesellschaft ist eine der weltweit führenden\nOrganisationen für angewandte Forschung. Mit über 75 Instituten in ganz\nDeutschland _______ sie Innovationen, die direkt in die Industrie\neinfließen. Besonders im Bereich der Künstlichen Intelligenz hat die\nFraunhofer-Gesellschaft zahlreiche Patente angemeldet und gilt als\nwichtige Schnittstelle zwischen Grundlagenforschung und Marktreife.</pre></div><b>37.</b> Welches Wort passt am besten in die Lücke?", choices:["verweigert","fördert","vermeidet","unterbricht"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Passage A:\nDie Fraunhofer-Gesellschaft ist eine der weltweit führenden\nOrganisationen für angewandte Forschung. Mit über 75 Instituten in ganz\nDeutschland fördert sie Innovationen, die direkt in die Industrie\neinfließen. Besonders im Bereich der Künstlichen Intelligenz hat die\nFraunhofer-Gesellschaft zahlreiche Patente angemeldet und gilt als\nwichtige Schnittstelle zwischen Grundlagenforschung und Marktreife.</pre></div><b>38.</b> Was bedeutet „Schnittstelle\" in diesem Kontext?", choices:["Trennlinie","Verbindungspunkt zwischen zwei Bereichen","Finanzierungsquelle","Verwaltungsbehörde"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Passage A:\nDie Fraunhofer-Gesellschaft ist eine der weltweit führenden\nOrganisationen für angewandte Forschung. Mit über 75 Instituten in ganz\nDeutschland fördert sie Innovationen, die direkt in die Industrie\neinfließen. Besonders im Bereich der Künstlichen Intelligenz hat die\nFraunhofer-Gesellschaft zahlreiche Patente angemeldet und gilt als\nwichtige Schnittstelle zwischen Grundlagenforschung und Marktreife.</pre></div><b>39.</b> Was beschreibt der Begriff „Marktreife\" am besten?", choices:["Der Zustand, wenn ein Produkt bereit ist, verkauft zu werden","Die staatliche Zulassung für wissenschaftliche Experimente","Die Anzahl der Patente, die ein Unternehmen besitzt","Das Verfahren zur Antragstellung von Forschungsgeldern"], answer:0},

  // Passage B (Q 40–42)
  {q:"<div class=\"stimulus\"><pre>Passage B:\nDie Max-Planck-Gesellschaft _______ sich der Grundlagenforschung.\nIhre Wissenschaftlerinnen und Wissenschaftler arbeiten ohne unmittelbaren\nkommerziellen Druck und haben dadurch Freiheiten, die in der Industrie-\nforschung selten möglich sind. Viele Nobelpreisträger haben ihre\nentscheidenden Entdeckungen in Max-Planck-Instituten gemacht.</pre></div><b>40.</b> Welches Wort passt am besten in die Lücke?", choices:["widersetzt","widmet","entzieht","beschränkt"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Passage B:\nDie Max-Planck-Gesellschaft widmet sich der Grundlagenforschung.\nIhre Wissenschaftlerinnen und Wissenschaftler arbeiten ohne unmittelbaren\nkommerziellen Druck und haben dadurch Freiheiten, die in der Industrie-\nforschung selten möglich sind. Viele Nobelpreisträger haben ihre\nentscheidenden Entdeckungen in Max-Planck-Instituten gemacht.</pre></div><b>41.</b> Welches Adjektiv könnte „unmittelbaren\" in diesem Satz am besten ersetzen, ohne die Bedeutung wesentlich zu verändern?", choices:["direkten","überwältigenden","gelegentlichen","willkürlichen"], answer:0},

  {q:"<div class=\"stimulus\"><pre>Passage B:\nDie Max-Planck-Gesellschaft widmet sich der Grundlagenforschung.\nIhre Wissenschaftlerinnen und Wissenschaftler arbeiten ohne unmittelbaren\nkommerziellen Druck und haben dadurch Freiheiten, die in der Industrie-\nforschung selten möglich sind. Viele Nobelpreisträger haben ihre\nentscheidenden Entdeckungen in Max-Planck-Instituten gemacht.</pre></div><b>42.</b> Was impliziert der Text über Grundlagenforschung im Vergleich zu Industrieforschung?", choices:["Grundlagenforschung ist wirtschaftlich profitabler als Industrieforschung.","Grundlagenforschung bietet mehr wissenschaftliche Freiheit als Industrieforschung.","Industrieforschung führt häufiger zu Nobelpreisen.","Grundlagenforschung ist ausschließlich in Deutschland möglich."], answer:1},

  // Passage C (Q 43–45)
  {q:"<div class=\"stimulus\"><pre>Passage C:\nDas Konzept der „Industrie 4.0\" bezeichnet die vierte industrielle\nRevolution, in der Maschinen, Anlagen und Menschen durch das Internet\nder Dinge _______ vernetzt werden. Deutsche Unternehmen wie Siemens\nund Bosch gelten als Pioniere dieser Entwicklung. Kritiker weisen\njedoch darauf hin, dass die Automatisierung zahlreiche Arbeitsplätze\nin der Produktion gefährdet, insbesondere in strukturschwachen Regionen.</pre></div><b>43.</b> Welches Wort passt am besten in die Lücke?", choices:["vereinzelt","miteinander","gegeneinander","nachträglich"], answer:1},

  {q:"<div class=\"stimulus\"><pre>Passage C:\nDas Konzept der „Industrie 4.0\" bezeichnet die vierte industrielle\nRevolution, in der Maschinen, Anlagen und Menschen durch das Internet\nder Dinge miteinander vernetzt werden. Deutsche Unternehmen wie Siemens\nund Bosch gelten als Pioniere dieser Entwicklung. Kritiker weisen\njedoch darauf hin, dass die Automatisierung zahlreiche Arbeitsplätze\nin der Produktion gefährdet, insbesondere in strukturschwachen Regionen.</pre></div><b>44.</b> Was bedeutet „gelten als\" in diesem Kontext?", choices:["werden gesetzlich verpflichtet zu sein","sind offiziell zertifiziert als","werden angesehen als","haben bewiesen, dass sie sind"], answer:2},

  {q:"<div class=\"stimulus\"><pre>Passage C:\nDas Konzept der „Industrie 4.0\" bezeichnet die vierte industrielle\nRevolution, in der Maschinen, Anlagen und Menschen durch das Internet\nder Dinge miteinander vernetzt werden. Deutsche Unternehmen wie Siemens\nund Bosch gelten als Pioniere dieser Entwicklung. Kritiker weisen\njedoch darauf hin, dass die Automatisierung zahlreiche Arbeitsplätze\nin der Produktion gefährdet, insbesondere in strukturschwachen Regionen.</pre></div><b>45.</b> Welche Sorge äußern Kritiker der Industrie 4.0?", choices:["Deutsche Unternehmen verlieren ihre internationale Wettbewerbsfähigkeit.","Die Datensicherheit im Internet der Dinge ist unzureichend geregelt.","Die Automatisierung gefährdet Arbeitsplätze in der Produktion, besonders in schwachen Regionen.","Die Kosten der Vernetzung sind für mittelständische Betriebe zu hoch."], answer:2}
];

const GERMAN_SET2_FRQ = [
  {
    "title": "Task 1: Interpersonal Writing — E-Mail-Antwort (2024, 5 Punkte · 15 min)",
    "text": "<strong>📅 OFFICIAL AP German 2024 Exam (College Board)</strong><p><em>The full exam prompt is copyrighted by College Board. This app links to the official PDF — open it and then respond below.</em></p><p><strong>📄 Offizieller Prompt:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap24-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2024 FRQ PDF — Task 1 (Seite 1–2)</a></p><p><strong>📋 Offizielle Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap24-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">Scoring Guidelines PDF</a></p><hr><p><strong>Your task:</strong></p><ul><li>⏱ <strong>15 Minuten</strong>. Lesen Sie die E-Mail im offiziellen PDF.</li><li>✍️ Antworten Sie auf <strong>Deutsch</strong> in formellem Register (<strong>Sie-Form</strong>).</li><li>📌 Beantworten Sie <strong>alle</strong> gestellten Fragen und Anliegen.</li><li>📏 Ca. 150–200 Wörter.</li><li>🎯 Fügen Sie Begrüßung (Sehr geehrte/r …) und Schlussformel (Mit freundlichen Grüßen) ein.</li></ul><p><strong>Schreiben Sie Ihre Antwort unten:</strong></p>",
    "maxPoints": 5,
    "rubric": [
      {
        "part": "Score 5 (Strong)",
        "desc": "Fully addresses all task elements. Appropriate register and tone. Rich vocabulary, varied structures. Minor errors do not impede communication.",
        "pts": 1
      },
      {
        "part": "Score 4 (Good)",
        "desc": "Addresses most task elements well. Generally appropriate register. Good variety in vocabulary and structures. Some errors.",
        "pts": 1
      },
      {
        "part": "Score 3 (Fair)",
        "desc": "Addresses task at a basic level. Register mostly appropriate. Basic vocabulary and structures. Errors may occasionally impede.",
        "pts": 1
      },
      {
        "part": "Score 2 (Weak)",
        "desc": "Partial response. Inconsistent register. Limited vocabulary. Errors frequently impede communication.",
        "pts": 1
      },
      {
        "part": "Score 1 (Poor)",
        "desc": "Minimal response. Inappropriate register or tone. Very limited vocabulary. Errors severely impede communication.",
        "pts": 1
      },
    ]
  },
  {
    "title": "Task 2: Presentational Writing — Argumentativer Aufsatz (2024, 6 Punkte · 55 min)",
    "text": "<strong>📅 OFFICIAL AP German 2024 Exam (College Board)</strong><p><em>Full prompt and sources are copyrighted. Open the official PDF for the essay question, print sources, and chart. Listen to the audio source below.</em></p><p><strong>📄 Offizieller Prompt + Quellen 1 &amp; 2:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap24-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2024 FRQ PDF — Task 2</a></p><p><strong>🎧 Quelle 3 (Audio) — wird zweimal gespielt:</strong><br><audio controls preload=\"none\" style=\"width:100%;max-width:480px\"><source src=\"https://secure-media.collegeboard.org/apc/ap24-german-task-2-argumentative-essay.mp3\" type=\"audio/mpeg\">Ihr Browser unterstützt kein Audio.</audio></p><p><strong>📋 Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap24-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">SG PDF</a></p><hr><p><strong>Your task:</strong></p><ul><li>⏱ <strong>55 Minuten</strong> insgesamt: 6 min Quellen lesen/hören + 40 min schreiben (Audio ~4 min, 2×).</li><li>✍️ Schreiben Sie einen <strong>argumentativen Aufsatz</strong> zur Thesefrage im PDF.</li><li>📚 Integrieren Sie <strong>alle drei Quellen</strong> (Artikel, Grafik/Tabelle, Audio) und zitieren Sie sie (z.B. „Laut Quelle 1 …\").</li><li>🎯 Klare Position + Gegenargumente + Schlussfolgerung.</li><li>📏 Ca. 300–400 Wörter.</li></ul><p><strong>Schreiben Sie Ihren Aufsatz unten:</strong></p>",
    "maxPoints": 6,
    "rubric": [
      {
        "part": "Task Completion",
        "desc": "Response clearly takes a position and thoroughly addresses the prompt's essay question.",
        "pts": 1
      },
      {
        "part": "Source Integration",
        "desc": "Integrates and synthesizes information from ALL 3 sources (print article, visual/chart, audio). Cites sources appropriately.",
        "pts": 1
      },
      {
        "part": "Organization",
        "desc": "Clear thesis; logical paragraph structure; effective use of cohesive devices (außerdem, jedoch, dennoch, etc.).",
        "pts": 1
      },
      {
        "part": "Language Use",
        "desc": "Rich vocabulary and varied grammatical structures appropriate to argumentative essay register.",
        "pts": 1
      },
      {
        "part": "Cultural / Content Knowledge",
        "desc": "Draws on relevant knowledge of German-speaking cultures; examples and analysis are accurate.",
        "pts": 1
      },
      {
        "part": "Grammatical Accuracy",
        "desc": "Errors do not impede communication; accurate use of connectors, verb tenses, and case.",
        "pts": 1
      },
    ]
  },
  {
    "title": "Task 3: Interpersonal Speaking — Gespräch (2024, 5 Punkte · ~5 min)",
    "text": "<strong>🗣️ SPEAKING TASK — nicht automatisch bewertet. Nehmen Sie sich selbst auf.</strong><p><em>This is a spoken task. The app provides the official audio and prompt link; use the notes area for your outline or transcription.</em></p><p><strong>📄 Gesprächsrahmen (Prompt + Outline):</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap24-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2024 FRQ PDF — Task 3</a></p><p><strong>🔗 Speaking Prompts Page:</strong> <a href=\"https://apcentral.collegeboard.org/courses/ap-german-language-and-culture/exam/speaking-prompts-2024\" target=\"_blank\" rel=\"noopener\">AP Central — Speaking Prompts 2024</a></p><p><strong>🎧 Offizielles Audio (5 Wechsel, je 20 Sek. Antwort):</strong><br><audio controls preload=\"none\" style=\"width:100%;max-width:480px\"><source src=\"https://secure-media.collegeboard.org/apc/ap24-german-task-3-conversation.mp3\" type=\"audio/mpeg\">Ihr Browser unterstützt kein Audio.</audio></p><p><strong>📋 Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap24-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">SG PDF</a></p><hr><p><strong>Ablauf:</strong></p><ol><li>Lesen Sie im PDF das Rollenspiel-Szenario und den Gesprächsplan (Outline).</li><li>Starten Sie das Audio. Sie hören 5 Äußerungen des Gesprächspartners.</li><li>Nach jeder Äußerung <strong>20 Sekunden</strong> für Ihre Antwort auf Deutsch.</li><li>Sprechen Sie natürlich, verwenden Sie passendes Register (Du/Sie laut Szenario).</li></ol><p><strong>Notizen / Transkription (optional — nicht bewertet):</strong></p>",
    "maxPoints": 5,
    "rubric": [
      {
        "part": "Score 5 (Strong)",
        "desc": "Fully accomplishes task. Clear pronunciation, appropriate register, rich vocabulary, varied structures. Fluent delivery.",
        "pts": 1
      },
      {
        "part": "Score 4 (Good)",
        "desc": "Accomplishes task well. Mostly clear pronunciation, appropriate register, good vocabulary. Mostly fluent.",
        "pts": 1
      },
      {
        "part": "Score 3 (Fair)",
        "desc": "Basic accomplishment of task. Occasionally unclear pronunciation. Basic vocabulary. Some hesitation.",
        "pts": 1
      },
      {
        "part": "Score 2 (Weak)",
        "desc": "Partial accomplishment. Unclear pronunciation at times. Limited vocabulary. Frequent hesitation.",
        "pts": 1
      },
      {
        "part": "Score 1 (Poor)",
        "desc": "Minimal accomplishment. Pronunciation impedes comprehension. Very limited vocabulary. Severely halting.",
        "pts": 1
      },
    ]
  },
  {
    "title": "Task 4: Presentational Speaking — Kulturvergleich (2024, 5 Punkte · 2 min)",
    "text": "<strong>🗣️ SPEAKING TASK — nicht automatisch bewertet.</strong><p><em>This is a 2-minute oral presentation comparing a cultural aspect of your own community with the German-speaking world.</em></p><p><strong>📄 Offizieller Prompt:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap24-frq-german-language.pdf\" target=\"_blank\" rel=\"noopener\">2024 FRQ PDF — Task 4</a></p><p><strong>🔗 Speaking Prompts Page:</strong> <a href=\"https://apcentral.collegeboard.org/courses/ap-german-language-and-culture/exam/speaking-prompts-2024\" target=\"_blank\" rel=\"noopener\">AP Central — Speaking Prompts 2024</a></p><p><strong>🎧 Offizielles Audio (Prompt + Direktiven):</strong><br><audio controls preload=\"none\" style=\"width:100%;max-width:480px\"><source src=\"https://secure-media.collegeboard.org/apc/ap24-german-task-4-cultural-comparison.mp3\" type=\"audio/mpeg\">Ihr Browser unterstützt kein Audio.</audio></p><p><strong>📋 Scoring Guidelines:</strong> <a href=\"https://apcentral.collegeboard.org/media/pdf/ap24-sg-german-language.pdf\" target=\"_blank\" rel=\"noopener\">SG PDF</a></p><hr><p><strong>Ablauf:</strong></p><ol><li>⏱ <strong>4 Minuten</strong> Vorbereitung + <strong>2 Minuten</strong> Präsentation.</li><li>Vergleichen Sie ein kulturelles Thema (im PDF) zwischen <strong>Ihrer eigenen Gemeinschaft</strong> (USA/Korea/etc.) und <strong>dem deutschsprachigen Raum</strong> (D/A/CH).</li><li>🎯 Struktur: Einleitung → Kulturaspekt A → Kulturaspekt B → Ähnlichkeiten/Unterschiede → Fazit.</li><li>📚 Nennen Sie konkrete Beispiele aus Ihrem kulturellen Wissen.</li><li>Sprechen Sie 2 Minuten ohne Pause.</li></ol><p><strong>Präsentationsgliederung / Notizen:</strong></p>",
    "maxPoints": 5,
    "rubric": [
      {
        "part": "Score 5 (Strong)",
        "desc": "Fully accomplishes task. Clear pronunciation, appropriate register, rich vocabulary, varied structures. Fluent delivery.",
        "pts": 1
      },
      {
        "part": "Score 4 (Good)",
        "desc": "Accomplishes task well. Mostly clear pronunciation, appropriate register, good vocabulary. Mostly fluent.",
        "pts": 1
      },
      {
        "part": "Score 3 (Fair)",
        "desc": "Basic accomplishment of task. Occasionally unclear pronunciation. Basic vocabulary. Some hesitation.",
        "pts": 1
      },
      {
        "part": "Score 2 (Weak)",
        "desc": "Partial accomplishment. Unclear pronunciation at times. Limited vocabulary. Frequent hesitation.",
        "pts": 1
      },
      {
        "part": "Score 1 (Poor)",
        "desc": "Minimal accomplishment. Pronunciation impedes comprehension. Very limited vocabulary. Severely halting.",
        "pts": 1
      },
    ]
  },
];
void GERMAN_SET2_MC; void GERMAN_SET2_FRQ;
